### ISSUE TITLE
importing github.com/caffix/amass

### ISSUE THREAD

**Issue by fmpwizard** [OWASP/Amass#1]
Hi,

There are 53 instances of `github.com/caffix/amass` being used across several files, instead of using the code at `github.com/OWASP/Amass` . 

Are you ok if I send a PR to change it? (I checked both, the develop and master branches show this import, so I would be sending the PR to the develop branch)

**Comment by caffix** [comment]
The repo was just copied from caffix/amass, and the imports have been changed in the code I'm currently working on. It will be pushed up soon. Thank you for contributing to the project!
