### ISSUE TITLE
Beyond Amass: Features that move past enumeration

### ISSUE THREAD

**Issue by caffix** [OWASP/Amass#10]
@kerberosmansour wrote:

This is a feature that might not fit Amass, but is more about what to do with the data:

 - Take snapshot of the homepage of each subdomain, present it with visjs in a report.
 - Scan the subdomains on common ports, (perhaps have smart filters for known ports on known subdomain names e.g. ftp.example.com, mail.example.com etc..).
 - Enumerate the technologies running on an FQDN (language/framework/CMS/etc..).
 - Run google dorks agains an FQDN or whole domain and identify potential issues on the site(s).
 - Createing an original feed, this maybe a project in and of itself, but a feed within Amass's control would significantly speed up the enumeration process.

**Comment by fraabye** [comment]
The first two or three of these can easily be done with https://github.com/michenriksen/aquatone which supports receiving data via pipes.

**Comment by caffix** [comment]
I agree, @fraabye. These features seem out of scope for Amass and are being handled by projects such as Aquatone
