### ISSUE TITLE
The system was unable to build the pool of resolver 

### ISSUE THREAD

**Issue by galactghost** [OWASP/Amass#1014]
I am trying to find subdomain but i am getting this message which is in the title again and again . can anyone tell me how to solve this problem .

**Comment by mzpqnxow** [comment]
> I am trying to find subdomain but i am getting this message which is in the title again and again . can anyone tell me how to solve this problem . 

You're going to have to provide more information than that

What version, how did you invoke amass/what does your configuration file look like, and the full and exact output
