### ISSUE TITLE
Failed to create the graph issue

### ISSUE THREAD

**Issue by ultras5631** [OWASP/Amass#107]
Hello! I've got an issue today - i'm getting an Failed to create the graph issue, it started only today, everything was fine earlier.

Amass was installed via snap, All snaps up to date.

What should i do and how i could why this issue appeared?

![image](https://user-images.githubusercontent.com/25612375/53007353-21bf8500-3448-11e9-99e2-c22e8db05cb1.png)

**Comment by AkshayJainG** [comment]
How did you solve it?

**Comment by ultras5631** [comment]
Compiled from the source
