### ISSUE TITLE
Amass doesn't work on Windows Server 2012 R2

### ISSUE THREAD

**Issue by riramar** [OWASP/Amass#11]
I have a Kali Light (Virtualbox machine) and Amass 2.4.1 (snap package) works perfect. Thanks for such amazing tool!
But now I'm trying to run Amass 2.4.1 (prebuilt and complied source code) under Windows Server 2012 R2 (VMware Enterprise VM) and it doesn't work. Since it doesn't have a debug mode I don't know the reason.
The only environment difference between Kali and Windows is that my Windows Server VM is behind a firewall and DNS queries can be maybe only through x.x.x.x internal DNS server and HTTP(S) requests can be maybe only through x.x.x.x HTTP Proxy. The proxy settings seems to be working fine since Go and Git can make HTTP requests without any problem.
Could you please help me to run Amass on this Windows Server?
Thanks!

```
E:\>amass -v -r x.x.x.x -d example.com
No names were discovered
E:\>nslookup
Default Server:  xxx.xxx.xx
Address:  x.x.x.x

> example.com
Server:  xxx.xxx.xx
Address:  x.x.x.x

Non-authoritative answer:
Name:    example.com
Addresses:  2606:2800:220:1:248:1893:25c8:1946
          93.184.216.34
```

**Comment by caffix** [comment]
Hello @riramar, 

Try using the '-log' option when you run the tool: amass -v -log err.log -r x.x.x.x -d example.com

This should give you more insight into the problem. Let me know if that helps.

**Comment by riramar** [comment]
Tried but it creates a empty (0 KB) err.log file. :(

**Comment by caffix** [comment]
Are you able to test it without the HTTP proxy to see if that is the reason? I can imagine that causing problems.

**Comment by riramar** [comment]
I'm not able to test without proxy since it's a private network and I don't have control of any firewall.
To debug I've run Wireshark with some filters and started Amass in order to check the traffic.
I can see some requests going to my proxy but filtering out the proxy IP and checking only ports 80 and 443 I can see some syn packages to different IPs that comes from Amass for sure.
I've checked some of them this specific one 176.9.70.67 can help us. This IP host this website http://ipv4info.com/ which I believe Amass is trying to connect.
Is this information helps you to find the root cause? Please let me know if you need anything else.

**Comment by riramar** [comment]
Hi @caffix , sorry to ask you again but is there anything else that I can try to fix this? Thanks!

**Comment by caffix** [comment]
Seems like you'll need proxy support, which sounds like a feature request.
