### ISSUE TITLE
indexes.bolt permission error

### ISSUE THREAD

**Issue by acknowledgeHim** [OWASP/Amass#110]
I need to run amass from directories where I don't have write access.  It is automated and must be running from with current directory but it tries to open indexes.bolt and because I don't have write access I get a 'permission denied'.  Can I get it to default to /tmp/indexes.bolt instead of my current directory/indexes.bolt?

Thanks!

**Comment by caffix** [comment]
I would like to keep the default as it currently is, but would like to provide a flag that allows the user to identify an alternative location for the graph database file. I assume this will suit your needs as well, correct?

**Comment by huberkev11** [comment]
Yes, that would be perfect.  Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ultras5631** [comment]
> I would like to keep the default as it currently is, but would like to provide a flag that allows the user to identify an alternative location for the graph database file. I assume this will suit your needs as well, correct?

could you, please, write back here when it will be done?
Will be really appreciate

**Comment by caffix** [comment]
I am attempting to push this out today

**Comment by caffix** [comment]
The release for version 2.9.3 went out today. Please try again and let us know if it fixed the issue you were experiencing. Thank you!
