### ISSUE TITLE
[Feature Request] Change returns into exits with proper codes

### ISSUE THREAD

**Issue by DiodonHystrix** [OWASP/Amass#114]
Example:
https://github.com/OWASP/Amass/blob/a26b8e32cd2bf95397684f602b64aa851077961d/cmd/amass/main.go#L154-L156

Instead of `return` it could be `os.Exit(1)` like here:
https://github.com/OWASP/Amass/blob/a26b8e32cd2bf95397684f602b64aa851077961d/cmd/amass/main.go#L116-L123

It would allow to easier write scripts that use amass.
I could submit PR if you liked the idea.

**Comment by caffix** [comment]
I can make these changes with the upcoming updates to the amass tool. Thank you for the feature request!

**Comment by DiodonHystrix** [comment]
Thank you a lot:) Really like the tool :+1:

**Comment by caffix** [comment]
Have the recent changes helped you with scripting?

**Comment by DiodonHystrix** [comment]
Yes :) Thank you a lot! Feel free to close this issue. If I have any more requests or issues, I'm gonna open a new issue then.

**Comment by caffix** [comment]
Sounds good. Thank you!
