### ISSUE TITLE
-df not work on linux

### ISSUE THREAD

**Issue by sieunhando** [OWASP/Amass#115]
Hi, I'm trying to load website list but it not work. It still work for single domain. I tried in Debian and Ubuntu. I also tried rebuild binary it but not work too.

**Comment by fork-while-fork** [comment]
Hi @sieunhando,

We merged some changes this morning that I believe may fix your issue. Can you build from the latest develop branch and let me know if that fixes your issue?

Thanks

**Comment by sieunhando** [comment]
I tried but still not work with domain list.

**Comment by caffix** [comment]
The release went out today. Please try updating it again

**Comment by caffix** [comment]
I used a list with nearly 200 domain names today. It worked great. Is version 2.9.3 giving you the same results?
