### ISSUE TITLE
"Failed to create the graph"

### ISSUE THREAD

**Issue by Viss** [OWASP/Amass#119]
Fresh pull from github (2/26/2019) as well as the binary release - I can't run amass at all, with any args, that don't produce this error.

**Comment by caffix** [comment]
You need to have write permissions in the current working directory so it can create the graph database. Version 2.9.3 will allow you to create the graph in an alternative directory.

**Comment by Viss** [comment]
This is being done on a throwaway vm, and I am operating as root.

**Comment by caffix** [comment]
Due to naming used in version 2.9.2, you also cannot run amass in the same directory as the binary

**Comment by caffix** [comment]
Version 2.9.3 was released today and should handle the issue you were experiencing

**Comment by caffix** [comment]
All set with version 2.9.3?

**Comment by Viss** [comment]
yep! thanks man, excellent work!

**Comment by caffix** [comment]
Great! I'll close the issue then.
