### ISSUE TITLE
JSON CIDR field error

### ISSUE THREAD

**Issue by edelahozuah** [OWASP/Amass#123]
Version 0.93 (at least) changed the way of representing CIDR. Previously (at least 0.90), cidr JSON filed was a  string, with the CIDR in 'X.X.X.X/YY' format. In 2.9.3, CIDR is an object instead with the following fields:

- IP: network address
-Mask: base64-encoded Hex representation of the network mask

For instance:
"cidr":{"IP":"213.149.224.0","Mask":"///8AAA=="}
Whis is equivalent to:
213.149.224.0/21

**Comment by caffix** [comment]
Thank you for bringing this to our attention! It will be fixed in version 2.9.4, which is providing some quick fixes to several parts of the Amass tool suite.

**Comment by caffix** [comment]
The fix will be in the release going out tomorrow. Thanks again!
