### ISSUE TITLE
Can i use OWASP Amass to find the ip's in a network.

### ISSUE THREAD

**Issue by minnumerinalex** [OWASP/Amass#125]
i need to list all the ip's in a local network.can i use OWASP Amass for  this.if so how will configure amass to achieve the same.

**Comment by caffix** [comment]
Currently, OWASP Amass performs enumeration of Internet-facing systems for target domain names.

**Comment by minnumerinalex** [comment]
can you please suggest me a tool to get the list of ip's in LAN

**Comment by caffix** [comment]
[Nmap](https://nmap.org/) is the rock solid tool for identifying active systems on a network. It can also list IPs within a target CIDR/LAN.

If you are attempting to generate all the IPs within a CIDR/Subnet/LAN within a program you're developing, then perhaps some good Go code would work, like [go-cidr](https://github.com/nytr0gen/go-cidr)

**Comment by minnumerinalex** [comment]
thank you
