### ISSUE TITLE
Amass command not found on Kali Linux (solution)

### ISSUE THREAD

**Issue by Lokillo20** [OWASP/Amass#127]
In Kali a have problems when execute amass ("command not found") , I solve with this: 
sudo apt install snapd
sudo systemctl start snapd
sudo systemctl enable snapd

We also add apparmor to autoload (otherwise there will be an error):

systemctl start apparmor
systemctl enable apparmor

Modify ~/.bashrc with this:

>nano ~/.bashrc

add line
:

export PATH=$PATH:/snap/bin

For the changes to take effect:
>source ~/.bashrc

I hope it help!﻿

**Comment by caffix** [comment]
Thank you for the contribution! It has been added to the README

**Comment by vellangelus00** [comment]
You are my savior! That the old Gods bless you!
