### ISSUE TITLE
amass is unstable

### ISSUE THREAD

**Issue by icezhaoL** [OWASP/Amass#133]
OWASP Amass v2.9.4                     
--------------------------------------------------------------------------------
17 names discovered - api: 1, scrape: 1, brute: 15
--------------------------------------------------------------------------------
ASN: 132203 - TENCENT-NET-AP-CN Tencent Building, Kejizhongyi Avenue, CN
	119.28.38.0/23    	2    Subdomain Name(s)
ASN: 4808 - CHINA169-BJ China Unicom Beijing Province Network, CN
	101.236.8.0/21    	13   Subdomain Name(s)
ASN: 23724 - CHINANET-IDC-BJ-AP IDC, China Telecommunications Corporation, CN
	36.110.128.0/19   	1    Subdomain Name(s)
ASN: 8151 - Uninet S.A. de C.V., MX
	189.163.0.0/19    	1    Subdomain Name(s)

brute api scrape:
A lot of domain were grabbed, but the results were few.

**Comment by caffix** [comment]
Can you clarify as to how the information you have provided shows instability?
