### ISSUE TITLE
My internet connection gets lost everytime after using Amass

### ISSUE THREAD

**Issue by AhmadEgb** [OWASP/Amass#136]
It looks like that amass sends a huge number of requests every second which resulted in me being blocked from using the internet from my ISP for 15 min (As a result of suspicious activity)!
It's important to have an options to make Amass move "slower"

**Comment by caffix** [comment]
I definitely agree. We will be exposing a option to control the maximum number of concurrent DNS queries in the next release

**Comment by caffix** [comment]
The ability to control network utilization is now available and can be used via the '-max-dns-queries' flag

**Comment by SAGEof6iixPATHS** [comment]
How many queries are sent usually because I also have the same problem.

**Comment by Shaif111** [comment]
i face same problem , please give me solution.

**Comment by caffix** [comment]
Check the help information. The newer '-dns-qps' flag allows you to control DNS queries sent per second and will reduce the traffic generated on your network. There are two similar flags that allow you to control the QPS sent to trusted and untrusted DNS resolvers
