### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by AhmadEgb** [OWASP/Amass#138]
1) After running Amass I can't find the output file! (I searched everywhere on my windows).
2) why enabling Brute Force disables other methods for finding subdomains (I got fewer results after enabling it)?

**Comment by caffix** [comment]
As long as you have permissions to create the output directory, it should be created in the current working directory, or you can use '-dir' to identify a preferred location.

Using brute forcing does not disable other methods, but it does generate a lot of traffic that could cause other DNS queries to be dropped and time out. This is being addressed right now
