### ISSUE TITLE
Passive Name Checks

### ISSUE THREAD

**Issue by kdebacker** [OWASP/Amass#139]
Amass returns non-existant subdomains when doing a multiple different passive scan.

I ran the following commands using Amass v2.9.4 as an example:
```
amass -passive -d owasp.org
amass -passive -d owasp-amass.com
```

And the following subdomains stood out to me and don't resolve to anything:
* -www.owasp.org
* 2b-www.owasp.org
* 3awww.owasp.org
* -www.owasp-amass.com
* 2b-www.owasp-amass.com
* 3awww.owasp-amass.com

The `-www.owasp.org` and `-www.owasp-amass.com` subdomains are invalid, since subdomains cannot start or end with a dash.

Is this a bug in the tool, or are these the most reliable results we can get using a passive scan?
If that is the case, what flags would be required to get the most accurate and reliable results using Amass?

**Comment by caffix** [comment]
The -passive flag only returns the findings from available data sources, and does not validate the findings using DNS. If you would like to take full advantage of the capabilities provided by Amass, do not use the -passive flag

**Comment by kdebacker** [comment]
I understand that the subdomains don't get checked when running a passive scan, but I thought it was interesting that the same names showed up for different domains.
I was also wondering if it would be beneficial to add a check for names starting or ending with a dash since that is invalid, as specified under section 2.3.1 of the [1035 rfc](https://tools.ietf.org/html/rfc1035)

**Comment by caffix** [comment]
Improvements have been made in version 2.9.7
