### ISSUE TITLE
Failed to create the directory: mkdir amass_output: permission denied

### ISSUE THREAD

**Issue by thedr0pperx** [OWASP/Amass#140]
Hi, I installed the tool on a fresh version of ubuntu 16.04 using snapd.
Whenever i run the tool i get;
Failed to create the directory: mkdir amass_output: permission denied

I have tried creating this folder and chmod 777 the folder
i have tried using dir flag and also get permission denied, and even permission denied when i create the folder myself and chmod 777 it. I've also tried chmod 755.

How can i fix this?

**Comment by thedr0pperx** [comment]
The only place i can seem to run the tool is /tmp however this is not practical for me

**Comment by caffix** [comment]
As long as you have write permissions in the directory where the amass_output directory is being create, you should be alright

**Comment by caffix** [comment]
Also, you can specify where to place the output directory using the '-dir' flag
