### ISSUE TITLE
Error opening files

### ISSUE THREAD

**Issue by Damian89** [OWASP/Amass#146]
Hi,

amass worked for a long time but stoped working because of the following error:

__Error:__
`Error opening the file very-common.txt: open very-common.txt: no such file or directory`

__Test command:__ 
`amass -brute -w very-common.txt -d damianschwyrz.de -dir /tmp`

__Amass version:__
`OWASP Amass 2.9.9`

__uname -a:__
`Linux v27964.php-friends.de 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

The file is there, tryed different filenames. The same error can be observed when I want to specify my own resolvers.txt file.

Tryed executing the command with and without root rights. Also set up a simple Vagrant Box based on Ubuntu 18.10 and installed via snapd. Same result.

Any ideas? Thanks

**Comment by Damian89** [comment]
I removed amass using snap remove amass and build it from source. Now it works. Strange.

**Comment by caffix** [comment]
Snap does have some isolation constraints that create restrictions on how the tool can be used, but this does not usually prevent users from opening text files. Thank you for the feedback!
