### ISSUE TITLE
[Request] Detect False DNS resolvers and DNS benchmark before scan.

### ISSUE THREAD

**Issue by panchocosil** [OWASP/Amass#148]
Hello there, I like to point that having a valid list of DNS resolvers when looking new subdomains is very important, especially if we looking inside wildcard subdomains. 

For example some Public dns  don't resolve back the real dns record of certain sub-domains. 

Ex:
`dig @66.173.0.3 homexxxxx.example.com`

The subdomain` homexxxxx` does not exist and is returning  A record `198.105.254.19`  This sort of `dns resolver ips` mess with `amass` big time and I'm almost sure that this is messing with many users results when using amass.

Ideas for amass:
1. Detect false DNS resolvers that don't return a valid DNS response. [ similar tool but in python.](https://github.com/teknogeek/fresh.py)
2. DNS benchmark to detect speed and state of DNS resolvers.

This may will help with:
1. amass current subdomains wildcard detection.
2. amass current memory loss.
3. amass speed when resolving

I hope this helps. Best.

**Comment by caffix** [comment]
This feature has been completely implemented and works quite well. Thank you for the request!
