### ISSUE TITLE
Incorrect parsing of wildcard certificate CNs with certain TLDs in 'net' mode

### ISSUE THREAD

**Issue by commiebobdole** [OWASP/Amass#15]
I am having an issue when trying to perform discovery in 'net' mode on a server whose certificate has the following characteristics:

- Is a wildcard certificate (ex: foo.com.pl)
- Is in a national TLD which uses a subdomain as a defacto TLD, (ex: .com.pl, .co.uk)

This results in the return of a large number of false-positive results from the [ThreatCrowd] data source that appear to be random members of the national TLD's subdomain; it appears that ThreatCrowd is enumerating all of the domains in, for instance, .com.pl. Example output is below:

```
[ThreatCrowd] lupus1.com.pl,85.128.135.19
[ThreatCrowd] b-52.com.pl,46.4.42.105
[ThreatCrowd] 12.com.pl,188.128.255.251
[ThreatCrowd] m21.com.pl,91.228.197.30
[ThreatCrowd] 02.com.pl,93.157.100.74
[ThreatCrowd] rs232.com.pl,138.201.172.157
```

This behavior does not occur when enumerating subdomains with the '-d' switch. Here's an example site that can be used to demonstrate this behavior:

https://dhl24.com.pl (cert is issued to '*.dhl24.com.pl')
Site's IP address is 91.227.200.193

**Comment by caffix** [comment]
Thank you very much for discovering this bug! I have fixed it, and you will see the commit soon.

As a side note: The functionality that pulls domain names from network infrastructure parameters has been moved into a separate program named 'amass.netnames' in order to simplify the tools.
