### ISSUE TITLE
Writing to output file adds an extra space after each domain

### ISSUE THREAD

**Issue by geeknik** [OWASP/Amass#150]
When amass writes to an output file with the -o flag, it adds a space to the end of each domain. Is there a way to fix that? My command line: `amass -df domains.txt -active -brute -w wordlist.txt -noalts -norecursive -o sub-domains.txt`

**Comment by caffix** [comment]
The next release will have the fix for this issue

**Comment by caffix** [comment]
See if you're still experiencing this issue in version 2.9.10. Thanks!

**Comment by geeknik** [comment]
LGTM, thank you!
