### ISSUE TITLE
Result missing for scraping source VirusTotal

### ISSUE THREAD

**Issue by ramshazar** [OWASP/Amass#151]
Hi,

I created a DNS entry for virustotal.curl-pipe-sudo-bash.de and pointed that to 8.8.8.8.
Afterwards I searched that host name on VirusTotal. That made it available on [VirusTotal itself](https://www.virustotal.com/gui/domain/curl-pipe-sudo-bash.de/relations).

If I use Amass version 2.9.9 as "amass -src -ip -active -d curl-pipe-sudo-bash.de" I do not get virustotal.curl-pipe-sudo-bash.de as a result. I expected it to be shown there.
Am I doing it wrong? 

As far as I understand VirusTotal changed there website some time ago. It may be an issue that https://github.com/OWASP/Amass/blob/master/amass/sources/virustotal.go#L70 is a HTTP 302.
Do you have any advise?

Kind regards,
Matthias

**Comment by caffix** [comment]
I was able to obtain the subdomain name from VirusTotal

**Comment by caffix** [comment]
Both URLs are working for me, but I'll switch to the one suggested by @dhauenstein, since it provides the JSON output

**Comment by dhauenstein** [comment]
Funny, the original one did not work for me.. Not sure if this is a regional thing? 
I clearly get a 302 redirect, which would not be handled correctly as far as I can see: 

```
$ curl -si https://www.virustotal.com/en/domain/google.com/information/ 
HTTP/2 302
x-xss-protection: 1; mode=block
content-language: en
vary: Cookie
location: https://www.virustotal.com/gui/domain/google.com
x-frame-options: sameorigin
content-type: text/html; charset=utf-8
set-cookie: VT_PREFERRED_LANGUAGE=en; expires=Mon, 06-May-2019 13:58:12 GMT; Max-Age=604800; Path=/
x-cloud-trace-context: 514a85c11e63011f1c54871d00e15c14
date: Mon, 29 Apr 2019 13:58:12 GMT
server: Google Frontend
content-length: 0
```

See https://github.com/OWASP/Amass/blob/master/amass/utils/network.go#L106

**Comment by dhauenstein** [comment]
By the way, it also does not work after the redirect: 

```
$ curl -sLi https://www.virustotal.com/en/domain/google.com/information/ | grep google.com
location: https://www.virustotal.com/gui/domain/google.com
```

**Comment by caffix** [comment]
Thank you, @dhauenstein! I added you as a co-author on PR#155

**Comment by caffix** [comment]
Version 2.9.10 contains the fix for this issue

**Comment by ramshazar** [comment]
Thank you, caffix. It works as expected.

**Comment by caffix** [comment]
Great!
