### ISSUE TITLE
[Tool run error] Crtsh: Failed to connect to the database server: dial tcp 91.199.212.48:5432: connect: connection refused

### ISSUE THREAD

**Issue by s7x** [OWASP/Amass#154]
Hi there!

After running a scan with a huge wordlist (dns-jhaddix.txt), I encounter this error when trying to launch another one:

```
Crtsh: Failed to connect to the database server: dial tcp 91.199.212.48:5432: connect: connection refused
```
Version used: **version 2.9.9**

Cheers!

**Comment by caffix** [comment]
Looks like they blocked you

**Comment by jaikishantulswani** [comment]
@caffix I am also getting the same 
`Crtsh: Failed to connect to the database server: dial tcp 91.199.212.48:5432: connect: connection refused
`

**Comment by caffix** [comment]
It's possible to push your luck with any of the data sources. I am making one improvement to the situation thanks to @s7x

**Comment by tja** [comment]
The same is happening to me. From several IPs, many of which I never used for recon before. I would assume the crt.sh server is having general issues.

**Comment by dhauenstein** [comment]
Maybe a fallback to web scraping makes sense when the db is down. IIRC crtsh db access is not planned to be very stable, so a fallback may be a good solution.

**Comment by m4xx101** [comment]
Getting this same error, does any one has explanation why is this happening.? 

>  Crtsh: Failed to connect to the database server: dial tcp 91.199.212.48:5432: connect: connection refused 

Here is the snap

![Screenshot from 2019-04-30 23-40-07](https://user-images.githubusercontent.com/46222738/56983477-59158500-6ba1-11e9-9e72-29094c07ef31.png)

**Comment by s7x** [comment]
Hi everyone. For now, until the release of the fix, you can still run the tool using the sources.

- First do amass -list to get all the source names
- amass -d <domain> -include <all sources except Crtsh>

Cheers!

**Comment by dhauenstein** [comment]
Or simply use `-exclude crtsh` :)

**Comment by m4xx101** [comment]
Oh thank you so much 😊

**Comment by s7x** [comment]
@dhauenstein Even better! Thanks for the tip!

**Comment by Teicu** [comment]
hi 

same error here 

Crtsh: Failed to connect to the database server: dial tcp 91.199.212.48:5432: connect: connection refused

**Comment by caffix** [comment]
See if you're still experiencing this issue in version 2.9.10

**Comment by dhauenstein** [comment]
Please note: crt.sh seems to have some issues right now. The DB is not working, and it seems the website (now that every tool is scraping instead of using the DB) is not responding correctly all the time either. Hope they get this fixed soon, crt.sh is a valuable source for DNS recon..

**Comment by Teicu** [comment]
> See if you're still experiencing this issue in version 2.9.10

works fine now, thank you. No more errors 

Cheers

**Comment by s7x** [comment]
Working fine now. Closing the issue. Thanks everyone for your help & tests!
