### ISSUE TITLE
Feature Enhancement: Make alteration words configurable

### ISSUE THREAD

**Issue by dhauenstein** [OWASP/Amass#157]
It would be great if the list of alteration words could be set by the user. Right now the list ist hard coded in `alteration_words.go`. 
I would love to see this list being configurable for using it with in custom wordlists, for example created by using [CeWL](https://digi.ninja/projects/cewl.php).

**Comment by caffix** [comment]
Great suggestion! @fork-while-fork and I were asked about this during the BSidesROC talk. We can definitely implement this feature

**Comment by caffix** [comment]
This feature is now available in version 2.9.11
