### ISSUE TITLE
Failed to open the data operations output file: open amass_output/amass_data.json: too many open files

### ISSUE THREAD

**Issue by oldesec** [OWASP/Amass#161]
Hi.

Errors occur in the "2.9.10" version.

My command line : 
```
 ./amass -d twitter.com  -ip -rf resolvers.txt -active -o amass-output.txt -min-for-recursive 3
```

error:
```
Failed to open the data operations output file: open amass_output/amass_data.json: too many open files
```

There seems to be a problem with the "resolvers.txt" file.

If the "-rf" option is not used, no error will occur.

However, the "resolvers.txt" file does not appear to have any special problems.

```
$ cat resolvers.txt | sort | uniq | wc -l
9073
```

**Comment by caffix** [comment]
Each line (resolver) in the resolvers file opens a file handle for UDP communications with the server. If your system does not allow you to have that many file handles open for a single process, then the error you're receiving is to be expected

**Comment by dhauenstein** [comment]
Check the output of this command (if on a Linux box): 

`ulimit -n`

If this is significantly lower than the list of resolvers, this might be a problem. 
Here's a link with a description and a solution to it: 

https://easyengine.io/tutorials/linux/increase-open-files-limit
