### ISSUE TITLE
wildcard domain not  dispose

### ISSUE THREAD

**Issue by icezhaoL** [OWASP/Amass#163]
wildcard domain not  dispose when brute

**Comment by icezhaoL** [comment]
![image](https://user-images.githubusercontent.com/14086616/57219193-df124f80-7029-11e9-9d2b-5065c44c5324.png)
![image](https://user-images.githubusercontent.com/14086616/57219196-e2a5d680-7029-11e9-92e8-487a4661c9dc.png)
 get a lot of invalid results

**Comment by caffix** [comment]
I would try slowing down the DNS queries using the '-max-dns-queries' flag, and if you continue to have trouble with a subdomain, use the '-bl' or '-blf' flags for blacklisting

**Comment by dhauenstein** [comment]
Actually, this seems like a legit issue. I tried to brute force that same domain, and I have a result where I would not expect one: 
```
$ amass -brute -ip -d openvpn.7.cainiao.com  -src -max-dns-queries 2
[Brute Forcing]   ad.openvpn.7.cainiao.com 23.89.5.60
```

This seems to be a false positive: 
```
$ host -t any ad.openvpn.7.cainiao.com
Host ad.openvpn.7.cainiao.com not found: 3(NXDOMAIN)
```

Anyhow, this does not seem to be an issue with the wildcard detection (in this case the `host` command would return the wildcard IP address) but rather with the brute force module.

**Comment by dhauenstein** [comment]
Maybe this is the same issue as in #148?

**Comment by dhauenstein** [comment]
Yandex seems to be the culprit one:
`resolver = 77.88.8.8 ; Yandex.DNS`

Using this DNS server we get: 
```
$dig +short @77.88.8.8 ad.openvpn.7.cainiao.com
49.2.123.56
$dig +short @77.88.8.8 ad.openvpn.7.cainiao.com
23.89.5.60
```

Testing this against Google DNS: 

```
$dig +short @8.8.8.8 ad.openvpn.7.cainiao.com
```

No result. Either check the list of hardcoded DNS servers in amass or implementing #148 should fix this.

**Comment by caffix** [comment]
@icezhaoL Does removing the Yandex.DNS solve this problem for you?

**Comment by icezhaoL** [comment]
ok Thank you for your patience@caffix  @dhauenstein

**Comment by caffix** [comment]
@icezhaoL We appreciate the feedback, which caused us to discover the problem with the resolver. If you're all set, then I'll close this issue once Yandex.DNS has been removed from the default list of resolvers
