### ISSUE TITLE
Some domain names are wrong

### ISSUE THREAD

**Issue by icezhaoL** [OWASP/Amass#165]
![image](https://user-images.githubusercontent.com/14086616/57764435-05c13c00-7736-11e9-936b-d9aee51bb0a2.png)
i don't know why

**Comment by icezhaoL** [comment]
linux  is ok ,  windows is wrong

**Comment by caffix** [comment]
@danmartinj @rbadguy @s7x Can you help discover the reason for this issue? Thanks!

**Comment by caffix** [comment]
@icezhaoL When I just tested Amass on Windows, it ran quite well (very fast), so I'm not sure what trouble you're experiencing

**Comment by s7x** [comment]
I'll do some tests in a few minutes at home.
Which version are you using @icezhaoL?

**Comment by icezhaoL** [comment]
2.9.11

**Comment by s7x** [comment]
Hey @icezhaoL sorry for the delay, can you try with the new version? The whole tool got a new rework on many points/features.

Try with this command:
```
amass.exe enum -src -ip -d yourdomainhere.com
```
With the **amass_3.0.3_windows_amd64.zip** binary.

Cheers

**Comment by caffix** [comment]
@icezhaoL Has this issue been resolved for you?

**Comment by icezhaoL** [comment]
![image](https://user-images.githubusercontent.com/14086616/61604137-e0d7d080-ac72-11e9-8ffe-8b989983aca0.png)
Outages occur when large domain names are encountered

**Comment by icezhaoL** [comment]
```
mode = active
output_directory = amass_output
maximum_dns_queries = 2000000
[network_settings]
port = 443
[resolvers]
resolver = ******
resolver = ******
[blacklisted]
subdomain = ******
[bruteforce]
enabled = true
recursive = true
minimum_for_recursive = 2
wordlist_file = **********
[alterations]
enabled = true
minimum_for_word_flip = 2
edit_distance = 1
flip_words = true   
flip_numbers = true 
add_words = true    
add_numbers = true  
wordlist_file = **********
[BinaryEdge]
apikey = **********
[Censys]
[CertDB]
[DNSDB]
[PassiveTotal]
[SecurityTrails]
[Shodan]
[Umbrella]
[URLScan]
[VirusTotal]
[Riddler]
[NetworksDB]
[Spyse]

```

**Comment by caffix** [comment]
What type of outage are you referring to? Your current network, DNS resolvers or the target organization’s infrastructure?

Turning up the maximum DNS queries to two million concurrent requests could definitely cause some problems if your network cannot handle it or you do not have enough resolvers to spread the load across. Additionally, some organizations will detect such a large amount of traffic and throttle the activity.

I hope that helps, and we appreciate the feedback!

**Comment by icezhaoL** [comment]
Can we control the rate of transmission?

**Comment by s7x** [comment]
@icezhaoL & @caffix can we close this issue now? Do we consider this solved?

**Comment by icezhaoL** [comment]
Has been resolved
