### ISSUE TITLE
Failed to build docker image

### ISSUE THREAD

**Issue by L3K0V** [OWASP/Amass#166]
Hello I faced problem building a Docker image with latest 2.9.11 version

```
$ docker build -t amass https://github.com/OWASP/Amass.git
Sending build context to Docker daemon  22.28MB
Step 1/11 : FROM golang:alpine as build
 ---> c7330979841b
Step 2/11 : WORKDIR /go/src/github.com/OWASP/Amass
 ---> Using cache
 ---> 5d47d0cbc21f
Step 3/11 : COPY . .
 ---> 919d495bd4b3
Step 4/11 : RUN apk --no-cache add git   && go get -u github.com/OWASP/Amass/...
 ---> Running in d4e2063a66b4
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/6) Installing nghttp2-libs (1.35.1-r0)
(2/6) Installing libssh2 (1.8.2-r0)
(3/6) Installing libcurl (7.64.0-r1)
(4/6) Installing expat (2.2.6-r0)
(5/6) Installing pcre2 (10.32-r1)
(6/6) Installing git (2.20.1-r0)
Executing busybox-1.29.3-r10.trigger
OK: 20 MiB in 21 packages
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
# cd /go/src/github.com/OWASP/Amass; git pull --ff-only
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
package github.com/OWASP/Amass/amass: exit status 128
The command '/bin/sh -c apk --no-cache add git   && go get -u github.com/OWASP/Amass/...' returned a non-zero code: 1
```

**Comment by rbadguy** [comment]
I was able to install via docker, confirmed proper version using "docker run amass -version" . 
I did not run "cd /go/src/github.com/OWASP/Amass; git pull --ff-only", the amass in your go path should be different than the docker image unless you are trying to do something else.

**Comment by L3K0V** [comment]
I think the build process using the Dockerfile runs `# cd /go/src/github.com/OWASP/Amass; git pull --ff-only` not me. I'm trying to build the docker image outside the project folder without any go environment.

**Comment by caffix** [comment]
@L3K0V You should now be able to build the Docker image. Also, please check out the updated documentation related its use, since it covers employing a volume to persist the graph database across executions of Amass.

**Comment by L3K0V** [comment]
@caffix, It is look like the Dockerfile you have updated is still on development branch on your fork. I will try it tomorrow and hope it will be merged here soon. I'm aware of the working dir and the persistence volume which are needed when using amass with docker. Thanks for that!
