### ISSUE TITLE
[New source] Let's Encrypt Oak

### ISSUE THREAD

**Issue by s7x** [OWASP/Amass#168]
Hi there,

Let's Encrypt is launching is own **Certificate Transparency service**!
I think this could be a great new addition to the source list for subdomain enumeration.

[Introducing Oak, a Free and Open Certificate Transparency Log](https://letsencrypt.org/2019/05/15/introducing-oak-ct-log.html)

**Announcement from Let's Encrypt:**

> Today we are announcing a new Certificate Transparency log called Oak. The Oak log will be operated by Let’s Encrypt and all publicly trusted certificate authorities will be welcome to submit certificates.
> 
> We decided to create and operate a CT log for a few reasons. First, operating a log is consistent with our mission to create a more secure and privacy-respecting Web. We believe transparency increases security and empowers people to make well-informed decisions. Second, operating a log helps us take control of our destiny. Google Chrome requires all new certificates to be submitted to two separate logs, so multiple log options are imperative to our operation. Finally, Let’s Encrypt often issues more than 1M certificates each day, so we wanted to design a CT log that is optimized for high volume. We’ve designed our log to be able to handle submissions from all other publicly trusted Certificate Authorities so they can use Oak to fulfill their logging requirements as well.

[Link to the CT-Logs docs with public keys](https://letsencrypt.org/docs/ct-logs/)

Cheers!

**Comment by Edu4rdSHL** [comment]
Seems that they doesn't provide an API.

**Comment by meme-lord** [comment]
This source is already covered by https://crt.sh/monitored-logs . Issue should probably be closed .

**Comment by caffix** [comment]
Thank you @meme-lord
