### ISSUE TITLE
Example config link in help menu points to dead github link

### ISSUE THREAD

**Issue by sethsec** [OWASP/Amass#171]
Version/Build 2.9.12
```
root@kali:/opt/amass/amass_2.9.12_linux_amd64# ./amass       

<snip>

  -w string
        Path to a different wordlist file

An example configuration file can be found here: 
https://github.com/OWASP/Amass/blob/master/examples/amass_config.ini

```
This is the link that you want, i think: 
```https://github.com/OWASP/Amass/blob/master/examples/config.ini```

**Comment by caffix** [comment]
Thank you, @sethsec! This has been updated in the develop branch and will be fixed in version 2.9.13
