### ISSUE TITLE
doc: Amass Terminal Capture video is unavailable

### ISSUE THREAD

**Issue by mikesamuel** [OWASP/Amass#176]
In the User Guide under [Amass Terminal Capture](https://github.com/OWASP/Amass/blob/master/doc/user_guide.md#amass-terminal-capture), the preview shows "This recording has been archived" and clicking through to https://asciinema.org/a/v6B1qdMRlLRUflpkwRPhvCTaY I get

> This recording has been archived
> All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

**Comment by caffix** [comment]
Thank you for your contribution. This issue is currently in the process of being fixed in PR#175. We appreciate you bringing it to our attention
