### ISSUE TITLE
Installation error:

### ISSUE THREAD

**Issue by Tikam02** [OWASP/Amass#18]
Error while Installing Amass
os : Kali linux
@caffix 
![screenshot from 2018-08-12 21-38-57](https://user-images.githubusercontent.com/10548085/44003917-50b682b6-9e78-11e8-925a-a0d27a36218b.png)

**Comment by mkonda** [comment]
I found that you have to install those packages by hand first to make it work.
i.e.
`go get github.com/asaskevich/EventBus`

I do think the packaging could use work to get it to where it will pull these automatically and fit the typical Go "way of doing things" without snapcraft.  I was hoping to create a branch and try to add this but I haven't had time yet ...

**Comment by caffix** [comment]
I looks like you’re not inside the GOPATH while running the install command. You may want to install with snap instead.

**Comment by caffix** [comment]
@mkonda It would be great to discuss your proposal on the chat server. Sound good?

**Comment by bardelch** [comment]
Command does not download dependancies:
$ go get -u github.com/OWASP/Amass
package github.com/OWASP/Amass: no Go files in $GOPATH/src/github.com/OWASP/Amass

this command works:
$ go get -u github.com/OWASP/Amass/...

as referenced by ponzu-cms/ponzu#204

====
in README.md
-$ go get -u github.com/OWASP/Amass
+$ go get -u github.com/OWASP/Amass/...

**Comment by caffix** [comment]
Great! Now do the following:

$ cd $GOPATH/src/github.com/OWASP/Amass

$ go install ./...

Then you will find the binaries in $GOPATH/bin

**Comment by riramar** [comment]
No need to cd into the src dir and install. The -u (update) do it for you.

https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies
> The -u flag instructs get to use the network to update the named packages and their dependencies. By default, get uses the network to check out missing packages but does not use it to look for updates to existing packages.

Now I'm not not sure why exactly the command "go get -u github.com/OWASP/Amass/..." works and "go get -u github.com/OWASP/Amass" it doesn't.

```
root@zion:~/go# go get -u github.com/OWASP/Amass/...
root@zion:~/go# amass -version
version v2.5.2
root@zion:~/go# 
```

Seems to be related to the path as you can see from this explanation about the

https://golang.org/cmd/go/#hdr-Package_lists
> An import path is a pattern if it includes one or more "..." wildcards, each of which can match any string, including the empty string and strings containing slashes. Such a pattern expands to all package directories found in the GOPATH trees with names matching the patterns.
> To make common patterns more convenient, there are two special cases. First, /... at the end of the pattern can match an empty string, so that net/... matches both net and packages in its subdirectories, like net/http. Second, any slash-separated pattern element containing a wildcard never participates in a match of the "vendor" element in the path of a vendored package, so that ./... does not match packages in subdirectories of ./vendor or ./mycode/vendor, but ./vendor/... and ./mycode/vendor/... do. Note, however, that a directory named vendor that itself contains code is not a vendored package: cmd/vendor would be a command named vendor, and the pattern cmd/... matches it. See golang.org/s/go15vendor for more about vendoring.

As an example subfinder can be installed just using the command "go get -u github.com/subfinder/subfinder".

**Comment by caffix** [comment]
In the past, you could install Amass using "go get -u github.com/OWASP/Amass," but since it has a cmd directory with multiple binaries to be installed, it requires the ./... wildcard to be provided.

**Comment by caffix** [comment]
So, from now on, we will be installing from source using the following command: "go get -u github.com/OWASP/Amass/..."
