### ISSUE TITLE
User Lost when executing amass command

### ISSUE THREAD

**Issue by eFiiel** [OWASP/Amass#180]
When executing an amass command, including "amass -h" , My computer's user get lost, like if i am not logged in anymore, anything that would need my user does not work anymore, like sudo.
I also cannot log in again, it says my user does not exist, the only solution is rebooting my pc.
![Screenshot from 2019-06-04 10-24-40](https://user-images.githubusercontent.com/11728601/58882601-fe48df00-86b2-11e9-826f-793602f66e59.png)

As you can see, that is the result of running a command.

**Comment by caffix** [comment]
Amass does not interfere with user accounts.

**Comment by eFiiel** [comment]
Okay, I guessed that, I just wanted to know if it has happened with anyone else, even if in another circunstances.
Well, thanks anyway

**Comment by caffix** [comment]
Please feel free to bring a topic like this to the chat server.

**Comment by eFiiel** [comment]
I am new here, how can I access the chat server ?

**Comment by caffix** [comment]
https://discord.gg/rtN8GMd
