### ISSUE TITLE
Doc: install.md is not correct  

### ISSUE THREAD

**Issue by BruceGitHub** [OWASP/Amass#181]
Doc: install.md  it's incorrect. Report `sudo docker run amass --passive -d example.com`
but it should be `sudo docker run amass enum -d example.com`

**Comment by caffix** [comment]
Thank you for the good catch! We'll be sure to update the docs in the next release

**Comment by BruceGitHub** [comment]
If you want I make a mini PR...

**Comment by caffix** [comment]
Sounds good to me. Please have the PR base branch be 'develop'

**Comment by caffix** [comment]
PR#193 has made the fix. Thanks!
