### ISSUE TITLE
No names were discovered

### ISSUE THREAD

**Issue by npbhatter17** [OWASP/Amass#182]
I'm using version 3.0.3 and running this command returns no result.
./amass enum -d example.com
No names were discovered

I know there are new changes in version 3. So trying to understand if i'm missing anything or doing wrong on my side.

**Comment by caffix** [comment]
Try using the '-passive' flag first, to see that amass can reach the data sources. Once that has returned names, then try changing your DNS resolver to one you can reach using the '-r' flag.

For more help, please join our Discord chat server: https://discord.gg/rtN8GMd
