### ISSUE TITLE
Failed to obtain the wordlist

### ISSUE THREAD

**Issue by CaijiOrz** [OWASP/Amass#189]
Sometimes i use amass will report this error:

> Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: Get https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Does amass not use a local wordlist by default?

**Comment by caffix** [comment]
If you do not provide wordlists, Amass currently reaches out to obtain the default wordlists.

**Comment by gotr00t0day** [comment]
I'm still getting that error even when I provide my own wordlist

**Comment by ShellInjector** [comment]
Also Here!
Even i'm using my wordlist , i'm getting same error!

**Comment by Anderson0abr** [comment]
Same here

**Comment by berzerk0** [comment]
I'm getting this error even when supplying my own wordlist. 

Could it be the wordlist is inaccessible at the time of this writing?

> $ amass enum -passive -d example.com -json ./amassTool_subdomains.json -dir . -w wl.txt
> 
> Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found

**Comment by berzerk0** [comment]
> I'm getting this error even when supplying my own wordlist.
> 
> Could it be the alterations wordlist is inaccessible at the time of this writing?
> 
> > $ amass enum -passive -d example.com -json ./amassTool_subdomains.json -dir . -w wl.txt
> > Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found

Fixed by using 3.1.6 instead of 3.0.27
