### ISSUE TITLE
could not open amass

### ISSUE THREAD

**Issue by Tikam02** [OWASP/Amass#19]
installation method : $ sudo snap install amass
os : kali linux
![amass](https://user-images.githubusercontent.com/10548085/44004604-84028df4-9e82-11e8-9359-ec261d9c14f7.png)

**Comment by caffix** [comment]
Try installing the snap package without ‘—edge’

Also, update by executing $ sudo snap refresh

**Comment by caffix** [comment]
Is /snap/bin in your PATH?

**Comment by Tikam02** [comment]
@caffix  Thanks :+1:   now it's working.

**Comment by caffix** [comment]
Great!
