### ISSUE TITLE
Amass ASN Table

### ISSUE THREAD

**Issue by jhaddix** [OWASP/Amass#190]
When logging via -oA The Amass table (which is super useful btw) is not in any of the log formats. Can it be added somehow?

**Comment by jhaddix** [comment]
the ASN reference table that is...

```
OWASP Amass v2.9.10                               https://github.com/OWASP/Amass
--------------------------------------------------------------------------------
16 names discovered - dns: 1, cert: 4, api: 7, scrape: 1, archive: 3
--------------------------------------------------------------------------------
```

**Comment by caffix** [comment]
We could make this easier for users to save. In the meantime however, there is a way for you to acquire the table after the enumeration is complete:

1) You performed an enumeration that targeted example.com

2) Type: amass db -list -d example.com

3) Obtain the index number for the enumeration you just performed

4) Type: amass db -enum INDEX -d example.com -show 2>&1 >/dev/null

**Comment by jhaddix** [comment]
i'll use that work around in the meantime =)

**Comment by caffix** [comment]
The db subcommand now has two additional flags for displaying data from previous enumerations. Before, there was only the '-show' flag, but now the '-names' and '-summary' flags allow you to decide the parts of the output to display
