### ISSUE TITLE
What's changed from 2.9.10?

### ISSUE THREAD

**Issue by shadowzoom** [OWASP/Amass#195]
I've upgraded from 2.9.10 to 3.0.9 but old commands not working. What's wrong?
**amass enum -d google.com -passive**
Failed to create the directory: mkdir C:\Users\Admin\amass: The system cannot find the path specified.

**Comment by shadowzoom** [comment]
Figured it out. Was need to add -dir. I have question. What changes and commands was added?

**Comment by caffix** [comment]
The users' guide should be able to answer your question:

https://github.com/OWASP/Amass/blob/master/doc/user_guide.md
