### ISSUE TITLE
building binaries fail on Kali 2019.2

### ISSUE THREAD

**Issue by jaweesh** [OWASP/Amass#196]
When following the *build from source* here https://github.com/OWASP/Amass/blob/master/doc/install.md#from-source 

building fail with message
```
go install ./...
# github.com/OWASP/Amass/amass/sources
amass/sources/radb.go:348:12: undefined: strings.ReplaceAll
```

build machine specs
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.2
Codename:	n/a

uname -r
4.19.0-kali5-amd64

go version
go version go1.11.6 linux/amd64

 echo $GOPATH
/root/go
```

**Comment by dhauenstein** [comment]
ReplaceAll was added to Go 1.12 (see https://github.com/golang/go/commit/ebdc0b8d68e04ad383088c8b3ab963de4a9b5c5d).
As the relasenotes state, Go 1.12 is needed for newer amass versions (or when building from source, like you do) https://github.com/OWASP/Amass/commit/48476c4d90edc628a8ae3a165445d52a5791dbb9

Hope that helps!

**Comment by jaweesh** [comment]
Oh thank you
