### ISSUE TITLE
config.ini permutation

### ISSUE THREAD

**Issue by Techbrunch** [OWASP/Amass#198]
This is the content of my config.ini:

```config.ini
[alterations]
enabled = true
# minimum_for_word_flip specifies the number of times a word must be seen before
# using it for future word flips and word additions
minimum_for_word_flip = 2
# edit_distance specifies the number of times a primitive edit operation will be
# performed on a name sample during fuzzy label searching
edit_distance = 1
flip_words = true   # test-dev.owasp.org -> test-prod.owasp.org
flip_numbers = true # test1.owasp.org -> test2.owasp.org
add_words = true    # test.owasp.org -> test-dev.owasp.org
add_numbers = true  # test.owasp.org -> test1.owasp.org
#wordlist_file = /usr/share/wordlists/all.txt
#wordlist_file = /usr/share/wordlists/all.txt # multiple lists can be used
```

If I don't specify a wordlist, will a default wordlist be used ?

Is there an argument that I can pass that will only add entries to the default list ?

**Comment by fork-while-fork** [comment]
Yes, a default wordlist is used if one isn't specified. The default alteration wordlist is hosted within the repo:
https://github.com/OWASP/Amass/blob/master/wordlists/alterations.txt

If you want to add an additional wordlist to the default, use multiple wordlist lines:

```
[alterations]
wordlist_file=./wordlists/alterations.txt
wordlist_file=./extra.txt
```

The files will be deduplicated when they are loaded.

**Comment by Techbrunch** [comment]
Ok, if its compiled from source is it going to get the worlist from `$GOPATH/src/github.com/OWASP/Amass/wordlists`.

Also, I running Amass with this command:

```
amass enum -config ~/amass/config.ini -src -d domain.com
```

Is there an argument that I can pass to dynamically pass a wordlist to add to the one(s) configured in the config.ini ?

**Comment by caffix** [comment]
Arguments provided on the command-line replace values obtained from the configuration file

**Comment by Techbrunch** [comment]
@caffix Thanks for your answer, it might be nice to be able to pass multiple wordlists then if that's not already the case. It could be comma separated.

**Comment by caffix** [comment]
@Techbrunch Your suggestion to support multiple wordlists from the command-line has now been implemented. Thank you!
