### ISSUE TITLE
Snapcraft version fails to open the text output file in folders with drwxr-xr-x permission

### ISSUE THREAD

**Issue by fuomag9** [OWASP/Amass#204]
I can't manage to open the file I own in `/media/hacking_virtualbox/results/xxx.com/` and I have permission to write to, indipendently if it exists or not. This problem is happening using the latest amass version installed with `snap`
```console
[fuomag9@manjaro-virtualbox hacking_virtualbox]$ cat /media/hacking_virtualbox/results/xxx.com/xxx.com_2.txt
e
[fuomag9@manjaro-virtualbox hacking_virtualbox]$ sudo amass enum -active -brute -d xxx.com -o /media/hacking_virtualbox/results/xxx.com/xxx.com_2.txt
Failed to open the text output file: open /media/hacking_virtualbox/results/xxx.com/xxx.com_2.txt: no such file or directory
```
Meanwhile by calling amass on a new file on my desktop works correctly:
```console
[fuomag9@manjaro-virtualbox xxx.com]$ amass enum -active -brute -d xxx.com -o /home/fuomag9/Scrivania/xxx.txt
```

Permissions on the folder are as follow:
```console
[fuomag9@manjaro-virtualbox xxx.com]$ ls -la /media/hacking_virtualbox/results/
totale 8
drwxr-xr-x 2 fuomag9 fuomag9 4096  1 lug 16.16 .
drwxr-xr-x 2 fuomag9 fuomag9 4096  1 lug 16.16 ..
drwxr-xr-x 2 fuomag9 fuomag9    0  1 lug 15.47 xxx.com
```

By testing the precompiled ded548216c587499295e7e13fbb4f7de5112ad08 release, I've succesfully managed to write to `/media/hacking_virtualbox/results/xxx.com/xxx.com_2.txt`, suggesting that the issue is related to the snapcraft permissions. 

I've tried installing amass with ```snap install amass --classic``` to test wider system access but I got `Warning: flag --classic ignored for strictly confined snap amass` and nothing changed.

**Comment by caffix** [comment]
Yes, Snapcraft definitely imposes some constraints regarding which files can be accessed by the installed program. If the constraints are a problem, then I would just recommend you select an alternative installation mechanism.
