### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by hazcod** [OWASP/Amass#212]
Hi, your current release numbers are not using [semantic versioning](https://semver.org/), which makes it impossible to use with go modules.

Format: `v(major).(minor).(patch)`

If you simply prepend it with a `v`, a `go mod vendor` will work just fine.
I tried this out on my fork: https://github.com/hazcod/amass/releases

**Comment by caffix** [comment]
The Amass version now include the v along with the major, minor and patch numbers.
