### ISSUE TITLE
new 'intel' subcommand doesn't run, doesnt show what was incorrect about users input

### ISSUE THREAD

**Issue by Viss** [OWASP/Amass#215]
> amass intel -d domain.com

That command just shows help. I've tried adding -active and several other permutations, but it seems like I can't really get any intel subcommands to actually run. The syntax is identical to what's in the readme.

**Comment by caffix** [comment]
Adding the ‘-whois’ flag will perform reverse whois on the provided root domain. 

I have considered just removing the ‘-d’ flag and allowing the other flag to accept the argument

**Comment by arthurk** [comment]
I have the same problem, the user guide shows `amass intel -d domain.com` as an example but it just displays the help without any info of what is missing

**Comment by drthankyou** [comment]
Would a stop-gap be to update the user guide with the correct information?

**Comment by caffix** [comment]
@drthankyou Can you share which portion of the user's guide was not accurate? Thank you in advance!

**Comment by drthankyou** [comment]
@caffix My mistake. I originally thought and saw `amass intel -d example.com` in the User Guide but I now see `amass intel -whois -d example.com`. Please ignore my comment :)

**Comment by caffix** [comment]
@drthankyou No problem.

**Comment by caffix** [comment]
I'll soon close this issue now that the user's guide has been updated
