### ISSUE TITLE
only enumerate subdomains that provide public service

### ISSUE THREAD

**Issue by laoshaw** [OWASP/Amass#216]
for certain use cases you do not need the whole map for all sub-domains, instead only sub-domain providing public services are of interest(80,8080,443,4343,mysql, postgresql, etc, but not those thousand of dhcp-whatever.domain.com for example)), is this possible?

**Comment by laoshaw** [comment]
to answer my own question, it seems there is a -p enum flag to do just that, i.e. specify ports of interest, nice.

**Comment by caffix** [comment]
The '-p' flag is not for filtering, but instead identifies ports to check when using active recon techniques

**Comment by laoshaw** [comment]
that turns out to be true.

amass's result is massive but it does not work for my case, I don't need enumerate every single "internal&external" subdomain most of them time, instead I only need the public-interfacing subdomain's IPs, the one that is useful for external visits(mostly just http and https)

I tried utexas.edu with amass and it took forever with 50K names to go etc and it's not very helpful for my case.

**Comment by caffix** [comment]
Amass attempts to find all information about the target that is obtainable from the Internet. There are many ways you can filter that information once it has been collected
