### ISSUE TITLE
I can't understand how wordlists are used

### ISSUE THREAD

**Issue by halfluke** [OWASP/Amass#217]
Hello,

I've tried for a long time to specify different wordlists with the -w option in amass enum, but it looks like amass ignores the wordlist I pass. I can use the small user-agent.txt wordlist or the huge all.txt wordlist, but apparently it always use the same list (not sure which one), as I can see from the progress displayed on screen:
something like
Average DNS queries performed: 418/sec, DNS names remaining: 2139
etc....
That shouldn't be possible when I use a small list with only 75 elements, and it shouldn't be so quickly displayed if I start with a list containing 500K elements.

What am I doing wrong when trying to use a specific wordlist?

Thank you

**Comment by caffix** [comment]
Did you install Amass using Snap? It creates limitations regarding where input files must be located in order to be used

**Comment by halfluke** [comment]
Hmm no, I downloaded the precompiled binary release amass_3.0.18_linux_amd64.zip
and ran it on kali

**Comment by caffix** [comment]
Can you provide an example of your usage? Also, this would probably be easier to troubleshoot using our Discord server

**Comment by halfluke** [comment]
I did it on my work machine however I've just replicated on my home kali.
root@kali:~/Downloads/amass_3.0.18_linux_amd64# ./amass enum -d $domain$ -w wordlists/all.txt -o output.txt

**Comment by caffix** [comment]
The amass enum subcommand will not use the wordlist provided via the '-w' flag when the '-brute' flag is not included as well

**Comment by halfluke** [comment]
ah, thank you, I get it now.
A couple of additional questions if you don't mind:
- what list is used if you do not specify -brute and you don't provide a wordlist?
- I've tried to launch it with -brute and -w tldlist.txt, which contains 1531 entries:
why am I getting this huge number of DNS entries remaining?
Average DNS queries performed: 241/sec, DNS names remaining: 95120
Average DNS queries performed: 134/sec, DNS names remaining: 92980
...........................
Thank you again

**Comment by caffix** [comment]
The following is the default brute forcing word list: [Here](https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/namelist.txt)

tldlist.txt is not meant for brute forcing. I have found 'subdomains-top1mil-20000.txt' to be a good choice

**Comment by halfluke** [comment]
thanks, but my second question is just about the difference between the number of lines in a list and the actual queries performed by amass, in the example above 1531 vs 95120 remaining... How is it possible that form a list of 1531 elements we get almost 100k queries?

**Comment by caffix** [comment]
It is recursive brute forcing. If you use the default settings, then every subdomain name is brute forced using the available wordlist. 

If this is too much, you can require additional labels to be discovered on subdomains before brute forcing will begin. This is achieved using the '-min-for-recursive' flag, which has a default value of zero. Set it to 2 if you would like two names/labels to appear on the subdomain before starting the brute forcing process

**Comment by halfluke** [comment]
again, thanks a lot!
