### ISSUE TITLE
Amass > 2.4.0 no longer working on Windows 10

### ISSUE THREAD

**Issue by emtunc** [OWASP/Amass#22]
Operating system: Windows 10 Enterprise 2016 LTSB - 1607 - 64-bit

Amass 2.4.0 is the last version that works for me - anything above and I get this message:

"This app can't run on your PC - To find a version for your PC, check with the software publisher"

I've tried disabling Windows Defender and Smartscreen to rule those out but still get the same error.

I have only attempted to use the compiled binaries.

**Comment by caffix** [comment]
When built from source on Windows, the tool appears to run without issue. I'll build new binaries for version 2.6.2 over the next few days.

**Comment by emtunc** [comment]
Can now compile and confirmed works on 2.7.6 +
