### ISSUE TITLE
[Feature Request] Support Multiple CLI Wordlist Files, Separation of Wordlist Mask Files

### ISSUE THREAD

**Issue by ngkogkos** [OWASP/Amass#222]
Hello there. Good job on the recent updates! 

I've been thinking, following on https://github.com/OWASP/Amass/pull/221, that it would be nice if Amass supported multiple wordlist files comma separated perhaps, example:

`amass enum ... -w /root/dns_lists/all.txt, subdomain_masks.txt ...`

The reason I am asking for this is that users can have different small customised wordlist files with hashcat-style masks only, this is mainly to keep things organised and clean. For example I don't want to add masks in my `all.txt` list as they will be target specific and generate unnecessary DNS requests.

Another idea is to potentially retrieve masks input from command line:

`amass enum ... -w /root/dns_lists/all.txt -md dev-?l?l?l`

**Comment by caffix** [comment]
Multiple files can now be specified and masks provided on the command-line. 

Brute forcing:
amass enum -brute -wm "www-?l?l?l" -d example.com

For name alterations:
amass enum -awm "www-?l?l?l" -d example.com
