### ISSUE TITLE
Failed to obtain alterations.txt

### ISSUE THREAD

**Issue by d1pakda5** [OWASP/Amass#223]
error: Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 500 Internal Server Error

![Screenshot_130](https://user-images.githubusercontent.com/17035598/61646766-1b6c5800-acc9-11e9-936d-7ba6ee51c2c8.png)

**Comment by fork-while-fork** [comment]
Github had some availability issues yesterday (https://www.githubstatus.com/incidents/8x69vj1xyp9v). Can you try again and let us know if the issue persists?

**Comment by ak1t4** [comment]
same here, but 404 not found 
`

> Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found

> MacBook-Pro-de-akita:amass$ wget https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt

> --2019-09-16 21:15:29--  https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt

> Resolviendo raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...

> Conectando con raw.githubusercontent.com (raw.githubusercontent.com)[151.101.0.133]:443... conectado.

> Petici'on HTTP enviada, esperando respuesta... 404 Not Found

> 2019-09-16 21:15:31 ERROR 404: Not Found.

**Comment by ChillarAnand** [comment]
Looks like alterations.txt is not preset in master branch https://github.com/OWASP/Amass/tree/master/wordlist?

**Comment by AymaneZizi** [comment]
you can find the same wordlist here :
https://github.com/BitTheByte/Monitorizer/blob/master/wordlists/alterations.txt
Best,
