### ISSUE TITLE
UPDATE: panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by CrazyKidJack** [OWASP/Amass#224]
**UPDATE:** I get the same error (with different log info) for pretty much any amass command... not just the one listed

Just installed Amass today, but I keep getting this error when running the following command:
`amass enum -active -brute -o hosts.txt -d yahoo.com`

> panic: runtime error: integer divide by zero
> 
> goroutine 1 [running]:
> github.com/OWASP/Amass/resolvers.(*ResolverPool).NextResolver(0xc000200d40, 0x1)
>         /go/src/github.com/OWASP/Amass/resolvers/pool.go:97 +0x1a6
> github.com/OWASP/Amass/resolvers.(*ResolverPool).Resolve(0xc000200d40, 0x104c509, 0xe, 0x103e638, 0x1, 0x1, 0x4566f0, 0xc00ca6d958, 0xc00ca6d960, 0x8, ...)
>         /go/src/github.com/OWASP/Amass/resolvers/pool.go:211 +0x9b
> github.com/OWASP/Amass/services/sources.(*RADb).OnStart(0xc00015ee00, 0x1085778, 0xc00015ee00)
>         /go/src/github.com/OWASP/Amass/services/sources/radb.go:59 +0x6b
> github.com/OWASP/Amass/services.(*BaseService).Start(0xc00015ee00, 0x0, 0x0)
>         /go/src/github.com/OWASP/Amass/services/service.go:173 +0x17f
> github.com/OWASP/Amass/enum.(*Enumeration).Start(0xc0000ac680, 0x0, 0x0)
>         /go/src/github.com/OWASP/Amass/enum/enum.go:116 +0x266
> main.processEnumOutput(0xc0000ac680, 0xc00021c000, 0xc0001d6058)
>         /go/src/github.com/OWASP/Amass/cmd/amass/enum.go:360 +0x5a7
> main.runEnumCommand(0xc0000300a0, 0x6, 0x6)
>         /go/src/github.com/OWASP/Amass/cmd/amass/enum.go:228 +0x98b
> main.main()
>         /go/src/github.com/OWASP/Amass/cmd/amass/main.go:92 +0x4c8

**Comment by caffix** [comment]
Thank you for the feedback!

We have discovered the bug and are fixing it. If this is happening to you though, it's likely to indicate that your network doesn't allow you to reach the open resolvers used by Amass by default.

You should be able to avoid the problem by assigning the tool a reachable DNS resolver using the '-r' and '-rf' flags.

**Comment by caffix** [comment]
The bug should be fixed now. Thank you for posting the issue!

**Comment by seebog** [comment]
Now I have encountered similar problems. 
docker run -v  OUTPUT_DIR_PATH:/.config/amass/ caffix/amass:v3.2.3 enum -r 8.8.8.8 -brute -w /wordlists/all.txt -d xxx.com
