### ISSUE TITLE
can't install Amass

### ISSUE THREAD

**Issue by Bin-Khattab** [OWASP/Amass#228]
once i reach this step: go install ./...
i get this output:
# github.com/geziyor/geziyor/export
../../geziyor/geziyor/export/csv.go:47:15: val.MapRange undefined (type reflect.Value has no field or method MapRange)

**Comment by caffix** [comment]
Do you have the GO111MODULE environment variable set to "on"?

**Comment by Bin-Khattab** [comment]
yes, i did: export GO111MODULE=on as mentioned.. and i face the same problem

**Comment by Bin-Khattab** [comment]
UPDATE: i checked go env now, i can't fine GO111MODULE even i did that cmd.. how could i solve this?

**Comment by caffix** [comment]
You can download a binary or use a Docker image from the latest release.

**Comment by Bin-Khattab** [comment]
thanks, it works now.
