### ISSUE TITLE
Run time Error 

### ISSUE THREAD

**Issue by d1pakda5** [OWASP/Amass#23]
panic: close of nil channel [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x805503]

goroutine 661556 [running]:
github.com/PuerkitoBio/gocrawl.(*Crawler).Stop.func1(0xc44407c360)
        /home/caffix/go_work/src/github.com/PuerkitoBio/gocrawl/crawler.go:335 +0xc3
panic(0x8b66c0, 0x999c00)
        /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/PuerkitoBio/gocrawl.(*Crawler).Stop(0xc44407c360)
        /home/caffix/go_work/src/github.com/PuerkitoBio/gocrawl/crawler.go:340 +0x55
github.com/caffix/amass/amass/sources.UKGovArchiveQuery.func1(0xc444accb40, 0xc44407c360)
        /home/caffix/go_work/src/github.com/caffix/amass/amass/sources/ukgovarchive.go:49 +0x45
created by github.com/caffix/amass/amass/sources.UKGovArchiveQuery
        /home/caffix/go_work/src/github.com/caffix/amass/amass/sources/ukgovarchive.go:47 +0x35b

**Comment by caffix** [comment]
@d1pakda5 Which version of Amass are you using? The recent versions of Amass no longer use the PuerkitoBio/gocrawl package. Please update the tool.

**Comment by d1pakda5** [comment]
i am using the latest one

**Comment by caffix** [comment]
And with the latest version, have you been able to reproduce this error? Thanks!
