### ISSUE TITLE
Cannot run go get 

### ISSUE THREAD

**Issue by Wraiith1** [OWASP/Amass#230]
I created a small docker container that uses Amass aside with other tools and I am getting this error:

Step 8/10 : RUN go get github.com/OWASP/Amass
 ---> Running in e9f4559ef169
package github.com/OWASP/Amass: no Go files in /root/go/src/github.com/OWASP/Amass                                                         
The command '/bin/sh -c go get github.com/OWASP/Amass' returned a non-zero code: 1 

Or

Step 8/10 : RUN go get github.com/OWASP/Amass/...
 ---> Running in 2ca589dfa06f
github.com/OWASP/Amass/services/sources
/root/go/src/github.com/OWASP/Amass/services/sources/radb.go:352:12: undefined: strings.ReplaceAll
The command '/bin/sh -c go get -u github.com/OWASP/Amass/...' returned a non-zero code: 2

**Comment by caffix** [comment]
Our Docker file is written properly to handle the problem you're having

**Comment by caffix** [comment]
It also appears that you're attempting to compile Amass with a Go version < 1.12, which causes the problem with the undefined function strings.ReplaceAll
