### ISSUE TITLE
No DNS resolvers passed the sanity check

### ISSUE THREAD

**Issue by amiralkizaru** [OWASP/Amass#233]
**Hi**

I'm using kali2 im VM 
and I installed amass via 
```
sudo snap install amass
sudo apt install snapd
sudo systemctl start snapd
sudo systemctl enable snapd
sudo systemctl start apparmor
sudo systemctl enable apparmor
export PATH=$PATH:/snap/bin
sudo snap refresh
```

**Command**
``` amass enum -d google.com```
``` amass enum -active -d google.com```

They both return this error
> No DNS resolvers passed the sanity check

**Comment by caffix** [comment]
You're not able to reach the default DNS resolvers from the network you are current on. Please bring these usage questions to our Discord server, since this is not an issue with the project

**Comment by ayoubfathi** [comment]
Install using precompiled versions https://github.com/OWASP/Amass/releases instead of snap.

**Comment by ayoubfathi** [comment]
@amiralkizaru Install using precompiled versions https://github.com/OWASP/Amass/releases instead of snap.

**Comment by amiralkizaru** [comment]
It was just my VPN works fine now thanks anyways @ayoubfathi
