### ISSUE TITLE
ViewDNS is forbidden since its using http instead of https

### ISSUE THREAD

**Issue by kckadaba** [OWASP/Amass#235]
PFB the log 
ViewDNS: http://viewdns.info/iphistory/?domain=some.com: 403 Forbidden

please observe that viewDNS is being forbidden since its using http, replacing http://viewdns.info/iphistory/?domain=some.com with https://viewdns.info/iphistory/?domain=some.com online shows the results, however when this http://viewdns.info/iphistory/?domain=some.com is used online captcha appears and fails.

amass version v3.0.25

**Comment by fork-while-fork** [comment]
Interesting. Looks like some of their other APIs that we use redirect to HTTPS automatically instead of presenting the captcha. Good catch!
