### ISSUE TITLE
How to force Amass to re-run repeatedly on a domain

### ISSUE THREAD

**Issue by phuongvietvu0306** [OWASP/Amass#239]
I am integrating Amass into my system which will listen and run any domain that I push into it using API. However, I cannot make it to work on a single domain that I push into repeatedly, not until I restart my API. 
I think Amass have some kind of cache or in-mem database that will not re-run the recent added domains.
Would you mind showing me how to do solve this problem of mind. Thank you

**Comment by caffix** [comment]
Please visit our Discord and we can discuss the details of your integration. Thank you!

**Comment by caffix** [comment]
Problem was solved on Discord
