### ISSUE TITLE
DNS sweeping backwards?

### ISSUE THREAD

**Issue by sea-erkin** [OWASP/Amass#24]
This may be a non issue or a misunderstanding on my end. When running amass for my personal domain, erkin.xyz, I see the following coming through in the DNS sweeping. My IP address is 204.48.17.202 and when printing the DNS service requests going through, I see a sweep being performed as follows:

My ip
204.48.17.202

4 sample print lines from line 119 in brute.go
127.17.48.204.in-addr.arpa
142.17.48.204.in-addr.arpa
128.17.48.204.in-addr.arpa
143.17.48.204.in-addr.arpa

It looks like we are sweeping the octets backwards? Is this intended or am I missing something? Wouldn't we want to sweep the /24 of our original cidr? I.e. 204.48.17.202/24

**Comment by caffix** [comment]
Many factors can influence the order of the requests, and more than one sweep can be taking place at once. Also, the sweep takes place on IP addresses with lower and higher host numbers than the IP originally discovered.

If you would like to develop a new algorithm for the reverse DNS sweeping, I would welcome and appreciate your contribution to the project!

**Comment by sea-erkin** [comment]
I think I've phrased my question poorly. Look at line 385 in datamgmtsrv.go

`ptr = utils.ReverseIP(ip.String()) + ".in-addr.arpa"`

// AttemptSweep - Initiates a sweep of a subset of the addresses within the CIDR

Don't you want to perform this sweep on the current CIDR subset, not the reverse?

**Comment by caffix** [comment]
The DNS request for the PTR record associated with IPv4 address 204.48.17.202 uses the following name: 202.17.48.204.in-addr.arpa

Please see the following Wikipedia page for further details: https://en.wikipedia.org/wiki/Reverse_DNS_lookup

**Comment by sea-erkin** [comment]
Thank you for the reply and sorry for the wasted time - my misunderstanding.

**Comment by caffix** [comment]
No worries! Perhaps you would like to contribute to the project, since there are many other things to learn in the process. The link to the Discord server in on the README page, where we can discuss it further. Thanks!
