### ISSUE TITLE
Amass intel -d option not working?

### ISSUE THREAD

**Issue by phspade** [OWASP/Amass#241]
Hi Team,

Whenever I command `~$ amass intel -whois -d example.org` there are no outputs or something.
![2019-08-12_15-59-20](https://user-images.githubusercontent.com/18681023/62851861-210cfa80-bcd7-11e9-949e-0729b27d92b4.png)

**Comment by phspade** [comment]
![2019-08-12_15-59-20](https://user-images.githubusercontent.com/18681023/62851939-616c7880-bcd7-11e9-8e37-fee044c6f522.png)

**Comment by VltraHeaven** [comment]
Hello. It looks like it worked for me. The only difference looks like you are running an older version (3.0.3) of Amass and I'm running on the latest (3.0.27). If you want to get the latest version via the precompiled binary, you can find it on the [Releases Page](https://github.com/OWASP/Amass/releases), or if you'd like to compile it from source you can [make sure your GOPATH is configured correctly](https://github.com/golang/go/wiki/SettingGOPATH) and run this little script.
```sh
#/bin/sh
# Deletes Amass binary and Amass source directory
rm -rf $(which amass) $HOME/go/src/github.com/OWASP/Amass
# Pulls Amass sources from Github
go get github.com/OWASP/Amass
# Changes to the Amass source directory, activates Go Modules and installs binary in $GOPATH/bin
cd $GOPATH/src/github.com/OWASP/Amass && export GO111MODULE=on && go install ./...
```
You can also try building and running the [Docker Image](https://github.com/OWASP/Amass/blob/master/doc/install.md#using-docker), as this will ensure you have a clean build of the latest release of Amass in a stable environment.

**Comment by phspade** [comment]
will do this right now and confirm it within a minute :)

**Comment by phspade** [comment]
I hate errors

![2019-08-12_15-59-20](https://user-images.githubusercontent.com/18681023/62855101-d5f7e500-bce0-11e9-880c-966a4a742d26.png)

**Comment by phspade** [comment]
Case closed.. all is working now :)

**Comment by VltraHeaven** [comment]
Dope. Have a good one!
