### ISSUE TITLE
Quick questoin

### ISSUE THREAD

**Issue by shadowzoom** [OWASP/Amass#243]
Hi there. Did this option is avialable on the amass? "Print https titiles and status page (200,302,404)? This is very helpfull command

**Comment by caffix** [comment]
The results from Amass can be provided to [other tools](https://github.com/michenriksen/aquatone) in order to give you this information

**Comment by shadowzoom** [comment]
@caffix honestly... Aquatone is shit. I would to just enumerate http title and status page like in knockpy and that's all :)

**Comment by ngkogkos** [comment]
I think Amass is currently the best tool for information gathering and subdomain discovery, if we added fingerprinting and other capabilities then it could lead to other issues and things may not be kept clean.

If you want to combine Amass abilities with fingerprinting or other tasks, you can easily automate them with Bash.
