### ISSUE TITLE
Failed to create the graph

### ISSUE THREAD

**Issue by arrahmani** [OWASP/Amass#251]
I am getting this error: "Failed to create the graph" everytime i try to run amass.
I'm using the latest pre-compiled binary ( v3.0.27 )

It was running fine these past couple of weeks, up until yesterday.

**Comment by caffix** [comment]
Try removing the ~/amass/ directory and all its contents. Then try again.

You might have a corrupted graph database on your system

**Comment by arrahmani** [comment]
That fixed it for the Windows Binary.
The Linux Binary isn't displaying the graph error anymore, but i am getting this:

panic: page 9 already freed

goroutine 302 [running]:
github.com/boltdb/bolt.(*freelist).free(0xc0001497a0, 0x5a, 0x7f1ef32f9000)
        /Users/caffix/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/freelist.go:121 +0x2a6
github.com/boltdb/bolt.(*node).spill(0xc000202620, 0xc0135b95a0, 0x1)
        /Users/caffix/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/node.go:363 +0x208
github.com/boltdb/bolt.(*node).spill(0xc0002025b0, 0xc013030870, 0xc006356f30)
        /Users/caffix/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/node.go:350 +0xba
github.com/boltdb/bolt.(*Bucket).spill(0xc012fea100, 0xc006357000, 0x1)
        /Users/caffix/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:570 +0x476
github.com/boltdb/bolt.(*Bucket).spill(0xc006dc88d8, 0x3a4f82df1, 0x1b24100)
        /Users/caffix/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:537 +0x3d8
github.com/boltdb/bolt.(*Tx).Commit(0xc006dc88c0, 0x0, 0xffffffffffffffff)
        /Users/caffix/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:163 +0xf3
github.com/cayleygraph/cayley/graph/kv/bolt.(*Tx).Commit(0xc0135b8260, 0x11f42a0, 0xc0000340b0, 0x11f44e0, 0xc0135b8260)
        /Users/caffix/go/pkg/mod/github.com/cayleygraph/cayley@v0.7.5/graph/kv/bolt/bolt.go:117 +0x62
github.com/cayleygraph/cayley/graph/kv.(*QuadStore).ApplyDeltas(0xc0001b8140, 0xc000124300, 0x4, 0xa, 0x11e0001, 0x0, 0x0)
        /Users/caffix/go/pkg/mod/github.com/cayleygraph/cayley@v0.7.5/graph/kv/indexing.go:493 +0x1072
github.com/cayleygraph/cayley/writer.(*Single).ApplyTransaction(0xc0002d0000, 0xc0135b8220, 0xc0152e9500, 0x11ea820)
        /Users/caffix/go/pkg/mod/github.com/cayleygraph/cayley@v0.7.5/writer/single.go:118 +0x64
github.com/OWASP/Amass/graph.(*Graph).insertDomain(0xc0002d0060, 0xc006dc8540, 0x1043824, 0x6)
        /Users/caffix/go/src/github.com/OWASP/Amass/graph/graph.go:185 +0x635
github.com/OWASP/Amass/graph.(*Graph).Insert(0xc0002d0060, 0xc006dc8540, 0x0, 0x0)
        /Users/caffix/go/src/github.com/OWASP/Amass/graph/graph.go:148 +0x25e
github.com/OWASP/Amass/services.(*DataManagerService).insertDomain(0xc00015f880, 0x7fffce619e17, 0xb)
        /Users/caffix/go/src/github.com/OWASP/Amass/services/datamgmtsrv.go:111 +0x2ad
github.com/OWASP/Amass/services.(*DataManagerService).manageData(0xc00015f880, 0xc00652d320)
        /Users/caffix/go/src/github.com/OWASP/Amass/services/datamgmtsrv.go:73 +0xed
github.com/OWASP/Amass/services.(*DataManagerService).processRequests(0xc00015f880)
        /Users/caffix/go/src/github.com/OWASP/Amass/services/datamgmtsrv.go:60 +0x174
created by github.com/OWASP/Amass/services.(*DataManagerService).OnStart
        /Users/caffix/go/src/github.com/OWASP/Amass/services/datamgmtsrv.go:43 +0xbb
