### ISSUE TITLE
different execution of the precompiled version

### ISSUE THREAD

**Issue by CuriousIncident** [OWASP/Amass#255]
I am using the precompiled version for Debian. If I execute it from a PATH directory with root permissions it runs very slow and only finds a small amount of subdomains in active mode, for example us.google.com,www.google.com for google it were only 4.
If I run it via ./ from shell with the same permission it is multiple times faster with even more results. I'm running Kali Linux. 
I don't know if there is an issue with my distro and a search didn't reveal anything useful. 
Is it because I broke something in my distro or do i not know something?
I don't want to annoy you doing actually great work with amass

**Comment by caffix** [comment]
I am not yet sure what is causing this problem, but we can probably figure it out in the Amass Discord server
