### ISSUE TITLE
Installing from source, errors out on `go get`

### ISSUE THREAD

**Issue by hook-s3c** [OWASP/Amass#26]
```
$ go get -u github.com/OWASP/Amass/...
# github.com/OWASP/Amass/amass/dnssrv
amass/dnssrv/wildcards.go:100:2: undefined: "math/rand".Shuffle
```
```
$ go version
go version go1.9.3 linux/amd64
```

**Comment by caffix** [comment]
Hello, @hook-s3c! Amass requires Go version 1.10 or higher.

**Comment by hook-s3c** [comment]
Ah! My bad - seems like Ubuntu 16.04 only goes up to golang 1.9.3, sad times - I'll go for the Docker build, not a fan of snapd

**Comment by hook-s3c** [comment]
guide for anyone else that's wondering;

https://tecadmin.net/install-go-on-ubuntu/

**Comment by caffix** [comment]
The docker build is currently being updated and the problem discussed in issue #27.
