### ISSUE TITLE
Failed to obtain the wordlist at URL amass repository

### ISSUE THREAD

**Issue by swartepete** [OWASP/Amass#268]
Hi; 
if I try to use enum module, its try to reach a wordlist into this repo. But The word list has been moved to another location, so it got a 404.
it is possible to spec where is locate the wordlist or any workaround ?

![image](https://user-images.githubusercontent.com/55359385/64925562-c92b4d00-d7c8-11e9-950c-bb5a821a4818.png)

**Comment by zokerf** [comment]
I ran into the same thing. One thing I found you can do is to download the [wordlist](https://github.com/OWASP/Amass/blob/master/examples/wordlists/alterations.txt) locally (if it's not already in your Amass installation directory) and use `-aw` to point to it:

`amass enum -aw /path/to/alterations.txt -d somedomain.com`

One thing I thought was odd, though, is that I get this error when running Amass with `enum --passive`. I didn't think alterations.txt was used in passive mode?

**Comment by pajoda** [comment]
I installed it via snap. Problem is that the newest available version on [snap](https://snapcraft.io/amass) is `3.0.27`, too.

I removed my amass installation from snap and downloaded an up to date binary [here](https://github.com/OWASP/Amass/releases). The most recent release is actually `3.1.4`.

**Comment by caffix** [comment]
This has been fixed in v3.1.5
