### ISSUE TITLE
issue with alterations.txt 

### ISSUE THREAD

**Issue by soupnatzi** [OWASP/Amass#269]
i have never had this issue before looking to see if i can fix this issue with some help.

when running root@root: amass enum -passive -d example.com
Failed to obtain the wordlist at https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/alterations.txt: 404 Not Found

**Comment by pablocordova** [comment]
Same error to me at this moment.

**Comment by 0x90n** [comment]
Hitting this issue as well, was there a location or URI change?

**Comment by caffix** [comment]
Please upgrade to Amass v3.1.6
