### ISSUE TITLE
Dockerfile image fails to build

### ISSUE THREAD

**Issue by decidedlygray** [OWASP/Amass#27]
Hello,

I am running Kali, but with docker-ce [installed from the docker.com repos](https://gist.github.com/decidedlygray/1288c0265457e5f2426d4c3b768dfcef). After cloning, when I try to:
```
docker build .
```

After a lot of steps, the build stops with the following error message:
```
... tons of stuff...
golang.org/x/vgo/vendor/cmd/go/internal/fmtcmd
golang.org/x/vgo/vendor/cmd/go/internal/fix
golang.org/x/vgo/vendor/cmd/go/internal/clean
golang.org/x/vgo/vendor/cmd/go/internal/generate
golang.org/x/vgo/vendor/cmd/go/internal/list
golang.org/x/vgo/vendor/cmd/go/internal/bug
golang.org/x/vgo/vendor/cmd/go/internal/modcmd
golang.org/x/vgo/vendor/cmd/go/internal/modget
golang.org/x/vgo/vendor/cmd/go
golang.org/x/vgo
go: creating new go.mod: module github.com/OWASP/Amass
can't load package: package github.com/OWASP/Amass: no Go files in /go/src/github.com/OWASP/Amass
The command '/bin/sh -c apk --no-cache add git   && go get -u -v golang.org/x/vgo   && vgo install' returned a non-zero code: 1
```

Are you able to build the latest version of amass using docker?

**Comment by decidedlygray** [comment]
After looking at this, it is kind of making sense.. There are no go files in `/go/src/github.com/OWASP/Amass`, they are in subdirectories.

**Comment by caffix** [comment]
Please let me know if Amass version 2.6.3 has fixed the problem. Thank you!

**Comment by decidedlygray** [comment]
It works! Thanks!
