### ISSUE TITLE
An option to disable DNS resolution

### ISSUE THREAD

**Issue by nirvana-msu** [OWASP/Amass#272]
Hello,

Is there an option to entirely disable DNS resolution (and by extension, I do not want to do any bruteforcing or name alterations either)? I just want Amass to return all the names it finds across all the configured sources without attempting to resolve them. The reason I want to do this is that I want to perform bulk DNS resolution myself. No matter which option I try setting it still always seems to attempt to do DNS resolution for me.

And a follow up question. Once I do that bulk DNS resolution (in my own way) I still want to check resolved names for certificates. So is there a way to use Amass to only pull domain names from certificates scraped from a manually provided domain list (without actually pulling any data from any other source)? Put differently, I want to disable `passive` mode and only use `active` mode (assuming that's what it means), while specifying a domain list manually (which can probably be done with `-nf` based on its description).

Thanks for you time and this awesome tool!

**Comment by caffix** [comment]
Passive mode does simply pull the results from the data sources. As you indicated, the '-nf' flag allows you to provide previously discovered names, and you can specify the certificate data sources you wish to utilize via the '-include' flag. The data sources do not accept subdomain name though. You must specify the root domain name to be investigated

**Comment by nirvana-msu** [comment]
@caffix thanks for your response! What about the main questions, which were:

1. Is it possible to not perform any DNS resolution whatsoever and just return all domain names?
2. Is it possible to _turn off_  passive mode, i.e. only do _active_ but not passive? It seems to be that you can't disable it?

**Comment by caffix** [comment]
1. Yes. As I said, passive mode achieves this for you.
2. I think you have the meaning of the two modes mixed up. Passive mode is the one that just queries the data sources.

**Comment by nirvana-msu** [comment]
Indeed, it looks like I confused something. Thanks for the clarifications!
