### ISSUE TITLE
ptrarchive.com 404

### ISSUE THREAD

**Issue by raigorx** [OWASP/Amass#273]
amass use search3.hm but that link is give me 404
[http://ptrarchive.com/tools/search3.htm?label=twitter.com&date=ALL](http://ptrarchive.com/tools/search3.htm?label=twitter.com&date=ALL)

it should be search4.htm
[http://ptrarchive.com/tools/search4.htm?label=twitter.com&date=ALL](http://ptrarchive.com/tools/search4.htm?label=twitter.com&date=ALL)

**Comment by caffix** [comment]
Thank you. This is currently being handled in PR#259
