### ISSUE TITLE
The enumeration was unable to build the pool of resolvers

### ISSUE THREAD

**Issue by kcnewb1e** [OWASP/Amass#277]
``kcnewbie@b0x:~/pentesting$ amass enum -d google.com
``
`The enumeration was unable to build the pool of resolvers
`
why am got that error? 
am install amass on snap package.. 

how i can fixit?

**Comment by caffix** [comment]
That error indicates that the DNS resolvers being used are not reachable from your network environment. Please try providing DNS resolvers that you know will be reachable and allow unfiltered use via the '-r' and/or '-rf' flags

**Comment by kcnewb1e** [comment]
i was trying that solution , but i got other error like this:

amass enum -d -rf xxxx.com
`Configuration error: No root domain names were provided`

**Comment by caffix** [comment]
Each DNS resolver is identified as an IP address to the nameserver and the '-d' and/or '-df' flags are still required with argument(s)

**Comment by kcnewb1e** [comment]
what the argument i needed?
in all tutorial they use 
amass enum -d xxxx.com
and its work...?

**Comment by caffix** [comment]
Please read the usage information: amass enum -help

Proper use of the flags you're interested in look like this: amass enum -r 8.8.8.8 -d example.com

**Comment by kcnewb1e** [comment]
still not work
`The enumeration was unable to build the pool of resolvers`

**Comment by caffix** [comment]
Join the Amass Discord server and we can help you troubleshoot this.

You need to try using other DNS resolvers that your network environment will allow. Check what resolver your host OS is using by default and assign that IP address using the '-r' flag

**Comment by fs3c** [comment]
Yeah I got the same problem, everything I tried and it useless..

**Comment by kcnewb1e** [comment]
Yaa me too

**Comment by shabbadont** [comment]
Why closed if not resolved? I have the same problem

**Comment by caffix** [comment]
@shabbadont It isn't a problem with the tool. It means your network is preventing Amass from reaching the various DNS resolvers used by default. You can change your infrastructure, execute the tool from another environment, or specify preferred resolvers using the appropriate flags. See the `-r` and `-rf` flags

**Comment by asolab** [comment]
@caffix I downloaded amass zip file got the same problem too, any solution yet?

**Comment by caffix** [comment]
@asolab Unfortunately, Amass does not know which DNS resolvers you can reach from your network. The user much provide the correct settings or run the tool from a more flexible location

**Comment by asolab** [comment]
@caffix can you please specify the flexible location?

**Comment by caffix** [comment]
Some users execute Amass within a cloud environment

**Comment by asolab** [comment]
I tried installing through snap but keep having issues with "snapd" in Ubuntu on window 10, that''s why I opted for zip file

**Comment by caffix** [comment]
Using Docker is the easiest and most reliable option

**Comment by asolab** [comment]
I will try it now, Thanks Boss

**Comment by caffix** [comment]
No problem. Please bring additional questions to the Amass Discord server

**Comment by asolab** [comment]
invite link

**Comment by caffix** [comment]
It's on the project repo README: [Amass Discord server](https://discord.gg/rtN8GMd)

**Comment by sdsrrt** [comment]
![Screenshot from 2021-08-22 10-41-37](https://user-images.githubusercontent.com/73928464/130346330-fa70880b-0121-4ca6-bca0-d2499bbc17ec.png)
This is show me when i use it.

**Comment by areebtanzeem** [comment]
> 
Use cloudflare warp or some other VPN it'll work with that.

**Comment by KaustubhGiri** [comment]
Just try with sudo command it work for me.
sudo amass enum -d google.com

**Comment by anuragk2406** [comment]
> Please read the usage information: amass enum -help
> 
> Proper use of the flags you're interested in look like this: amass enum -r 8.8.8.8 -d example.com

Thanks it works but its loading the results very slow. Anything we can do to speed it up?

**Comment by aliayaz7** [comment]
kcnewbie@b0x:~/pentesting$ amass enum -d google.com
The enumeration was unable to build the pool of resolvers

I was facing this error I entered some command 
**$cd /
$sudo apt-get install amass**
After these commands 
This command **"amass enum -d google.com"** was working fine for me.

**Comment by iamYEEZUS** [comment]
'amass enum -d google.com'
The enumeration was unable to build the pool of resolvers. 

Had same issues today, I did the following to help me resolve it . i typed the command
 'amass enum -config config.ini'
to get config.ini and got an error , so I created a config.ini file in the **˜/.config/amass** directory 
copied the **examples/config.ini** and pasted it in the file I created. 

I removed the comment for the following and saved the file:

'# DNS resolvers used globally by the amass package.
[resolvers]
resolver = 1.1.1.1 ; Cloudflare
resolver = 8.8.8.8 ; Google
resolver = 64.6.64.6 ; Verisign
resolver = 74.82.42.42 ; Hurricane Electric
resolver = 1.0.0.1 ; Cloudflare Secondary
resolver = 8.8.4.4 ; Google Secondary
resolver = 64.6.65.6 ; Verisign Secondary
resolver = 77.88.8.8 ; Yandex.DNS Secondary'

Then I went back to run the command  'amass enum -d yahoo.com' and it worked 

'$amass enum -d yahoo.com
ns3.yahoo.com
ns5.yahoo.com
be130.member.bf1.yahoo.com
oxy-oxygen-d89bce15.ne1.yahoo.com
oxy-oxygen-628afb15.ne1.yahoo.com
oxy-oxygen-d89bcef1.ne1.yahoo.com
ns13.yahoo.com
oxy-oxygen-628af23b.ne1.yahoo.com
ns22.yahoo.com
et5-1.fab7-2-gdc.ne1.yahoo.com
oxy-oxygen-62895449.ne1.yahoo.com'

**Comment by gofish543** [comment]
This is an issue regarding the `pool.ClientSubnetCheck()` within local.go

Commenting this out has the tool run perfectly. What does this function call do?

**Comment by iamYEEZUS** [comment]
didn't  go  through local.go, it just occurred to me to remove if it would work.  I'm a newbie, anyways you said the tool runs perfectly. amass enum hangs now when I commented out. how is yours running perfectly

**Comment by galactghost** [comment]
Can you tell me where is local.go in kali linux?
