### ISSUE TITLE
Cannot build amass on Windows with go 1.11

### ISSUE THREAD

**Issue by mikemadden42** [OWASP/Amass#28]
I cannot build amass on Windows with go 1.11.  I get the following error.

```bash
>go get -u -ldflags "-s -w" github.com/OWASP/Amass/cmd/amass
# github.com/OWASP/Amass/cmd/amass
go\src\github.com\OWASP\Amass\cmd\amass\main.go:218:23: undefined: syscall.SIGTSTP
go\src\github.com\OWASP\Amass\cmd\amass\main.go:219:24: undefined: syscall.SIGCONT
```

**Comment by caffix** [comment]
Please let me know if Amass version 2.6.3 has fixed the problem. Thank you!

**Comment by mikemadden42** [comment]
I had tried to build Amass from the master branch earlier today.  Should I build from a specific tag?  I'm not seeing a tag for 2.6.3.

```bash
git tag | grep 2.6
v2.6.0
```

**Comment by caffix** [comment]
The following command should build the tool and install it in $GOPATH/bin:

$ go get -u github.com/OWASP/Amass/...

**Comment by mikemadden42** [comment]
The following command works for on Windows.  Feel free to close this issue.

```PowerShell
> go get -u github.com/OWASP/Amass/...
```

**Comment by caffix** [comment]
Thank you for your feedback/contribution to the project!
