### ISSUE TITLE
Error after update amass and go (mac)

### ISSUE THREAD

**Issue by fs3c** [OWASP/Amass#282]
I cant' enumerated subdomain with amass. Everytime I'm running the enum (active or passive) I always got this message `The enumeration was unable to build the pool of resolvers`. 
I try this:

`amass enum -active -d example.com -p 80,443,8080`
And with the option `-rf` still not working.
`amass enum -active -d example.com -p 80,443,8080 -rf ~/path/to/resolvers.txt`

any help please.

**Comment by caffix** [comment]
This "issue" has been addressed in several previously raised project issues. Please look at the answers given for those and consider joining our Discord server for troubleshooting
