### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by bughunterp0** [OWASP/Amass#287]
`# github.com/OWASP/Amass/config
config/support.go:54:19: undefined: os.UserConfigDir
`
When I try install Amass it show me this error

**Comment by caffix** [comment]
You need to build Amass with Go version 1.13

**Comment by bughunterp0** [comment]
package github.com/cayleygraph/cayley/quad: cannot find package "github.com/cayleygraph/cayley/quad" in any of:
	/usr/lib/go-1.13/src/github.com/cayleygraph/cayley/quad (from $GOROOT)
	/home/bughunter/go/src/github.com/cayleygraph/cayley/quad (from $GOPATH)

**Comment by caffix** [comment]
Thank you. This problem has been addressed and discussed in issue #291
