### ISSUE TITLE
Switch to disable colours

### ISSUE THREAD

**Issue by tautology0** [OWASP/Amass#290]
The default colours for amass make the text illegible when the background is light. Can we have a switch to not mess around with text colours for those of us who can't use dark backgrounds?

Example of how bad it is below:
![image](https://user-images.githubusercontent.com/3503697/66843159-4c74c580-ef64-11e9-9861-827e01bfd4ea.png)

**Comment by caffix** [comment]
This feature has been implemented in v3.6.1

**Comment by tautology0** [comment]
Thanks!

**Comment by caffix** [comment]
@tautology0 Thank you for the feature request

**Comment by tautology0** [comment]
Just another one; to stop me fat fingering it later, can we have nocolor allowed both with and without the "u" to cover all flavours of English?

(e.g. --nocolor and --nocolour)
