### ISSUE TITLE
Docker build error - golang is not a valid repo

### ISSUE THREAD

**Issue by HollywoodMarks** [OWASP/Amass#293]
When running the docker build command I get the following output:

Sending build context to Docker daemon 30.35 MB
Step 1/12 : FROM golang:1.13.0-alpine3.10 as build
Error parsing reference: "golang:1.13.0-alpine3.10 as build" is not a valid repository/tag: invalid reference format

**Comment by caffix** [comment]
[Golang Docker Repo](https://hub.docker.com/_/golang)

**Comment by caffix** [comment]
This should be all set now. Thanks again!
