### ISSUE TITLE
How to save Amass enumerated subdomain output to a file?

### ISSUE THREAD

**Issue by rohitcoder** [OWASP/Amass#295]
I tried this command

`amass enum -d domain.com -o out.txt`

I am not sure if `-o` is used for this purpose or not. Can anyone please guide me here? I asked few peoples no one answered properly.

**Comment by ngkogkos** [comment]
Hello,

That is correct the `-o` option is for output. Have a read at https://github.com/OWASP/Amass/blob/master/doc/user_guide.md also.

You could also pipe the output to a file or use the tee command for example. Additionally, look at `-dir` argument for storing the amass database and logs in other folders.

For questions like this, please join us at Discord at https://discord.gg/rtN8GMd.

**Comment by a5h-u** [comment]
its output comes in unreadable format using -o flag
