### ISSUE TITLE
Feature Request: Validating Live Domains

### ISSUE THREAD

**Issue by kerberosmansour** [OWASP/Amass#3]
Some of the feeds might contain stale data, I would like to validate that they domains provided are in-fact alive and well.

**Comment by caffix** [comment]
@kerberosmansour What did you have in mind for validating the domain? Was it to check that the domain registration has not expired? Or was it related to checking if the domain is active and use vs. a parked domain? Thank you in advance for the clarification

**Comment by kerberosmansour** [comment]
Check both the domain registration and the subdomain record. I.e. if I discover vpn.example.com is there still a DNS record for that FQDN? What which IPs does it point to etc..

Additionally if the user wants it would be good to have an additional flag "active validation" flag where they user would ping the FQDN on a few specific ports to check.

**Comment by caffix** [comment]
@kerberosmansour Thank you for the clarification!

@KJ202 Please see the comment above
