### ISSUE TITLE
c-domain__target

### ISSUE THREAD

**Issue by jaikishantulswani** [OWASP/Amass#304]
@caffix getting `c-domain__target--` prefix with every domain, any workaround to get rid of this.

**Comment by caffix** [comment]
I have not seen this yet, so we’ll need additional context. Can you please use the ‘-src’ flag to show which data source is producing the name? Also, can you share the command-line arguments being used? Thank you

**Comment by geeknik** [comment]
Spyse

**Comment by caffix** [comment]
Thank you, @geeknik!

**Comment by fork-while-fork** [comment]
Took a quick look and.... Spyse completely rewrote their site, again. Now they are using IDs in the html that parse as valid domains, so the scraping regex will need to be adjusted.
