### ISSUE TITLE
Amass 3.2.3 "no names were discovered"

### ISSUE THREAD

**Issue by eur0pa** [OWASP/Amass#305]
As the subject states, no results are returned. `-passive` will return hundreds, `-active` will return none—not even the ones returned by `-passive`.

`amass.log` discloses thousands of:

```
19:30:00.385378 DNS: Resolver: svcscm.rampart029.facebook.com type CNAME returned 0 results
19:30:00.385432 DNS: Resolver: rampart021.rampart.facebook.com type CNAME returned 0 results
19:30:00.385453 DNS: Resolver: svcscm.rampart024.facebook.com type CNAME returned 0 results
...
19:30:02.476688 DNS: Resolver: proxygen_verifier.facebook.com type A returned 0 results
19:30:02.476707 DNS: Resolver: rampart033.rampart.facebook.com type A returned 0 results
19:30:02.476726 DNS: Resolver: msgin.vvv.facebook.com type AAAA returned 0 results
1
...
```

The output file is, obviously, empty. Using the precompiled binary available in the release section. Amass v3.1 worked fine.

```
# amass -version
v3.2.3
```

```
# go version
go version go1.13.3 linux/amd64
```

```
# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build406421333=/tmp/go-build -gno-record-gcc-switches"
```

```
~/amass_v3.2.3_linux_amd64
# ./amass enum -active -d facebook.com -o test.txt
Average DNS queries performed: 1639/sec, DNS names queued: 42
Average DNS queries performed: 420/sec, DNS names queued: 0
Starting DNS queries for altered names
Average DNS queries performed: 314/sec, DNS names queued: 1
Average DNS queries performed: 441/sec, DNS names queued: 0
Average DNS queries performed: 1375/sec, DNS names queued: 0
Average DNS queries performed: 83/sec, DNS names queued: 1
No names were discovered
```

**Comment by sumgr0** [comment]
I've been facing the same challenge with both brute and active. Additionally, when I use the -config option, it just kills the command without any output.

Only the below command works for me:

amass enum -passive -d <example.com>

**Comment by Kulme** [comment]
Same to me. The new version does not get any results.

**Comment by eur0pa** [comment]
I'm not sure why this ticket is not being acknowledged by @caffix

**Comment by caffix** [comment]
Is v3.3.1 still giving you this problem?

**Comment by djcater** [comment]
I am seeing this with the latest 3.4.2 using the release binary for Linux x64.

`-passive` will return hundreds of results, but replacing `-passive` with `-ip` will return no (or occasionally very few) results, even though spot-checking some of the subdomains found passively shows that they do resolve to IP addresses (or CNAMEs).

**Comment by djcater** [comment]
Here's a minimal example which demonstrates the above:
```
$ ./amass enum -v -passive -src -noalts -include Pastebin -d twitter.com 
[Pastebin]        mobile.twitter.com
[Pastebin]        pic.twitter.com
[Pastebin]        happening.mobile.twitter.com
Querying Pastebin for twitter.com subdomains
[Pastebin]        about.twitter.com
[Pastebin]        www.twitter.com
[Pastebin]        support.twitter.com
[Pastebin]        careers.twitter.com
[Pastebin]        hoping.twitter.com
[Pastebin]        search.twitter.com
[Pastebin]        blog.twitter.com
[Pastebin]        university.twitter.com
[Pastebin]        developer.twitter.com
[Pastebin]        1pic.twitter.com
[Pastebin]        nwww.twitter.com
[Pastebin]        cards.twitter.com

OWASP Amass v3.4.2                                https://github.com/OWASP/Amass
--------------------------------------------------------------------------------
15 names discovered - api: 15
```
And here's the same command but with `-passive` replaced with `-ip`:
```
$ ./amass enum -v -ip -src -noalts -include Pastebin -d twitter.com 
Querying Pastebin for twitter.com subdomains
No names were discovered
```
Spot checking one of the passive subdomains shows that it does in fact resolve:
```
$ host mobile.twitter.com 
mobile.twitter.com has address 104.244.42.198
mobile.twitter.com has address 104.244.42.6
mobile.twitter.com has address 104.244.42.70
mobile.twitter.com has address 104.244.42.134
```
This is on a home network with no DNS interception or rewriting.

@caffix: Can you re-open this issue based on the above and let me know if there's anything specific I can do to help debug it? Thank you.

**Comment by djcater** [comment]
If I capture the network traffic in Wireshark whilst the Amass command is running I can actually see the valid DNS response coming back from one of the DNS servers, but for some reason Amass is ignoring it:

![image](https://user-images.githubusercontent.com/856675/71313892-7d2b1c80-2437-11ea-8e8a-f4a89c56db64.png)

**Comment by djcater** [comment]
To avoid adding to much noise to a closed issue, I have opened a new one, with output from the latest version of Amass (3.4.2). See #349.
