### ISSUE TITLE
Out of memory (again)

### ISSUE THREAD

**Issue by fopina** [OWASP/Amass#307]
I think this is a follow up from #12 but it's now happening with version 3...
I upgraded amass from version 2.9.13 to 3.2.3 today and when I tried to run in my (very) low-end VPS it simply died almost every time with out of memory.

I then ran it in my Mac and here's the output from `time` (gnu one, for the memory used format option):

2.9.13
```
23.92u 6.37s 63.00r 308168kB ./amass -passive -d vodafone.pt -aw wordlists/alterations.txt
```

3.2.3
```
14.86u 11.99s 192.30r 2156844kB ./amass enum -passive -d vodafone.pt
```

From 300M to 2GB, I'm guessing some refactor in v3 really went wrong... or is there some new flag/feature in v3 that uses more memory and I can just disable it?

**Comment by architectt1** [comment]
Although the issue might need a fix, this made it work for me: https://linuxize.com/post/how-to-add-swap-space-on-ubuntu-18-04/.

**Comment by fopina** [comment]
Yes that can work around the issue, I chose to revert to 2.9.13 :)

**Comment by caffix** [comment]
Try slowing the tool down using the '-max-dns-queries' flag

**Comment by fopina** [comment]
I'm using `-passive` flag @caffix 
And I opened the issue as I believe it as an issue.
Personally I'm ok using the older version 2 :)
60 times more memory doing the same thing does not seem correct

**Comment by caffix** [comment]
@fopina We will definitely be looking into it

**Comment by caffix** [comment]
The memory profiling we have done so far indicates that the string filters are to blame. We will be working on a long-term fix for the problem. Thank you for the useful feedback!

**Comment by fopina** [comment]
Just tested version 3.3.1
` 190746624  maximum resident set size`

versus (in 3.2.3)
`1719726080  maximum resident set size`

So about 10x less, I guess we can consider this one closed, thanks! 👍

**Comment by caffix** [comment]
@fopina Thank you for following up!

Closing the issue now
