### ISSUE TITLE
Output Working Resolvers

### ISSUE THREAD

**Issue by meme-lord** [OWASP/Amass#315]
It would be nice if there was an option to export resolvers that amass has confirmed as working and giving good results to a file or something

**Comment by fork-while-fork** [comment]
There's no official support for this, but a workaround would be grepping the log file for messages like:

```
Resolver 8.8.8.8 has a low score
Resolver 8.8.8.8 has been stopped
SanityChecks: Resolver 8.8.8.8 failed to resolve good names
SanityChecks: Resolver 8.8.8.8 returned false positives for bad names
```

Then just take those and subtract them from your original list.
