### ISSUE TITLE
amass_v3.2.3_macos_amd64 fails to retrive subdomains with sanity checks failure.

### ISSUE THREAD

**Issue by thefishermanhacker** [OWASP/Amass#317]
`$ ./amass -version                                                                     
v3.2.3`

`./amass enum -dir output -v -w examples/wordlists/subdomains.lst -d example.com`

> $ cat amass.log                                                                      
08:28:27.851942 AlienVault: API key data was not provided
08:28:27.851990 BinaryEdge: API key data was not provided
08:28:27.852173 Censys: API key data was not provided
08:28:27.852200 CIRCL: API key data was not provided
08:28:29.006894 DNSDB: API key data was not provided
08:28:29.006953 GitHub: API key data was not provided
08:28:29.007041 NetworksDB: API key data was not provided
08:28:29.007121 PassiveTotal: API key data was not provided
08:28:35.848152 SanityChecks: Resolver 64.6.65.6 failed to resolve good names
08:28:35.848246 SanityChecks: Resolver 77.88.8.1 failed to resolve good names
08:28:35.848181 SanityChecks: Resolver 1.0.0.1 failed to resolve good names
08:28:35.848189 SanityChecks: Resolver 8.8.8.8 failed to resolve good names
08:28:35.848202 SanityChecks: Resolver 9.9.9.10 failed to resolve good names
08:28:35.848264 SanityChecks: Resolver 8.8.4.4 failed to resolve good names
08:28:35.848274 SanityChecks: Resolver 64.6.64.6 failed to resolve good names
08:28:35.848300 SanityChecks: Resolver 1.1.1.1 failed to resolve good names
08:28:35.848343 SanityChecks: Resolver 74.82.42.42 failed to resolve good names

**Comment by fork-while-fork** [comment]
Can you try running the following script to help troubleshoot the DNS issue? 

```
#!/bin/sh

dig @8.8.8.8 www.owasp.org
dig @8.8.8.8 twitter.com
dig @8.8.8.8 github.com
dig @8.8.8.8 www.google.com
dig @8.8.8.8 not-a-real-name.owasp.org
dig @8.8.8.8 wwww.owasp.org
dig @8.8.8.8 www-1.owasp.org
dig @8.8.8.8 www1.owasp.org
dig @8.8.8.8 wwww.google.com
dig @8.8.8.8 www-1.google.com
dig @8.8.8.8 www1.google.com
dig @8.8.8.8 not-a-real-name.google.com
dig @8.8.8.8 www.not-a-real-name.google.com
```

**Comment by thefishermanhacker** [comment]
See attachment.
[results.txt](https://github.com/OWASP/Amass/files/3821164/results.txt)

**Comment by caffix** [comment]
@thefishermanhacker If you're still having DNS issues, please bring the discussion to the Amass Discord server. Thank you!
