### ISSUE TITLE
[amass intel]  giving panic: runtime erro

### ISSUE THREAD

**Issue by IfrahIman** [OWASP/Amass#318]
Hi,

Following is the error: I reinstalled amass but still I cant run amass intel.

amass intel -whois -d example.com

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa61b36]

goroutine 11 [running]:
github.com/OWASP/Amass/resolvers.(*ResolverPool).numUsableResolvers(0x0, 0xc00013aa20)
        /build/amass-QlKQKB/amass-3.1.8/resolvers/pool.go:413 +0x26
github.com/OWASP/Amass/resolvers.(*ResolverPool).Resolve(0x0, 0x104c6b7, 0xe, 0x103e798, 0x1, 0x1, 0x4584f0, 0xc001669e10, 0xc001669e18, 0x8, ...)
        /build/amass-QlKQKB/amass-3.1.8/resolvers/pool.go:226 +0x40
github.com/OWASP/Amass/services/sources.(*RADb).OnStart(0xc000114ee0, 0x14de200, 0xc000114ee0)
        /build/amass-QlKQKB/amass-3.1.8/services/sources/radb.go:60 +0x6b
github.com/OWASP/Amass/services.(*BaseService).Start(0xc000114ee0, 0x0, 0x0)
        /build/amass-QlKQKB/amass-3.1.8/services/service.go:173 +0x17f
github.com/OWASP/Amass/intel.(*Collection).ReverseWhois(0xc000924600, 0x0, 0x0)
        /build/amass-QlKQKB/amass-3.1.8/intel/intel.go:360 +0x1fa
created by main.runIntelCommand
        /build/amass-QlKQKB/amass-3.1.8/cmd/amass/intel.go:216 +0xca9

-Ifrah

**Comment by fork-while-fork** [comment]
Can you reproduce the issue on the latest version of amass (3.3.1)?

**Comment by IfrahIman** [comment]
@fork-while-fork I'm using this one from the kali repo: 

> amass is already the newest version (3.1.8-0kali1).

**Comment by caffix** [comment]
@IfrahIman You definitely should upgrade to v3.3.1 and Kali Linux is in the process of upgrading their Amass package as well
