### ISSUE TITLE
3.2.3 to 3.3.0 upgrade failed

### ISSUE THREAD

**Issue by geeknik** [OWASP/Amass#322]
I thought that I had successfully upgraded from 3.2.3 to 3.3.0 after I ran the following:

$ go get -v -u github.com/OWASP/Amass/v3
```
go: finding github.com/OWASP/Amass/v3 v3.3.0
go: downloading github.com/OWASP/Amass/v3 v3.3.0
go: extracting github.com/OWASP/Amass/v3 v3.3.0
```
But alas, it wasn't meant to be... 

$ amass -version
```
v3.2.3
```
So I wiped out `$GOPATH/src/github.com/OWASP/Amass` and `$GOPATH/bin/amass` and tried `go get github.com/OWASP/Amass/v3` as per the [Installation Guide](https://github.com/OWASP/Amass/blob/master/doc/install.md) and nothing happens. GO111MODULES is exported, etc.

Here is what worked:
`go get -v -u github.com/OWASP/Amass/v3/...`

$ amass -version
```
v3.3.0
```

Might need to update the Install/Upgrade guide.

Using go version go1.13.4 linux/amd64 throughout this all. Thank you for the software.

**Comment by caffix** [comment]
@geeknik Thank you for the excellent feedback!
