### ISSUE TITLE
Multiple APIs  per service in config.ini

### ISSUE THREAD

**Issue by theblackturtle** [OWASP/Amass#330]
Hi,
Can you make the config.ini accept multiple apis per service.
Ex:
```
[Github]
apikey = [apikey1, apikey2, ....]
```
If the apikey1 got limit, change to apikey2 ... apikey-n

**Comment by ngkogkos** [comment]
I was pretty much thinking about the same today. Great idea.

On top of this, a list of socks proxies to rotate would also work well for data sources that block IPs.

**Comment by mzpqnxow** [comment]
@theblackturtle you can resolve,this thanks to a flurry of recent commits. They're in master.

https://github.com/OWASP/Amass/commit/ef132c99e75fd79fd44be5aa0e22dea6570fdf19

**Comment by caffix** [comment]
Thank you for catching this @mzpqnxow. I'm going to close this issue
