### ISSUE TITLE
Default config path. Avoid always having to pass -config

### ISSUE THREAD

**Issue by dotboris** [OWASP/Amass#331]
From what I can see, it seems that if I want to use a config file (to define API keys for various services), I always have to pass the `-config` flag.

This is something's that is very easy to forget. I'd like to be able to configure & use my API keys by default without having to pass in the `-config` flag with every call.

Having a default value for the `-config` flag would be a simple solution to this problem. 

Most of the CLI tools that I've worked with that need some kind of configuration or that need to store things like API keys and the like end up having a configuration file stored in a default / standard location. I think that this could be a great addition to amass.

**Comment by caffix** [comment]
@dotboris I imagine you'll be happy to know the following from the Amass users' guide:

"If you decide to use an Amass configuration file, it will be automatically discovered when put in the output directory and named config.ini."

If this existing feature is giving you trouble, please let us know under this issue. Thank you!

**Comment by caffix** [comment]
@dotboris Can you please close this issue if the existing feature implementation meets your needs. Thanks!

**Comment by dotboris** [comment]
@caffix it worked like a charm. Thank you.

I think that the documentation could be improved so that someone who's looking for this (like I was) can find it easier.

I see two possible improvements:

- Moving / copying the sentence you cited be in the "The Configuration" section of the user guide.
- Writing down the actual path to where amass looks for the configuration file instead of referring to the output directory. I had a hard time finding that the output directory on my MacBook was `~/Library/Application Support/amass/`.

**Comment by caffix** [comment]
Thank you for your contribution!
