### ISSUE TITLE
Error: Process finished with exit code 0

### ISSUE THREAD

**Issue by Babs-Boh** [OWASP/Amass#334]
Hello guys,

the code below gives me Process finished with exit code 0. I understand that it doesn't have any error in it but how do I solve this once and for all?

import pandas as pd

df = pd.read_csv('assignment3.csv')
print (df)

x = df.math
y = df.cs

def grad_descent(x, y):
    mcurr = bcurr = 0
    iterations = 100
    n = len(x)
    learning_rate = 0.04

    for i in range(iterations):
        y_pred = mcurr * x + bcurr
        cost = (1 / n) * sum((y - y_pred) ** 2)
        md = -(2 / n) * sum(x * (y - y_pred))
        bd = -(2 / n) * sum(y - y_pred)
        mcurr = mcurr - learning_rate * md
        bcurr = bcurr - learning_rate * bd
        print("m {}, b {}, cost{}, iteration {}".format(mcurr, bcurr, cost, i))

grad_descent(x,y)

**Comment by caffix** [comment]
@Babs-Boh It appears you have this to the wrong project
