### ISSUE TITLE
 config.ini not taken into account

### ISSUE THREAD

**Issue by Techbrunch** [OWASP/Amass#340]
Looks like I'm running into the same issue again #201.

- I have installed Amass using brew.
- I'm using Amass `v3.4.1`
- I'm running this command `amass enum -config ~/amass/config.ini -ip -src -nf subfinder.txt -d target.com`

My config explicitely enables bruteforcing but no bruteforcing is done:

```
[bruteforce]
enabled = true
recursive = true
# Number of discoveries made in a subdomain before performing recursive brute forcing
# Default is 0
minimum_for_recursive = 0
wordlist_file = /Users/***/Documents/github/SecLists/Discovery/DNS/subdomains-top1mil-110000.txt
#wordlist_file = /usr/share/wordlists/all.txt # multiple lists can be used
```

**Comment by caffix** [comment]
What output indicated that brute forcing did not execute? Thank you for your feedback!

**Comment by Techbrunch** [comment]
I think the problem was probably because of a wildcard DNS. I'm closing it for now and will reopen if I can reproduce it.
