### ISSUE TITLE
wilecard detection

### ISSUE THREAD

**Issue by KristianMKD** [OWASP/Amass#344]
Hi, today I was trying to map ATT subdomains after few hours I noted that anything I put get resolve on 1 IP I was using bruteforce option.

This is not an amass problem but it will nice to detect something like this in future 

here is an example 
1wscbmxws-www.chat.att.com.mx  after -www.chat.att.com.mx whatever you put its resolve to 201.130.47.157 and the scan runs forever.

**Comment by caffix** [comment]
If the existing wildcard detection is being tricked under some conditions, you can use Amass blacklisting to ignore portions of the namespace in order to address the problem
