### ISSUE TITLE
Gremilin Support Removed?

### ISSUE THREAD

**Issue by aguggenberger** [OWASP/Amass#345]
According to the [documentation](https://github.com/OWASP/Amass/blob/master/doc/user_guide.md#the-gremlin-section) a TinkerPop server is supported. However, with the 
[Commit 16a64221886902346257870d295bb418d46bf7da](https://github.com/OWASP/Amass/commit/16a64221886902346257870d295bb418d46bf7da) it appears all Gremlin references have been removed.

Will support be added back? Are there still plans to support an external graph db?

**Comment by caffix** [comment]
@aguggenberger Gremlin support was removed when the new data model was implemented. As we work out the kinks, support for Gremlin and Neo4j will be added back in

**Comment by caffix** [comment]
@aguggenberger Gremlin support is back as of v3.6.0
