### ISSUE TITLE
go get link?

### ISSUE THREAD

**Issue by jepunband** [OWASP/Amass#350]
Hi what is thr exact go get link for amass ? ..  the link provided at the page doesnt seem to work. 
go get -v -u github.com/OWASP/Amass/v3/..

**Comment by caffix** [comment]
Do you have modules enabled as shown in the installation instructions?

**Comment by Maturaf** [comment]
I have the same problem and i have enabled the module

**Comment by jepunband** [comment]
Yes modules installed. I got installed. I think i did this .. try this:

go get -v -u github.com/OWASP/Amass

**Comment by Maturaf** [comment]
Fix after install git
go get -v -u github.com/OWASP/Amass

**Comment by caffix** [comment]
export GO111MODULE=on
go get -v -u github.com/OWASP/Amass/v3/...
$GOPATH/bin/amass -version
