### ISSUE TITLE
failed to resolve good names

### ISSUE THREAD

**Issue by jepunband** [OWASP/Amass#353]
SanityChecks: Resolver 1.1.1.1 failed to resolve good names
SanityChecks: Resolver 64.6.65.6 failed to resolve good names
SanityChecks: Resolver 77.88.8.1 failed to resolve good names
SanityChecks: Resolver 64.6.64.6 failed to resolve good names
SanityChecks: Resolver 1.0.0.1 failed to resolve good names
SanityChecks: Resolver 8.8.4.4 failed to resolve good names
SanityChecks: Resolver 8.8.8.8 failed to resolve good names
SanityChecks: Resolver 74.82.42.42 failed to resolve good names

**Comment by caffix** [comment]
Those messages are usually indicators that the tool is having trouble reaching the DNS resolvers
