### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by saisravanth10** [OWASP/Amass#354]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xab7a3c]

goroutine 532 [running]:
sync.(*RWMutex).RLock(...)
	/usr/lib/go-1.13/src/sync/rwmutex.go:48
github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0x10f87fe, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/build/amass-5YnjMR/amass-3.3.1/graph/db/cayley.go:153 +0x5c
github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc000380100, 0xc00032a030, 0x1, 0x1)
	/build/amass-5YnjMR/amass-3.3.1/graph/event.go:103 +0x4c
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc000450420, 0xc0002042a0)
	/build/amass-5YnjMR/amass-3.3.1/enum/io.go:21 +0xda
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
	/build/amass-5YnjMR/amass-3.3.1/enum/enum.go:192 +0x53e

**Comment by caffix** [comment]
What were the command-line and/or configuration options provided when this occurred?

**Comment by saisravanth10** [comment]
I was trying to identify the subdomains.i used the command:  amass -d <domain>.
Then i received the error mentioned above.
