### ISSUE TITLE
Feature Request: Features for ASN based domain enmuration

### ISSUE THREAD

**Issue by Avileox** [OWASP/Amass#356]
Amass already provide great result for ASN, It will be good if it has some feature like:

**1.List-based ASN enumeration** 
It will be good if we can use it to scan a list of ASN's rather than only single ASN at a time
ex- `amass intel -asn -list asndata.txt`

**2.Timebase Enmuration Per ASN**
`Amass intel -asn` Sometimes it gets stuck when I try to enumerate an ASN with huge IP base

A timeout feature will be really useful while enumeration ASN, 
ex - Only enumerate Single ASN for limited user-supplied time like 
if anyone wants to enumerate a single ASN for 20 minutes 
`amass intel -asn 15169 -timeout 20`

**Comment by caffix** [comment]
@Avileox Thank you for the request. We should be able to implement that in future releases

**Comment by caffix** [comment]
These features have been implemented
