### ISSUE TITLE
is there any way update amass ?

### ISSUE THREAD

**Issue by sandman4812av** [OWASP/Amass#359]
in my kali amass version is 2.8...
so is there any way update amass ? (without reinstall)

**Comment by caffix** [comment]
$ apt update
$ apt upgrade

The version of amass available in Kali will be updated once certain performance improvements have been made to the tool

**Comment by caffix** [comment]
There are other options for installing updated versions of Amass that can be found in the installation guide:

https://github.com/OWASP/Amass/blob/master/doc/install.md
