### ISSUE TITLE
Tracking requires more than one enumeration

### ISSUE THREAD

**Issue by fmtbkgiddiqq** [OWASP/Amass#360]
I am very interested to utilize tracking features, but I am having difficulty. Can any power users or project contributors please point me in the right direction?

Setup:
- OWASP Amass v3.3.1
- amass run periodically via crontab, overwriting amass.txt, amass.json, .etc
- config.ini specifies output folder, i.e. output_directory = /home/username/amass/

Trouble:
When I attempt to invoke track command, such as:
amass track -dir /home/username/amass -df domains.txt

It returns, "Tracking requires more than one enumeration"

Questions:
- What should I be doing to track / retain each amass run from crontab? I have tried rotating .txt and .json file names each run but it does not seem to make any difference.
- Where / what is the "graph database"? Is this a combination of the indexes.bolt and .json?

**Comment by caffix** [comment]
Once you have enumerated a domain at least two times and saved the results into the same output directory, the tracking features should be available for that target domain
