### ISSUE TITLE
Root Domain is not exported in the output (for example json)

### ISSUE THREAD

**Issue by vtasio** [OWASP/Amass#372]
Hello,

the root Domain during Domain enumeration is not exported unless a "data source" report it.
As shown in the below screenshot the example.com is not reported:
![image](https://user-images.githubusercontent.com/61179409/75381707-ea4ca980-58e1-11ea-89ea-2288f5aa58a7.png)

It seems that is added in db:
![image](https://user-images.githubusercontent.com/61179409/75381853-2c75eb00-58e2-11ea-9e0b-bd957fb1e4a1.png)

But it is not exported to json:
![image](https://user-images.githubusercontent.com/61179409/75381898-41527e80-58e2-11ea-8128-fcf2ed458b9e.png)

**Comment by caffix** [comment]
Thank you, @vtasio! We should be able to fix that easily in the next release

**Comment by vtasio** [comment]
Np , i would also like to add this not always the case. Some time, it is neither reported nor added db even if it live.
