### ISSUE TITLE
 YAMI -Yet Another Memory Issue :)

### ISSUE THREAD

**Issue by chppppp** [OWASP/Amass#376]
Amass v3.4.4

`amass enum -d blabla.com,blabla.net -o blabla.amass -json blabla.amass.json -brute -w ./jhaddix_dns.all.txt`

The wordlist is 26MB (jhaddix all.txt). My machine has `4GB` of RAM and `8GB` of Swap. 100% of scans run out of memory and result in `Killed`. 

I'll break my scan up into 2 for the 2 domains but with a total of 12GB of memory I am a little surprised i'm getting nuked. 

Any suggestions on getting this to successfully run? Thank you so much.

**Comment by caffix** [comment]
I'll have to run some tests with such large wordlists and investigate the problem

**Comment by ghost-pep** [comment]
I have had the same issue. I am using it without a wordlist: `amass enum -d <domain> -json output.json`. I used to use an input file with a list of domains (`-df`), which crashed as well. My current theory is that there is a memory leak associated with some kind of JSON serialization, but I am not familiar with the codebase enough to debug further.

**Comment by chppppp** [comment]
+1 to @ghost-pep . I stopped outputting to JSON and I have less memory related issues.
