### ISSUE TITLE
intel -whois not working on Windows server in AWS EC2

### ISSUE THREAD

**Issue by dan-processbolt** [OWASP/Amass#379]
Any idea why this would not work on an AWS EC2 Windows Server 2019 instance?
> amass intel -whois -d xxxxxxx.yyy

Instance has its own public IP, no proxies/firewalls that I can see.

"amass enum" commands work as expected.

Linux instances in same VPC work as expected.

Thanks

**Comment by dan-processbolt** [comment]
update - on a domain that I know has 1,000+ related domains, I am getting a partial result, like 20, but nowhere near the expected number, so it is partially working.

**Comment by dan-processbolt** [comment]
update 2 - looks like it just the ViewDNS source that is not working.

**Comment by dan-processbolt** [comment]
update 3 - ViewDNS returning 403 (e.g. https://viewdns.info/reversewhois/?q=xxxxx.yyy).

Why just the Windows Server boxes??

**Comment by caffix** [comment]
Perhaps ViewDNS is able to tell that you're in the cloud and would like you using an account with API access

**Comment by dan-processbolt** [comment]
That's what I was thinking, but if that were the case, I would think the Linux boxes would behave the same way.
