### ISSUE TITLE
Amass Docker Image 3.5.0 contains wrong amass version

### ISSUE THREAD

**Issue by J12934** [OWASP/Amass#380]
Okay this feels like a weird bug report, but the docker image tagged as `caffix/amass:v3.5` seems to contain amass version `v3.4.2`, or at least lists it as its version.

```bash
➜ docker pull caffix/amass:v3.5.0
v3.5.0: Pulling from caffix/amass
Digest: sha256:8e85792c26ab070c918ec0eacd57346c1a2c20839b9696aada30f7620cea4e51
Status: Image is up to date for caffix/amass:v3.5.0
docker.io/caffix/amass:v3.5.0

➜ docker run caffix/amass:v3.5.0 -version
v3.4.2
```

`caffix/amass:v3.4.4` interestingly lists its version correctly.

**Comment by caffix** [comment]
Thank you for the heads up. I'll be releasing v3.5.1 with some fixes shortly

**Comment by J12934** [comment]
Version shows correctly in 3.5.1.
Thanks you 👍
