### ISSUE TITLE
API Keys not read from config.ini

### ISSUE THREAD

**Issue by JoshuaMart** [OWASP/Amass#381]
Hi,
First of all thank you for this great tool, however, it seems that the latest version(s) are impacted by the same bug as issue #192 

I installed Amass by fetching the binary since the release, I'm on Debian 9.

My config file :
```
...
#[SecurityTrails]
apikey = WjXXXXXX3pS9XXXXXTjIUfXXXXXhXXX
...
```

I run Amass with this command :
```
amass enum -config config/amass.ini -d domain.tld
```

Output :
```
Querying ThreatCrowd for ... subdomains
Querying VirusTotal for ... subdomains
Querying ViewDNS for ... subdomains
Querying URLScan for ... subdomains
Querying Yahoo for ... subdomains
Querying Spyse for ... subdomains
Querying Sublist3rAPI for ... subdomains
Querying Robtex for ... subdomains
Querying SiteDossier for ... subdomains
Querying Riddler for ... subdomains
Querying Crtsh for ... subdomains
Querying Google for ... subdomains
Querying Pastebin for ... subdomains
Querying Dogpile for ... subdomains
Querying GoogleCT for ... subdomains
Querying Netcraft for ... subdomains
xxx.domains.tld
...
```

I've also tried with the absolute path to the conf file without change, my API key is not used.

Regards,
Jomar

**Comment by caffix** [comment]
I was not able to reproduce your issue. I used the following command and it resulted in excellent results from SecurityTrails:

`amass enum -src -ip -config amass_config.ini -include securitytrails,radb -d DOMAIN`

**Comment by JoshuaMart** [comment]
Hi,
From Debian 9 with Amass 3.5.1 (wget the las binary) :
![amass1](https://user-images.githubusercontent.com/17493961/76995724-8ea99500-6950-11ea-8438-4f401a351fc5.png)

From Debian 10, Amass installed with snap (3.5.1 too) :
![amass2](https://user-images.githubusercontent.com/17493961/76995990-02e43880-6951-11ea-8b96-1eb87a40173c.png)

Regards,
Jomar

**Comment by caffix** [comment]
You need the `radb` data source included in order to obtain ASN/netblock infrastructure information

**Comment by caffix** [comment]
The new snap package worked for me as well. The only difference being that I'm not using Debian

**Comment by JoshuaMart** [comment]
Unfortunately it's the same.

On Debian 9 :
![amass2](https://user-images.githubusercontent.com/17493961/76998152-dd592e00-6954-11ea-8f02-6baa6990237b.png)

On Debian 10 :
![amass1](https://user-images.githubusercontent.com/17493961/76997959-8eab9400-6954-11ea-8b7a-36b9b5af62e3.png)

Which distribution do you use? (I could test it later)

Regards,
Jomar

**Comment by caffix** [comment]
I am using Ubuntu for development

**Comment by JoshuaMart** [comment]
Ok, I just made a fresh install of Unbuntu 18.04.
The only commands I've made are the following :
```
apt-get update && apt-get upgrade -y
snap install amass
https://raw.githubusercontent.com/OWASP/Amass/master/examples/config.ini
```

Then I modified the configuration file to add my securitytrails key.
```
#[SecurityTrails]
apikey = tXXXXX3EXXXXXPFXXXXXwjXXXXXrcXXX
```

And it's the same :/

![amass](https://user-images.githubusercontent.com/17493961/77000195-45f5da00-6958-11ea-8642-81cec045b953.png)

**Comment by caffix** [comment]
The SecurityTrails section of your configuration is commented out

**Comment by JoshuaMart** [comment]
Works much better ... unless I'm mistaken I haven't seen any indication that the source should be uncommented as well ([SecurityTrails])

Thank you very much for the help and quick answers!

**Comment by caffix** [comment]
We appreciate the feedback. Thank you!
