### ISSUE TITLE
runaway memory conditions

### ISSUE THREAD

**Issue by Viss** [OWASP/Amass#382]
If you give amass a rather large wordlist (we have a custom one at phobos thats ~30 megs we developed) and you give it any more than 5 domains (the last case I gave it 10), amass will gobble up all the ram on the system and be killed by the kernel.

So I wager there should probably be some condition in the code that examines how much memory the system has and throttles stuff internally to not go ape-o and get killed by the system...

![image](https://user-images.githubusercontent.com/1756255/77131066-87998a00-6a17-11ea-95ca-896fa35e2fe9.png)

my system is a 12 core ubuntu box with 32 gigs of ram, and giving amass 10 domains or more (I initially tried with like 40) caused it to run out of memory and be killed, and I kept chopping the number of domains down til it stopped crashing. Right now I'm running 5, and its teetering at 27 gigs consumed, so its just barely below the limit.

**Comment by caffix** [comment]
@Viss The memory usage should rarely go above 1GB with v3.5.3 and beyond. Please let me know if the problem has been resolved for you

**Comment by Viss** [comment]
well, i tried the same command I did before, gave it 31 domains - the memory went up to 40 gigs or so, but then went back down to 33 or so for the rest of the run. 

i was able to do that purely because I upgraded the ram in my workstation, so it seems that it's using something like a gig per domain - in your testing did you aim amass at multiple domains, or just one?

**Comment by caffix** [comment]
Using the version that was just released minutes ago?
