### ISSUE TITLE
CIDR command not working Properly

### ISSUE THREAD

**Issue by attacker34** [OWASP/Amass#385]
Hi While i was looking for the ASN and CIDR commands. I noticed that CIDR command is not returning anything and completed within two or three seconds:

```
amass intel -cidr myCIDR

```

Can you please tell me what it should return in response. All It should do is to at least respond with Resolved IP's within that CIDR. 

Sincerely,

**Comment by caffix** [comment]
The command is working for me, but you'll always get more results if you turn on the active recon features using the `-active` flag. 

The `intel` subcommand only attempts to perform horizontal domain name correlation and will not return all the subdomain names discovered via reverse DNS queries

**Comment by attacker34** [comment]
Hi @caffix 

I tried to use -active flag but it gives me error:

```
Configuration error: No root domain names were provided

```

**Comment by caffix** [comment]
`amass intel -active -cidr $CIDR`

**Comment by caffix** [comment]
We can answer these questions for you easier in the Amass Discord server

**Comment by attacker34** [comment]
Hi @caffix  sorry for the mistake... Yes.. 

```
amass intel -active -cidr $CIDR 

```

is not working too... :(
