### ISSUE TITLE
amass doesn't find any domains on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [OWASP/Amass#39]
```amass -d reddit.com``` doesn't find anything, and the same for other domains I tried.
Revision ```2.7.0-8-g5ac544c```.

**Comment by caffix** [comment]
Do you have any leads from output or log file entries?

**Comment by yurivict** [comment]
It doesn't output anything and doesn't leave logs. ```amass -h``` doesn't produce help screen.

**Comment by yurivict** [comment]
It's built by the FreeBSD port https://svnweb.freebsd.org/ports/head/dns/amass/

**Comment by caffix** [comment]
Can you use dtrace to see what is happening?

**Comment by caffix** [comment]
Are you still having trouble with the latest version?

**Comment by yurivict** [comment]
It doesn't currently build: https://github.com/OWASP/Amass/issues/41

**Comment by yurivict** [comment]
```amass -d reddit.com``` works now, but ```amass -d doctorlan.com``` doesn't.

Revision: b4aba4f
