### ISSUE TITLE
Parsing issue in Yahoo data source - incorrect results.

### ISSUE THREAD

**Issue by lappsec** [OWASP/Amass#390]
Hi, 

I have an issue with the Yahoo plugin adding an incorrect prefix to discovered domain names. It looks like when it's parsing the results it sometimes incorrectly picks up a preceding special character (like "/" or ":"), URL encodes it, drops the %, and adds it to the beginning of the domain name in the results.
The discovered domain names are valid, minus the prefix. I've attached a screenshot. 

I tried this on two different Ubuntu systems (16.04.6 LTS, and 18.04.3 LTS), running version 3.5.4 installed via Snap.
![amass_issue](https://user-images.githubusercontent.com/22598243/79140701-3ad27600-7d6d-11ea-980d-a08db0ee3eff.jpg)

**Comment by caffix** [comment]
Thank you for the feedback. The fix for this is already in the `develop` branch and will be included in the next release. I'll try to push the release out soon

**Comment by leechristensen** [comment]
Is this fixed for the DNSTable source as well?

Test case:
`amass enum -passive -src -include dnstable -d deviantart.com`
Sorted output:
```
[DNSTable]        22ayej.deviantart.com
[DNSTable]        22caffeinejitsu.deviantart.com
[DNSTable]        22danfrandes.deviantart.com
[DNSTable]        22ferenartwork.deviantart.com
[DNSTable]        22gaomonpentablet.deviantart.com
[DNSTable]        22historicbridges.deviantart.com
[DNSTable]        22huggybear742.deviantart.com
[DNSTable]        22keylessentry.deviantart.com
[DNSTable]        22kukuruyoart.deviantart.com
[DNSTable]        22mail-p1.mg.deviantart.com
[DNSTable]        22mail-p4.mg.deviantart.com
[DNSTable]        22mail.deviantart.com
[DNSTable]        22niveus-diabolus.deviantart.com
[DNSTable]        22off-white-comic.deviantart.com
[DNSTable]        22office6.lax.deviantart.com
[DNSTable]        22officialartfight.deviantart.com
[DNSTable]        22ostadreza.deviantart.com
[DNSTable]        22star--bits.deviantart.com
[DNSTable]        22tonyr.deviantart.com
[DNSTable]        22www.deviantart.com
[DNSTable]        22www.ingret.deviantart.com
[DNSTable]        ayej.deviantart.com
[DNSTable]        caffeinejitsu.deviantart.com
[DNSTable]        danfrandes.deviantart.com
[DNSTable]        ferenartwork.deviantart.com
[DNSTable]        forum.deviantart.com
<snip>
```

**Comment by caffix** [comment]
@leechristensen Yes. The upcoming release has this problem fixed as well
