### ISSUE TITLE
The PTRArchive API should be removed 

### ISSUE THREAD

**Issue by binb4sh** [OWASP/Amass#391]
The PTRArchive API should be removed  cause it returns so many baseless results. 
<img width="1657" alt="Screen Shot 2020-04-14 at 18 31 46" src="https://user-images.githubusercontent.com/13507431/79215515-406bb100-7e7e-11ea-9130-20aa7d7ed8d7.png">
<img width="1663" alt="Screen Shot 2020-04-14 at 18 31 54" src="https://user-images.githubusercontent.com/13507431/79215520-42357480-7e7e-11ea-9905-f72df805c64d.png">

**Comment by caffix** [comment]
Definitely a possibility. We rarely get useful results from that data source

**Comment by rscott0** [comment]
I forget that people sometimes don't like to read. In those screenshots, it says "**WARNING**" (in bold red), "Automated usage is forbidden". OWASP has helped cause a denial of service attack. The ptrarchive.com site sometimes gets 100s of hits per second, *all* for the most resource intensive tool at the site (which warns that it "may take a minute!" to run). That's 1,000s of times higher than the designed usage.

So a few years back, I had the choice of [1] paying a lot of money for more/faster servers, [2] shutting the site down, [3] allowing the attacks and leaving it unusable for human visitors, or [4] being creative. I chose #4. Typically that involved returning low-resource invalid data to automated programs (adding an 0x00, a message in a domain name, random answers, etc.) and a message in case human readers saw it. That mitigated the attack, while not interfering with legitimate users. Not perfect, but it got the job done. But the blackhats kept at it, working around whatever I did.

Needless to say, after many years, I think I have fixed this with a hashing "proof of work" challenge. Just find a SHA256 hash of the lookup and a nonce, that meets the criteria (I.E. starting with 0's). Very easy to code, but it puts a small burden on the client end. and if unauthorized use gets out of hand, I can make the challenge harder.

So now you can decide whether to incorporate this, or leave the site alone. :)

**Comment by caffix** [comment]
@rscott0 I apologize for the inconvenience. Support for your service as an Amass data source is being removed right now. The change will show up in the next release
