### ISSUE TITLE
it looks like BufferOver and ThreatCrowd source was blocked by cloudflare protection

### ISSUE THREAD

**Issue by nancheal** [OWASP/Amass#392]
amass.log shows
BufferOver: https://dns.bufferover.run/dns?q=.vip.com: 503 Service Temporarily Unavailable
ThreatCrowd: https://www.threatcrowd.org/searchApi/v2/domain/report/?domain=vip.com: 503 Service Temporarily Unavailable
this is blokced by cloudflare right？is there any way to bypass it? thanks

**Comment by caffix** [comment]
Those log messages alone do not tell us if it was blocked due to Cloudflare. On another note, the bufferover.run service is working well for me. Perhaps you'll need to request the service from another IP address. If you have additional questions about this, please join the project Discord server
