### ISSUE TITLE
OOM the return

### ISSUE THREAD

**Issue by Nicknam3** [OWASP/Amass#393]
Hi all,

I've an issue with the last version of amass (amass_v3.5.5_linux_amd64.zip).

If the amass will start with -w option and wordlist have a big amount of word it leads to out of memory. It seems the same as https://github.com/OWASP/Amass/issues/325.

```
Apr 22 00:00:24 nmap kernel: [916282.952694] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-0.slice/session-294.scope,task=amass,pid=30082,uid=0
Apr 22 00:00:24 nmap kernel: [916282.952761] Out of memory: Killed process 30082 (amass) total-vm:1834748kB, anon-rss:787176kB, file-rss:0kB, shmem-rss:0kB
Apr 22 00:00:24 nmap kernel: [916283.126207] oom_reaper: reaped process 30082 (amass), now anon-rss:32kB, file-rss:0kB, shmem-rss:0kB
```
I just have 1G of memory on my VPS, so...

Thanks for your help ^^

**Comment by caffix** [comment]
The issue is likely more related to the 1G VPS than the wordlists provided. The next release should help with this given the additional reduction in memory consumption

**Comment by Nicknam3** [comment]
Hi @caffix,

I confirm that switching to a VPS with 2GB of RAM solved the problem.

Curious to see if the next release will allow to use amass on low performance computer ^^.

Thanks !

**Comment by caffix** [comment]
Thank you for your feedback
