### ISSUE TITLE
Failed to load config

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [OWASP/Amass#394]
hi,

I install via snap

 amass enum -config /home/ubuntu/config.ini

Failed to load the configuration file: Failed to load the configuration file: open /home/ubuntu/config.ini: permission denied

Any ideas how to resolve?

**Comment by caffix** [comment]
Snap is likely to give you these issues, but you can try putting the config file in the directory `~/.config/amass/` to avoid the problem. In the future, please bring these usage / support questions to our Discord server. Thank you
