### ISSUE TITLE
Silent option

### ISSUE THREAD

**Issue by aaaguirrep** [OWASP/Amass#397]
Hi, is there a silent option to don't show information when the amass command is running? I have checked the help menu and I didnt find an option.

Regards,
Arsenio

**Comment by caffix** [comment]
This feature has not been implemented at this point in time and sounds like a good request

**Comment by leebaird** [comment]
I second this request. Please add a new switch for silent mode (-s).

**Comment by caffix** [comment]
The feature will be available in the next release. The switch is `--silent`

**Comment by leebaird** [comment]
This is still not working in v3.6.0.

**Comment by caffix** [comment]
@leebaird It was not included in v3.6.0. It will be included in the upcoming release v3.6.1
