### ISSUE TITLE
JSON output is not a valid json

### ISSUE THREAD

**Issue by omerlh** [OWASP/Amass#398]
When running `amass enum -d <> -json out.json`, the output is not a valid JSON - it contains a list of object, but not in an array format

**Comment by caffix** [comment]
Back when we supported the array format, users did not like that either. Do you have a reference for which option meets a standard that will make it valid JSON? I am comfortable with either option

**Comment by crdx** [comment]
I believe this format is known as "JSON Lines" as it allows for streaming the output: http://jsonlines.org/

> This page describes the JSON Lines text format, also called newline-delimited JSON. JSON Lines is a convenient format for storing structured data that may be processed one record at a time. It works well with unix-style text processing tools and shell pipelines. It's a great format for log files. It's also a flexible format for passing messages between cooperating processes.

Perhaps the option `-json` should output regular JSON and `-jsonl` should output JSON lines? This is not a backwards-compatible change though.

**Comment by C-Sto** [comment]
As results are streamed to the file rather than buffered and written all at once, having an array-like output would result in broken output if the program is terminated early or interrupted, and other programs using the output file will need to wait until the run has fully completed before consuming the output file.

I think leaving it as-is is a sane way of doing it, as otherwise you'd need to buffer all of the results in-memory, and for *extremely large* datasets that doesn't make sense.

**Comment by r0oth3x49** [comment]
@caffix for me with latest release amass not saving the output to json file.

just downloaded from releases.

platfrom: ubuntu

```
***@***:~/path/to/executable$ ./amass -version
v3.6.3

***@***:~/path/to/executable$ ./amass enum -d impactechs.com -passive -timeout 1 -json out.json
Querying ViewDNS for impactechs.com subdomains
... strip ...
impactechs.com
telecoms.impactechs.com
cdn.impactechs.com
otsint.impactechs.com
... strip ..
```

it prints out on terminal but no json file is generated

**Comment by caffix** [comment]
@r0oth3x49 There's no JSON output when Amass is run in passive mode

**Comment by r0oth3x49** [comment]
> 
> 
> @r0oth3x49 There's no JSON output when Amass is run in passive mode

Thanks for the fast reply. and really appreciate your work on this tool.
It was producing json file on **Amass v3.5.4** with passive flag and now it is not :(.
take a look at below screenshot.

command used.  `amass enum -passive -d impactechs.com -json test.json`.
![Capture](https://user-images.githubusercontent.com/11024397/83486974-9e526780-a4c3-11ea-9a4a-9f57e4600fab.PNG)

**Comment by caffix** [comment]
@r0oth3x49 It has been explicitly removed given that the same information is easily obtained via the text file output. The JSON output is meant for the normal and active mode, where the output is more complicated. That said, I suppose the JSON output could be activated when the user provides the flag

**Comment by GouveaHeitor** [comment]
It would be good to document this change in the user manual ... I've been trying to use the -json option together with -passive for a long time...

**Comment by m-raheem** [comment]
> @r0oth3x49 It has been explicitly removed given that the same information is easily obtained via the text file output. The JSON output is meant for the normal and active mode, where the output is more complicated. That said, I suppose the JSON output could be activated when the user provides the flag

`amass enum -d example.com -brute -min-for-recursive 3 -active -r 8.8.8.8,1.1.1.1 -w /usr/share/seclists/Discovery/DNS/dns-Jhaddix.txt -max-dns-queries 100 -p 80,443 -nocolor -json ~/Desktop/targets/expediacruises/amass-subdomain.json -if ~/.config/amass/datastore.yaml 
flag provided but not defined: -json
`

**Comment by Sbrjt** [comment]
the json flag is gone :(
