### ISSUE TITLE
owasp_needs_upgrade_failed_to_send_a_nonce

### ISSUE THREAD

**Issue by anantupadhya** [OWASP/Amass#399]
Hello,
        While doing subdomain enumeration, Amass throws an error "owasp_needs_upgrade_failed_to_send_a_nonce" for few subdomains, Any idea why is it happening? Its a recent issue I am facing. I did not have this issue a week back

**Comment by caffix** [comment]
OWASP Amass does not include such an error message. Please bring this troubleshooting to the Discord server and we can investigate it

**Comment by dsamuel323** [comment]
Facing the same issue here, started happening a few days ago

**Comment by geeknik** [comment]
I saw this before @caffix removed the PTRArchive stuff. Haven't seen it since.

**Comment by caffix** [comment]
Perhaps the error message is from an API being used?

**Comment by crdx** [comment]
If run with `-src` it shows it came from PTRArchive. I can confirm it no longer appears since the removal of PTRArchive in 3.6.0.

**Comment by caffix** [comment]
Thank you @crdx and @geeknik. Issue closed
