### ISSUE TITLE
Question about consistency of results...

### ISSUE THREAD

**Issue by mkonda** [OWASP/Amass#40]
Great work.  Enjoyed the presentation in the project showcase yesterday.

I ran 
`amass -d jemurai.com`
 and a more detailed command 
`amass -v -ip -brute -min-for-recursive 3 -d jemurai.com`
and I got fewer results with the second command than the first.  That surprised me.  I didn't see anything in the second command that would suggest that it wouldn't check all of the same things and just add info about IP's, and do brute forcing.

I wonder if there is something in the tool that is different along these paths, or if it was something environmental.  (Same laptop, 5 minutes apart)  If environmental, I wonder if there is a way to know that the results are partial or if we just need to run it a few different times to ensure that we get full results.

```
om:go mk$ amass -d jemurai.com
www.jemurai.com
jemurai.com
jasp.jemurai.com
training.jemurai.com
feedback.jemurai.com
ctfd.jemurai.com
om:go mk$ amass -v -ip -brute -min-for-recursive 3 -d jemurai.com
[Brute Force]     feedback.jemurai.com,34.206.253.53
[CertSpotter]     ctfd.jemurai.com,52.22.145.207
[Forward DNS]     jemurai.com,34.195.173.235
[Brute Force]     training.jemurai.com,54.194.35.114

OWASP Amass v2.7.10                               https://github.com/OWASP/Amass
--------------------------------------------------------------------------------
4 names discovered - brute: 2, cert: 1, dns: 1
--------------------------------------------------------------------------------
ASN: 14618 - AMAZON-AES - Amazon.com, Inc., US
	34.192.0.0/12     	2    Subdomain Name(s)
	52.20.0.0/14      	1    Subdomain Name(s)
ASN: 16509 - AMAZON-02 - Amazon.com, Inc., US
	54.194.0.0/16     	1    Subdomain Name(s)
```

**Comment by caffix** [comment]
Great! I'm glad to hear that you enjoyed the talk at AppSec USA.

Please try version 2.7.11 and see if it addressed the problems you were experiencing. Thank you for the useful feedback.

**Comment by caffix** [comment]
A handful of improvements have been made on this front. 

Further concerns regarding consistency will be made in issue #47
