### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gy741** [OWASP/Amass#400]
Hey, I'm getting this error at Ubuntu 18.04 with released amd64 binary. 

Could anyone please help?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x956e1c]

goroutine 167 [running]:
github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0xf57b73, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/caffix/go/src/github.com/OWASP/Amass/graph/db/cayley.go:170 +0x5c
github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc0001573e0, 0xc00000e0c0, 0x1, 0x1)
        /Users/caffix/go/src/github.com/OWASP/Amass/graph/event.go:122 +0x6e
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc0000da000)
        /Users/caffix/go/src/github.com/OWASP/Amass/enum/io.go:20 +0xa9
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
        /Users/caffix/go/src/github.com/OWASP/Amass/enum/enum.go:197 +0x78c
root@ubuntu-s-1vcpu-1gb-sfo2-05:~/amass_v3.5.5_linux_amd64# ./amass enum -noalts -d example.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x956e1c]

goroutine 167 [running]:
github.com/OWASP/Amass/v3/graph/db.(*CayleyGraph).AllNodesOfType(0x0, 0xf57b73, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/caffix/go/src/github.com/OWASP/Amass/graph/db/cayley.go:170 +0x5c
github.com/OWASP/Amass/v3/graph.(*Graph).EventList(0xc0001d4ae0, 0xc00000e7c8, 0x1, 0x1)
        /Users/caffix/go/src/github.com/OWASP/Amass/graph/event.go:122 +0x6e
github.com/OWASP/Amass/v3/enum.(*Enumeration).submitKnownNames(0xc0000da000)
        /Users/caffix/go/src/github.com/OWASP/Amass/enum/io.go:20 +0xa9
created by github.com/OWASP/Amass/v3/enum.(*Enumeration).Start
        /Users/caffix/go/src/github.com/OWASP/Amass/enum/enum.go:197 +0x78c

```

Also, Intel module works for me.

reference issues
#369 #276

**Comment by gy741** [comment]
command : amass enum -d uber.com

**Comment by gy741** [comment]
snap install amass => good.
donwload releases version => error.

**Comment by caffix** [comment]
@gy741 Are you still having this problem since the recent release of version 3.6.0?

**Comment by rocketscientist911** [comment]
I have installed with snap & still same issue.

```
digitalocean_droplet.vps[0] (remote-exec): panic: runtime error: invalid memory address or nil pointer dereference
digitalocean_droplet.vps[0] (remote-exec): [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xdb40f6]

digitalocean_droplet.vps[0] (remote-exec): goroutine 1472017 [running]:
digitalocean_droplet.vps[0] (remote-exec): github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).tcpExchange(0xc000616480, 0x23846c, 0xc061f97c70)
digitalocean_droplet.vps[0] (remote-exec):      /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:517 +0x56
digitalocean_droplet.vps[0] (remote-exec): created by github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).processMessage
digitalocean_droplet.vps[0] (remote-exec):      /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:482 +0x519
```

**Comment by 7heRealBig** [comment]
Snap install same issue. 

'panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xdb40f6]

goroutine 204214 [running]:
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).tcpExchange(0xc000253f80, 0x467774, 0xc0247d8280)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:517 +0x56
created by github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).processMessage
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:482 +0x519'

**Comment by baotang2118** [comment]
Face the same issue while installing via snap. My version is v3.11.11.

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xdc63de]

goroutine 5310 [running]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0x18e7498, 0xc014d5a370, 0xc01aa35a30, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2012 +0x11e
panic(0xf3cce0, 0x1fdf7c0)
	/snap/go/7221/src/runtime/panic.go:965 +0x1b9
github.com/yuin/gopher-lua.callGFunction(0xc014d5a370, 0x0, 0xc015047740)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:262 +0x1f7
github.com/yuin/gopher-lua.init.3.func26(0xc014d5a370, 0xc07c180403, 0xc01a99e000, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:817 +0x39d
github.com/yuin/gopher-lua.mainLoopWithContext(0xc014d5a370, 0xc01a99e000)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:60 +0x126
github.com/yuin/gopher-lua.(*LState).callR(0xc014d5a370, 0x2, 0x0, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1203 +0x256
github.com/yuin/gopher-lua.(*LState).Call(...)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1959
github.com/yuin/gopher-lua.(*LState).PCall(0xc014d5a370, 0x2, 0x0, 0x0, 0x19e6660, 0xc00760d480)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2022 +0x114
github.com/yuin/gopher-lua.(*LState).CallByParam(0xc014d5a370, 0x19faab8, 0xc015047e40, 0x0, 0x1, 0x0, 0xc006d0eae8, 0x2, 0x2, 0x40caff, ...)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2040 +0xe9
github.com/OWASP/Amass/v3/datasrcs/scripting.(*Script).dnsRequest(0xc014c2f040, 0x19f8d38, 0xc01b5a4060, 0xc00df8a180)
	/root/parts/amass/build/datasrcs/scripting/script.go:320 +0x31d
github.com/OWASP/Amass/v3/datasrcs/scripting.(*Script).OnRequest(0xc014c2f040, 0x19f8d38, 0xc01b5a4060, 0xf57360, 0xc00df8a180)
	/root/parts/amass/build/datasrcs/scripting/script.go:270 +0x24d
reflect.Value.call(0xf07680, 0xc00dcc3f98, 0x13, 0x1080bbe, 0x4, 0xc00dcdf860, 0x2, 0x2, 0x2, 0xc005accea0, ...)
	/snap/go/7221/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xf07680, 0xc00dcc3f98, 0x13, 0xc00dcdf860, 0x2, 0x2, 0xffffffffffffffff, 0xecd800, 0xc00df7bbc0)
	/snap/go/7221/src/reflect/value.go:337 +0xb9
github.com/caffix/service.(*BaseService).processRequests.func1(0xecd920, 0xc00dcdf890)
	/root/go/pkg/mod/github.com/caffix/service@v0.0.0-20210321183606-3819810293b0/base.go:164 +0x169
github.com/caffix/queue.(*queue).Process(0xc014fa9980, 0xc01b22a640)
	/root/go/pkg/mod/github.com/caffix/queue@v0.0.0-20210301212750-6e488abe1004/queue.go:170 +0x52
github.com/caffix/service.(*BaseService).processRequests(0xc014c2f040)
	/root/go/pkg/mod/github.com/caffix/service@v0.0.0-20210321183606-3819810293b0/base.go:173 +0x86
created by github.com/caffix/service.(*BaseService).Start
	/root/go/pkg/mod/github.com/caffix/service@v0.0.0-20210321183606-3819810293b0/base.go:50 +0x12c

**Comment by caffix** [comment]
@baotang2118 The lastest version is v3.11.12

**Comment by baotang2118** [comment]
@caffix Thank you, because snap show that I installed the latest version but when run `amass -version` , it is not. I upgrade Go and can install from source now.

**Comment by qusaialhaddad** [comment]
go get github.com/michenriksen/Amass/...
cd ~/go/src/github.com/michenriksen/Amass
go build -o amass cmd/amass/*
