### ISSUE TITLE
Installation with Go

### ISSUE THREAD

**Issue by x1n5h3n** [OWASP/Amass#401]
## OS
Debian GNU/Linux bullseye/sid x86_64

## Version
Go: go version go1.13.8 linux/amd64
Amass : master

## Error

```bash
go get -v -u github.com/OWASP/Amass/...

[...]

# github.com/OWASP/Amass/graphdb
../.go/projects/src/github.com/OWASP/Amass/graphdb/gremlin.go:471:38: cannot convert vertex1.ID() (type interface {}) to type int: need type assertion
../.go/projects/src/github.com/OWASP/Amass/graphdb/gremlin.go:472:45: cannot convert vertex2.ID() (type interface {}) to type int: need type assertion
```

**Comment by geeknik** [comment]
I had that problem. Re-running without `-u` seemed to have fixed it in my end.

**Comment by x1n5h3n** [comment]
Regarding th use of `-u`, I don't know why it will solve the issue:

`The -u flag instructs get to use the network to update the named packages
and their dependencies. By default, get uses the network to check out
missing packages but does not use it to look for updates to existing packages.`

I still got the same erro beside:
```bash
go get -v github.com/OWASP/Amass/...

github.com/OWASP/Amass/graphdb
# github.com/OWASP/Amass/graphdb
../.go/projects/src/github.com/OWASP/Amass/graphdb/gremlin.go:471:38: cannot convert vertex1.ID() (type interface {}) to type int: need type assertion
../.go/projects/src/github.com/OWASP/Amass/graphdb/gremlin.go:472:45: cannot convert vertex2.ID() (type interface {}) to type int: need type assertion
```

**Comment by caffix** [comment]
@x1n5h3n Do you have the GO111MODULE environment variable turned on?

**Comment by x1n5h3n** [comment]
Yep, it's strange, I run the same command just now without any issue.
(`go get -v -u github.com/OWASP/Amass/...`)

**Comment by JesseClarkND** [comment]
I still get this error with go 1.14.4 running any of these

`go get -v -u github.com/OWASP/Amass/...`
`go get -v github.com/OWASP/Amass/...`
`go get -u github.com/OWASP/Amass/...`
`go get github.com/OWASP/Amass/...`

**Comment by geeknik** [comment]
I just ran `go get -v github.com/OWASP/Amass/v3/...` with `go version go1.14.4 linux/amd64` on Ubuntu 20.04 LTS without error.
