### ISSUE TITLE
[Feature request] need all of the ASN data

### ISSUE THREAD

**Issue by leebaird** [OWASP/Amass#403]
OWASP Amass v3.5.4                                https://github.com/OWASP/Amass
--------------------------------------------------------------------------------
766 names discovered - cert: 276, api: 59, scrape: 3, dns: 428
--------------------------------------------------------------------------------
ASN: 0 - Reserved Network Address Blocks

< need all of the ASN data to be recorded when using the -o  outfile.txt

**Comment by caffix** [comment]
v3.6.0 has been released.

Also, you can extract the summary information from the local graph database as follows:
`amass db -summary -d example.com`

**Comment by leebaird** [comment]
That command is exactly what I needed! I really appreciated the quick response.

I just started using your tool last night and have already integrated it to my project Discover:
https://github.com/leebaird/discover

**Comment by caffix** [comment]
@leebaird Happy to help and be part of your project!

**Comment by leebaird** [comment]
This prints exactly what I wanted to the screen great.
amass db -summary -d target.com

This does NOT work:
amass db -summary -d target.com -o tmp
flag provided but not defined: -o

**Comment by leebaird** [comment]
Sorry, I'm using v3.5.4 in Kali. 
I just submitted a ticket to have them pull the latest v3.6.

**Comment by caffix** [comment]
Everything should be as you suggested in the next release
