### ISSUE TITLE
cannot find module providing package github.com/OWASP/Amass/v3

### ISSUE THREAD

**Issue by kohldampfer** [OWASP/Amass#404]
I have a `centos:latest` container and I want to clone `Amass` and build it there. So these are the steps I am doing here:

- `git clone https://github.com/OWASP/Amass`
- `export GO111MODULE=on`
- `cd Amass`
- `go build`

This message I get at the end after go build

```
go: finding github.com/OWASP/Amass v2.6.0+incompatible
go: downloading github.com/OWASP/Amass v2.6.0+incompatible
go: extracting github.com/OWASP/Amass v2.6.0+incompatible
can't load package: package github.com/OWASP/Amass/v3: unknown import path "github.com/OWASP/Amass/v3": cannot find module providing package github.com/OWASP/Amass/v3
```

`go version` is

```
go version go1.12.12 linux/amd64
```

Is there anything I can do to get rid of this last error message ?

**Comment by caffix** [comment]
Amass requires Go version >= 1.14 in order to build properly.

Perhaps it would be easier for you to download the prebuilt executable?
