### ISSUE TITLE
Error on install graphdb package

### ISSUE THREAD

**Issue by bughuntercat** [OWASP/Amass#405]
Trying to install Amass with "go get -v -u" command as always I get an error on gremlin.go package

# github.com/OWASP/Amass/v3/graphdb
go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.6.1/graphdb/gremlin.go:471:38: cannot convert vertex1.ID() (type interface {}) to type int: need type assertion
go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.6.1/graphdb/gremlin.go:472:45: cannot convert vertex2.ID() (type interface {}) to type int: need type assertion

**Comment by caffix** [comment]
The following commands should properly update:
```bash
export GO111MODULE=on
go get -v -u github.com/OWASP/Amass/v3
```

**Comment by bughuntercat** [comment]
That is what always use, but not worked. Now works fine. Thanks.
