### ISSUE TITLE
-passive switch does not write output instantly to file while undergoing scan.

### ISSUE THREAD

**Issue by humurabbi** [OWASP/Amass#407]
Hi , there is the bug in amass which does not write output to file instantly when `-passive` switch is specified. :  
  
**Amass Version**:  `v3.6.1`  

**Command Used** :   

`amass enum -passive -norecursive -noalts -df domains.txt -o output_subdomains.txt`

Removing `-passive` switch from above command did not produce the following issue.   
  
  #### Consequences 
 1. Results in breaking of scripts.
 2. For large input list it results in memory exhaustion leading to shutdown of machine.

Hence I request you to fix this issue or include a switch which writes output instantly as done in previous versions.

**Comment by Jennfier** [comment]
This issue is present in amass since v3.6.0 (but not in v3.5.5).
It also decreases speed of amass as compared to its previous versions.
