### ISSUE TITLE
[Feature request] Add support to https://chaos.projectdiscovery.io API

### ISSUE THREAD

**Issue by riramar** [OWASP/Amass#414]
The project https://chaos.projectdiscovery.io is returning really good data and this integration should be really easy since Amass has already a bunch of other similar integrations.

**Comment by caffix** [comment]
Excellent recommendation! It will be available this week

**Comment by riramar** [comment]
Thanks! :)

**Comment by caffix** [comment]
Now available in v3.7.0

**Comment by onuncukoy-dot** [comment]
> https://chaos.projectdiscovery.io projesi gerçekten iyi veriler döndürüyor ve Amass'ın zaten bir sürü benzer entegrasyona sahip olması nedeniyle bu entegrasyon gerçekten kolay olmalı.

answer amass scripting engine   asstfinder.ads ..many pasiple NahamCon2021 https://www.youtube.com/watch?v=yCZqgg-GNx8  video time 12.30 chaos.ads
