### ISSUE TITLE
JSON output can't be parsed with Python

### ISSUE THREAD

**Issue by waawaa** [OWASP/Amass#415]

**Comment by waawaa** [comment]
In order to parse JSON output with python it's necessary to add "," character in each line produced by tool and later add "[" and "]" in the first and last line of the file.

It would be interesting to add a new argument to produce a valid JSON to python output, for example -output-json-format Python / regular.

**Comment by Kn0wl3dge** [comment]
I'm not sure if it's what you're looking for. But this format is called jsonlines. You can parse it with python using jsonlines library.

```
from jsonlines import jsonlines

with jsonlines.open(json_file) as reader:
    for line in reader:
        print(line)
```

**Comment by caffix** [comment]
#398 has already covered this issue
