### ISSUE TITLE
Getting some go routines debug info in output.

### ISSUE THREAD

**Issue by Jennfier** [OWASP/Amass#419]
Hi, I am facing an issue with amass latest version.
When I scanned domains using amass I am getting lot of go routines debug info.  

**Amass Version:** `v3.7.1`
  
**Command Used:**
`amass enum -passive -norecursive -noalts -df domains.txt -o output_subdomains.txt`
[It was having no such issue when last run with amass v3.6.1].  
  
It also breaks the scan and not scanning all domains provided to it.

![Screenshot from 2020-06-13 16-09-27](https://user-images.githubusercontent.com/58885348/84566654-954d7a00-ad90-11ea-8c12-835d57c982c6.png)

**Comment by caffix** [comment]
How many domains did you have in the text file?
