### ISSUE TITLE
Domain ENUMeration / VIZualisation generates unconnected islands

### ISSUE THREAD

**Issue by GitGitNS** [OWASP/Amass#423]
Tested with Amass 3.7.2.

Amass generates dangling AS/Subnet/IP islands, with no reference to the scanned domain. Could be a single AS/Subnet/IP, multiple subnets from the same AS or multiple IPs form the same subnet. 

Commands used:
amass enum -config /home/amass/config.ini -d domain.com
amass viz -config /home/amass/config.ini -gexf -d domain.com

![issue-examples](https://user-images.githubusercontent.com/16868806/84941208-5184a880-b0e1-11ea-8dc7-91ce8c0d2c9a.png)

[amass-config.zip](https://github.com/OWASP/Amass/files/4794682/amass-config.zip)

**Comment by caffix** [comment]
This issue has been solved for some time now
