### ISSUE TITLE
passive switch does not write output instantly to file while undergoing scan.

### ISSUE THREAD

**Issue by mzpqnxow** [OWASP/Amass#428]
I'm opening this is in lieu of reopening #407 which was resolved but only partially

The issue with amass having a longer run time seems to have been addressed but the initial issue (passive mode doesn't create a file when starting up) is still present

Is this now the intended behavior, or is it a bug? It did not behave this way in earlier versions (at least 3.5.5, but I believe there are newer versions listed in #407)

Clarification is appreciated, thx

**Comment by caffix** [comment]
How long of a delay are you experiencing?

**Comment by mzpqnxow** [comment]
I'm closing this out for now- the issue is that passive mode explicitly disables both JSON output and graphdb output. This is by design

We can revisit this in the future and if appropriate I can send a PR from the branch I use now to cause the JSON and graphdb/cache file to be written regardless of passive/active mode if it makes sense

To be continued ...
