### ISSUE TITLE
[Feature Request] Timing templates

### ISSUE THREAD

**Issue by dokkillo** [OWASP/Amass#43]
Amass is a very fast scanner, but when I use -brute flag it DOS my Wifi, and I lost all internet of my home. I think it could be a nice feature to create some timing flag (like nmap) to control the speed of Amass.

**Comment by caffix** [comment]
How is the current implementation of the feature working for you?

**Comment by dokkillo** [comment]
Yes, now I can use at home without any problem!

**Comment by caffix** [comment]
Great!
