### ISSUE TITLE
dot graphs are in the helptext but not implemented

### ISSUE THREAD

**Issue by krysopath** [OWASP/Amass#432]
I just downloaded `amass v.3.7.3` and noticed this flag in the usage text:

```
Usage: amass viz -d3|-dot||-gexf|-graphistry|-maltego [options]
```

but executing it:

```
 $ amass viz -dot -enum 1 -o . -d domain.tld
flag provided but not defined: -dot
```

I like dot graphs alot, since they can be used in so many different CLI tools.

- Is there support for dot coming in or phasing out?

**Comment by krysopath** [comment]
ah easy fix, mhm..

**Comment by caffix** [comment]
Yes. Great to have it back!
