### ISSUE TITLE
Passing resolver file in config.ini

### ISSUE THREAD

**Issue by ta1bbty** [OWASP/Amass#433]
Hi team,

First of all thanks for the wonderful tool that you've **created** and are _maintaining_.
I saw the recent talk by @caffix in Nahamcon [How to Use Amass Efficiently by @jeff_foley](https://www.youtube.com/watch?v=H1wdBgY1rtg), it was quite an informative one.

So, I am trying to pass the resolvers file as a config.ini option but there doesn't seem to be an option around that. The only thing that one could do is manually adding those resolvers, which is cumbersome in my case ( I've 50 resolvers ).

I tried finding it myself and looking through the code but that didn't help much.

Thanks.

**Comment by caffix** [comment]
There's no option in the configuration file for identifying a text file with DNS resolver IP addresses on each line, but you can provide the path to such a file using the `-rf` flag on the command-line
