### ISSUE TITLE
Can you control the CPU memory usage to affect the sending rate? When CPU or memory usage is 100%, it will die

### ISSUE THREAD

**Issue by icezhaoL** [OWASP/Amass#435]
Can you control the CPU memory usage to affect the sending rate? When CPU or memory usage is 100%, it will die

**Comment by caffix** [comment]
I wish it was that simple. How much memory are you making available to the process?

**Comment by icezhaoL** [comment]
10g

**Comment by caffix** [comment]
I added some memory consumption monitoring that should help

**Comment by icezhaoL** [comment]
thanks
