### ISSUE TITLE
Permission denied for output

### ISSUE THREAD

**Issue by apertureless** [OWASP/Amass#437]
**Server**: Ubuntu 20.04
**amass version**: v3.7.4
**Installation method**: snap

---

Installed amass on my ubuntu 20.04 server over snap `sudo snap install amass`

However, I can not ouput the results to a folder. 

```bash
Bespin12:vfl:% amass enum -brute -min-for-recursive 3 -active -o ~/.mora/projects/folder/subdomains -df domain.txt
Failed to open the text output file: open /home/op/.mora/projects/folder/subdomains: permission denied
```

**Sidenote**:

The `~/.mora/projects/folder/` will be created over a small wrapper bash script. 
The folder permissions should be good tho.

```bash
Bespin12:vfl:% ls -la ~/.mora/projects
total 12
drwxrwxr-x 3 op op    4096 Jul 15 13:45 .
drwxrwxr-x 6 op users 4096 Jul 15 12:53 ..
drwxrwxr-x 2 op op    4096 Jul 15 13:45 folder
```

**Comment by apertureless** [comment]
Uff, seems to be related to snap. 

If I install it over `go get -v github.com/OWASP/Amass/v3/...` it works.
Not sure tho, which permissions I need to set in order to fix the snap version.

Because even tho I set it to 777, it still fails xD

**Comment by geeknik** [comment]
run `snap connections amass` or `snap interfaces amass` and verify it's permission include `home`. I believe. 
Best follow up with https://snapcraft.io/tutorials/advanced-snap-usage#3-handling-interfaces-and-permissions-in-your-snaps
Good luck!
