### ISSUE TITLE
Improper elimination of output

### ISSUE THREAD

**Issue by adik69** [OWASP/Amass#439]
I have configured all the keys for my config.ini file.
But when I run 
**amass enum -config config.ini -d youla.ru**
 
It gives vague output. I believe this is because github search API.
ajax/libs/yui/3.11.0pr1/dom-style-ie/dom-style-ie.js.youla.ru
ajax/libs/yui/3.5.0pr2/pluginhost-config/pluginhost-config.js.youla.ru
ajax/libs/yui/3.0.0b1/dd/dd-min.js.youla.ru
ajax/libs/angular-i18n/1.3.0-beta.14/angular-locale_si-lk.js.youla.ru
ajax/libs/jquery.mmenu/4.4.1/js/jquery.mmenu.oncanvas.min.js.youla.ru
ajax/libs/angular-i18n/1.4.0-beta.1/angular-locale_tl.min.js.youla.ru
ajax/libs/angular-i18n/1.3.0-rc.2/angular-locale_sk-sk.js.youla.ru

Amass is showing this in the output. Need to eliminate the lines with '/'

**Comment by caffix** [comment]
@adik69 Was this enumeration performed using Amass v3.8.1?

**Comment by adik69** [comment]
Yes. I'm using exactly that version.
Could you please try the same exact command in order to reproduce.

Thank You

**Comment by adik69** [comment]
Were you able to reproduce??
