### ISSUE TITLE
Amass gets stuck on run

### ISSUE THREAD

**Issue by mikedesu** [OWASP/Amass#440]
```
# this command gets stuck
$ amass enum -v -config ./mike.ini -d somedomain.net -o somedomain.net.txt

# contents of ini file
mode = passive
maximum_dns_queries = 10000
[network_settings]
port = 443
[Shodan]
apikey = myapikey

# additional system info
$ amass --version
v3.8.0
$ which amass
/snap/bin/amass
$ uname -a
Linux mybox0 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Additionally, I could not Ctrl-C / `SIGINT` out of the program, and had to send `SIGTERM` via `htop`.  This kind of thing happens a lot. I like the idea of using my config file but so far has not been successful and I have not yet dug deep into what is going on here, but since I'm using it and am having trouble, thought I'd bring this here.

**Comment by caffix** [comment]
This was addressed this morning in issue #438. You should not experience the problem with v3.8.1

**Comment by caffix** [comment]
@mikedesu I would recommend that you not use Snap for installation, if you want the best experience, since it creates some interesting constraints on Amass

**Comment by mikedesu** [comment]
Noted! Thanks Jeff.

Need a computer science tutor? https://mikebell.xyz
