### ISSUE TITLE
Clarity on the ttl / API cache functionality

### ISSUE THREAD

**Issue by mzpqnxow** [OWASP/Amass#443]
I see on [this](https://twitter.com/owaspamass/status/1285778371897630720) Tweet about the 3.8.0 release that there is API/caching support now. Are there any docs on this? I haven't been able to find anything aside from the example config file which has `ttl` values set to various (seemingly arbitrary) values for various API sources

Will there be any docs added to this, or is the source the canonical guide?

... or maybe I am just not good at searching- but I did try, the only thing I found was #410 which mentions this as a feature request

Any clarification is appreciated

**Comment by caffix** [comment]
The values are the number of minutes for the cached responses to be used before allowing a new request to be sent to the data source

**Comment by mzpqnxow** [comment]
@caffix thanks.. two more questions:

1. Is this cache volatile, in memory? Or valid across multiple runs?
2. Is it actually stored to disk anywhere?

For my use-case, having a cache that survives across multiple runs would be infinitely more valuable than a volatile/per-run cache

**Comment by mzpqnxow** [comment]
I think I answered my own question(s) here by looking at the indexes.bolt file. I think more documentation would be helpful for those that don't realize they'll be losing the caching if they use the working directory parameter (unless they make sure the indexes.bolt file is copied to the working directory each time a new working directory is used)

If you're interest I can make a PR to the docs with some short info on this. I'll mark this as closed. Thanks again

**Comment by caffix** [comment]
You answered your questions correctly. Also, we welcome and look forward to your assistance with the documentation
