### ISSUE TITLE
Some really strange errors when I run amass enum -active and amass enum -brute

### ISSUE THREAD

**Issue by anantupadhya** [OWASP/Amass#449]
I am encountering some strange errors when I run amass in enum -active mode and -brute mode in my VPS. I have attached a screenshot of the errors. Even stranger is that amass runs perfectly fine in my local machine. This error occurs only when I run it in my VPS. In VPS, amass works fine when I am using amass in enum -passive mode. Any idea what might be causing it? Is it my VPS issue? I am using a Digital Ocean 1 GB vps. 
![Screenshot_2020-08-03_17-57-22](https://user-images.githubusercontent.com/64357415/89187392-dad13b00-d5ba-11ea-9268-77fd64e1246c.png)

**Comment by caffix** [comment]
Often times, 1GB is not enough memory for Amass when mapping the attack surface of your target

**Comment by anantupadhya** [comment]
Oh thanks a lot for the reply. So its my vps that is the problem. Guess I need to upgrade it then.

**Comment by caffix** [comment]
Please feel free to join our Discord server and others could have advice on how they manage the necessary infrastructure

**Comment by anantupadhya** [comment]
Sure I will. Thank you
