### ISSUE TITLE
Feature Request: Supporting data gathering post subdomain processing.

### ISSUE THREAD

**Issue by JeffreyShran** [OWASP/Amass#456]
I would like to formalise a [discussion ](https://discordapp.com/channels/433729817918308352/433729817918308354/742296765377675314 ) in the discord server which began on the 10th August into a feature request.

The idea stems from the idea that most users will process their subdomains with Amass and then go on to run tools like:

- https://github.com/projectdiscovery/naabu
- https://nmap.org/
- https://github.com/robertdavidgraham/masscan
- https://github.com/jaeles-project/gospider
- https://github.com/hakluke/hakrawler
- There are many more...

Supporting evidence for this can be found in Jason Hadix's most recent [bug hunters methodology](https://drive.google.com/file/d/1aG_qqRvNW-s5_8vvPk5rJiMSMeNL2uY9/view), skimming through this will also give you a good idea of how Amass is used in a professionals workflow.

During our brief chat on Discord @caffix suggested it wise to not try and emulate the excellent work already completed by these projects but that we utilise the Lua scripting available in Amass to allow us to consume their outputs instead. I think this is a sensible approach.

I envisage this working thusly:

1. We decide what outputs from these tools are desirable. I have initially proposed that we store associated URLs (which would also cover JS links as they are URLs themselves after all) and open ports.
2. Then storage tables in the database need to be created. (Do we want to be able to track new items like Amass does for subdomains?)
3. If the scripting engine cannot currently run post processing scripts then that needs to be created.
4. Documentation created showing how to map the data from the tools into the pre-built database fields using the Lua scripting engine.

**Comment by caffix** [comment]
You wish to import findings from other tools into the Amass graph database?

**Comment by JeffreyShran** [comment]
no longer required due to Amass updates since. Thanks.
