### ISSUE TITLE
Feature Request: Running amass enum on a list of domains

### ISSUE THREAD

**Issue by FaizanNehal** [OWASP/Amass#457]
I don't if amass have a feature, or I am not able to find it, where we can pass a list of domains to amass enum and it would find the sub-domains of that domains.
Basically what I am trying to say is that if we want to ran a passive enum we usually try `amass enum -passive -d example.com`. I am requesting a feature in which we can supply a list of domains like for example: `amass -enum -passive -d ./listOfExampleDomains.txt`, and it would find the sub-domains of all the domains in the list. That would be very helpful for everyone. And if amass already have this feature please tell me I am not able to do this.

Thanks,
Faizan Nehal

**Comment by caffix** [comment]
There are multiple ways that amass can currently do what you're asking:

1. Use the `-df` flag to pass in your text file that has one domain on each line
2. Use the `-d` flag with the domain names comma separated
3. Go through the trouble of providing your domains names in the config.ini file

Hopefully, this helps to solve your issue

**Comment by FaizanNehal** [comment]
Thanks @caffix , I was able to run a domain list. 
Sorry if this was a basic question but I am new to command line tools. Again thanks for the help I am closing this.
