### ISSUE TITLE
The Dockerfile is not working due to missing git executable from alpine images

### ISSUE THREAD

**Issue by bjhulst** [OWASP/Amass#469]
The git command is not found in any alpine image since 2019 or so...

See also 
https://github.com/docker-library/golang/issues/209
and
https://github.com/docker-library/golang/issues/119

### Amass docker build log output:
...
Step 2/13 : RUN apk --no-cache add git
 ---> Running in f2fcb8e53211
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
**WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)**
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
**WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  git (missing):
    required by: world[git]**
The command '/bin/sh -c apk --no-cache add git' returned a non-zero code: 1

**Comment by bjhulst** [comment]
https://github.com/OWASP/Amass/blob/master/Dockerfile

**Comment by caffix** [comment]
This Dockerfile built properly when recently tested

**Comment by bjhulst** [comment]
I tried again today and it still gave the error since git is not found from the alpine image anymore.

ERROR: unsatisfiable constraints:
  git (missing):
    required by: world[git]
The command '/bin/sh -c apk --no-cache add git' returned a non-zero code: 1
