### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Jamesaglad** [OWASP/Amass#470]
Hi can anyone tell me if I need to remove the hashtags in my config file for the api's to work or if the hash tags are needed.

Thanks

James

**Comment by ngkogkos** [comment]
Hi James,

Hashtags in the config file denote a comment, so you will need to remove it to uncomment the section/lines and have a working API. So it will need to look like this:

![image](https://user-images.githubusercontent.com/1519209/91042931-44bd8d00-e61b-11ea-890c-52957590ff49.png)

Please redirect questions like this to Amass' official Discord server https://discord.gg/rtN8GMd as we are trying to avoid overflowing GitHub with such issues.

Hope this helps.

Nick

**Comment by Jamesaglad** [comment]
Thank you I will do. Thanks for your swift response.

Regards
James

**Comment by Jamesaglad** [comment]
Thanks for your help. Really appreciate it, now my recon will actually
benefit from all the apis I signed up for.

Kind regards

James

P. S u guys are really doing an amazing job, much respect
