### ISSUE TITLE
Feature Request: Instant Subdomain Fetch or Fresh Deployed Subdomain Fetch

### ISSUE THREAD

**Issue by saintmalik** [OWASP/Amass#473]
Amass is an awesome tool, to be honest.

but there is something I noticed Amass couldn't get, which is getting of freshly deployed subdomains.

So one day I was doing recon on a target, gathered all subdomains actually. but while navigating the website itself, the site has a navbar which explains the subcategories of contents to navigate around. 

On clicking on a nav bar link which I had never seen there before. a new window was loaded and it was a new fresh subdomain that the company created to host their Software engineers project. 

The domain was created that week. but none of the existing subdomain tools could find this newly created subdomain.

So I would love to request the features of being able to crawl for instant/deployed subdomains scans.

Thank you

**Comment by caffix** [comment]
You used the `-active` flag that causes Amass to perform crawling?
