### ISSUE TITLE
enum package Start() cpu go to 100%

### ISSUE THREAD

**Issue by tarn4** [OWASP/Amass#475]
i use the code on this link https://github.com/OWASP/Amass/blob/master/doc/user_guide.md#integrating-owasp-amass-into-your-work

1、ExtractOutput() now need two params.
2、Start() will get the cpu go to 100% and will not end.

and i want to know that can i get the lastest subdomains for real-time

**Comment by caffix** [comment]
Try the latest version of the code and bring questions about usage to the Discord server
