### ISSUE TITLE
flag provided but not defined: -public-dns

### ISSUE THREAD

**Issue by ipk1** [OWASP/Amass#479]
amass enum -active -d $1 -min-for-recursive 0 -public-dns -brute -w /SecLists/Discovery/DNS/deepmagic.com-prefixes-top50000.txt  -config config.ini so this is the command i use for enumeration of late i have been getting "flag provided but not defined: -public-dns

thanks
ipk1

**Comment by caffix** [comment]
You will need to remove the `-public-dns` flag. If you wish to use other public DNS resolvers, you can select them using various tools available, and then provide them to Amass via the `-rf` flag. If necessary, this can be discussed further on the Amass Discord server
