### ISSUE TITLE
Loading the config file causes an error

### ISSUE THREAD

**Issue by CuriousIncident** [OWASP/Amass#480]
After performing the upgrade loading the config file caused this error:
Failed to load the configuration file: section "data_sources" does not exist
I am really sure there is something wrong, because I just had a successful run
prior to upgrading. 
Maybe someone can replicate or find the issue?

**Comment by caffix** [comment]
Versions > v3.10 use a slightly different config file format and will require you to upgrade existing files. Please see the [example configuration file](./examples/config.ini)

**Comment by CuriousIncident** [comment]
Somehow missed that. I solved it now thank you for the great work.

**Comment by duraki** [comment]
@caffix @CuriousIncident what shall be changed for new config to be refactored? I just updated `amass` on OSX and it spits the same error for me. I tried looking at [this wiki](https://github.com/OWASP/Amass/wiki/The-Configuration-File#Data-Source-Sections) page but haven't found out what have changed. Pointers, please?

**Comment by caffix** [comment]
@duraki It's a requirement of the INI file format when taking advantage of hierarchy in the configuration file

**Comment by duraki** [comment]
Yup, I understood it later it must be some arch dep. Backward compatibility would be nice, ngl.
