### ISSUE TITLE
Amass db -show doesn't work after upgrading to 3.10

### ISSUE THREAD

**Issue by ricsirigu** [OWASP/Amass#483]
The `amass db -show -ip -d TARGET` command gets stucked with the message

`Could take a moment while acquiring AS network information`

Wireshark shows lot of DNS requests but I get no results even after hours

**Comment by caffix** [comment]
Please try this again with the most recent version of Amass

**Comment by ricsirigu** [comment]
> Please try this again with the most recent version of Amass

Works perfectly on 3.10.4!

**Comment by ricsirigu** [comment]
Solved in the latest version

**Comment by caffix** [comment]
Thank you @ricsirigu
