### ISSUE TITLE
Can we disable Bruteforce queries with -passive flag?

### ISSUE THREAD

**Issue by sting8k** [OWASP/Amass#487]
Using amass enum mode with -passive seems not disable brute force. How can I disable this type of scan?
```
...
Querying BinaryEdge for netflix.com subdomains
Querying Bing for netflix.com subdomains
Querying Brute Forcing for netflix.com subdomains
Querying BufferOver for netflix.com subdomains
Querying BuiltWith for netflix.com subdomains
...
```

**Comment by sting8k** [comment]
Found it, use `-exclude "Brute Forcing"`

**Comment by caffix** [comment]
There are improvements that can be made on this issue. Thank you for bringing it to our attention
