### ISSUE TITLE
running multiple domains kills the enumeration process

### ISSUE THREAD

**Issue by praveenbhuviceh** [OWASP/Amass#488]
goroutine 2247967 [chan receive]:
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).queueQuery(0xc0001a14a0, 0xc092e1f200, 0xc0be2bb181, 0x10, 0xc092e1001c, 0x0, 0xc0843afdf0)
	/home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:350 +0x113
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).Resolve(0xc0001a14a0, 0x144d120, 0xc0034fa030, 0xc0be2bb181, 0x10, 0x1186759, 0x4, 0x0, 0x0, 0x0, ...)
	/home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:246 +0x2a6
github.com/OWASP/Amass/v3/resolvers.(*RateMonitoredResolver).Resolve(0xc00b22fd80, 0x144d120, 0xc0034fa030, 0xc0be2bb181, 0x10, 0x1186759, 0x4, 0x0, 0x0, 0x0, ...)
	/home/caffix/go/src/github.com/OWASP/Amass/resolvers/ratemon.go:151 +0x1fc
github.com/OWASP/Amass/v3/resolvers.(*ResolverPool).Resolve(0xc00007d040, 0x144d120, 0xc0034fa030, 0xc0be2bb181, 0x10, 0x1186759, 0x4, 0x0, 0xc098059560, 0x1, ...)
	/home/caffix/go/src/github.com/OWASP/Amass/resolvers/pool.go:337 +0x11d
github.com/OWASP/Amass/v3/enum.(*DNSService).queryInitialTypes(0xc003488150, 0x144d120, 0xc0034fa030, 0xc07e25f860, 0xc037678f90, 0x1, 0x1)
	/home/caffix/go/src/github.com/OWASP/Amass/enum/dnssrv.go:101 +0x1f4
github.com/OWASP/Amass/v3/enum.(*DNSService).processDNSRequest(0xc003488150, 0x144d120, 0xc0034fa030, 0xc07e25f860)
	/home/caffix/go/src/github.com/OWASP/Amass/enum/dnssrv.go:84 +0x1c5
created by github.com/OWASP/Amass/v3/enum.(*DNSService).OnDNSRequest
	/home/caffix/go/src/github.com/OWASP/Amass/enum/dnssrv.go:56 +0x9e

When trying to run 100 domains using -df it automaticalls kills the process after 10 hours could you please suggest me reliable way to run bulk domains using -df

**Comment by caffix** [comment]
It's most likely due to not having enough RAM for that enumeration. We can discuss this further on the Amass Discord server
