### ISSUE TITLE
Amass CPU Usage

### ISSUE THREAD

**Issue by jaikishantulswani** [OWASP/Amass#497]
@caffix Amass is taking a higher CPU usage, can you please let me know whats going wrong as sometime it goes from 20% to 48+ CPU Usage.
![Screenshot from 2020-10-09 16-14-26](https://user-images.githubusercontent.com/30144126/95574914-68158d80-0a4b-11eb-98e6-233a13d61ea8.png)
![Screenshot from 2020-10-09 16-19-45](https://user-images.githubusercontent.com/30144126/95574921-6a77e780-0a4b-11eb-8f5d-bfb98bda0ede.png)

**Comment by caffix** [comment]
Please bring usage questions to our Discord server
