### ISSUE TITLE
Amass taking forever to return output

### ISSUE THREAD

**Issue by AAShakil50** [OWASP/Amass#499]
### Is it like this Or just for me?

I'm using **Amass** for the first time. But it's super slow. Just see these screenshots. 1m just to return list of resources.

![Command](https://user-images.githubusercontent.com/62601862/95659687-94f99b80-0b44-11eb-8f00-5cd88d60fd90.png)
![Output after 1m](https://user-images.githubusercontent.com/62601862/95659708-b78bb480-0b44-11eb-9374-5859ee26cb8e.png)

I made a passive enum on  a domain but no network traffic capturing and it's taking forever. I mean it's not searching. 
`amass enum --passive -d example.com`

>Amass v3.10.5.
>Go v1.15.2
>Lua v5.4.0
>docker vLatest

**Comment by caffix** [comment]
We can help you troubleshoot this better in the [Amass Discord server](https://discord.gg/rtN8GMd)
