### ISSUE TITLE
[Feature Request] Add progress indicator

### ISSUE THREAD

**Issue by CharlieEriksen** [OWASP/Amass#50]
In the newest version (2.8.2), I'm finding that with -T4, my scans are taking awfully long, and I can't really tell if the process is doing anything.

Would it be possible to maybe have a flag, which outputs every X time, a status on what's going on? Like how many requests are being sent per second when brute forcing, or similar? Queue stats? Stuff like that?

**Comment by caffix** [comment]
@CharlieEriksen How is the progress indicator working for you?
