### ISSUE TITLE
I can't run amass on my azure vm

### ISSUE THREAD

**Issue by kac3pro** [OWASP/Amass#506]
I installed amass on a linux vm running on azure but when I run `amass enum -d example.com` it doesn't provide any output. Tried using the -r with different dns but it doesn't work. Is there something I should edit in vm settings I don't know about? The dig and curl commands work normally.
![Screenshot 2020-10-25 124059](https://user-images.githubusercontent.com/49036464/97107429-bf606280-16c7-11eb-8e3b-cc8734892375.png)

**Comment by shebi4** [comment]
same here i dont get any output .  i run amass enum -d example.com  it doesn't provide any output.

**Comment by mohammed-sec2010** [comment]
try this command below:
amass enum  --active -brute -d site.com  -rf /opt/resolvers.txt -w /opt/subdomainworldlist/fullSubdomains.txt
