### ISSUE TITLE
Bug: no persistence of results

### ISSUE THREAD

**Issue by schrnz** [OWASP/Amass#512]
When using the `intel` and `enum` commands, either while directly pointing them to a directory with `-dir` or not providing the flag, amass will not generate the database that the `db`, `viz` and `track` commands are meant to interact with. 

Quick example usage:

```sh
amass enum -d owasp.org -passive -include AlienVault -dir ./amass-out
[AlienVault]      blogs.owasp.org
[AlienVault]      update-wiki.owasp.org
[AlienVault]      secureflag.owasp.org
[AlienVault]      dev.owasp.org
[AlienVault]      phpsec.owasp.org
[AlienVault]      www2.owasp.org
[AlienVault]      austin.owasp.org
[AlienVault]      name-virt-host.owasp.org
[AlienVault]      new-wiki.owasp.org
[AlienVault]      tsd.owasp.org
[AlienVault]      www.owasp.org
[AlienVault]      videos.owasp.org
[AlienVault]      kerala.owasp.org
[AlienVault]      lists.owasp.org
[AlienVault]      cheatsheetseries.owasp.org
[AlienVault]      owasp4.owasp.org
[AlienVault]      contact.owasp.org
[AlienVault]      sl.owasp.org
[AlienVault]      ocms.owasp.org
[AlienVault]      wiki.owasp.org
[AlienVault]      owasp.org
```

Even though I see results, the directory `amass-out` stays empty. The folder is also not created if missing. Unfortunately, this renders 3 out of 5 commands dysfunctional. 

Setup:
Ubuntu 20.04.1 LTS
installation via `snap`

**Comment by caffix** [comment]
The `intel` subcommand does not yet have support for saving the findings. The `enum` subcommand does, but not in passive mode, since there's nothing to save but a list of FQDNs and they are not verified

**Comment by schrnz** [comment]
Thanks for the clarification, did not see this anywhere in the docs. Can confirm that for `enum` and without the passive flag, the data is persisted and available for the other commands. 

Although, when I provide a dedicated output folder like `/tmp/amass-db`, the folder is not created *but* 
`amass track -d owasp.org -dir /tmp/amass-db` works... 

So to clarify, I provide the output dir, I can use it with other commands but the path does not even exist on the file system. 
I don't really know too much about snaps, but might this be related to some chroot or other sandboxing mechanisms at work here?

**Comment by caffix** [comment]
Yes. Snapcraft creates additional complexities due to protections it provides. I would choose another installation option if you wish to take full advantage of the tool

**Comment by schrnz** [comment]
Okay, I see. The results of this issue could be helpful additions to the docs imho. Will have a look if I find some time the next days.

**Comment by MalikSl** [comment]
><svg srv='google.com'<script>alert(11)</script>
