### ISSUE TITLE
Amass not scanning alla domains

### ISSUE THREAD

**Issue by OSINT-d** [OWASP/Amass#514]
Hi everyone,
my Amass does not scan all domains I give it as input.

I used two commands:
amass enum -df FILE -ip -o OUTPUTFILE.CSV
amass enum -d DOMAIN [the same for all domains in the list] -ip -o OUTPUTFILE.CSV.

Amass starts working on domains but it is extremely slow and never finishes the scan.

Is there anyone who can help me? 

Thx

**Comment by caffix** [comment]
In your second example, are you comma separating the domain names? These troubleshooting questions should be brought to the [Amass Discord Server](https://discord.gg/rtN8GMd)

**Comment by OSINT-d** [comment]
Hi Jeff,
no commas!

Thank you, I will submit it to the link you gave me.

Best regards,

VALERIA MARIA D’ONGHIA
OSINT Analyst


[cid:image001.jpg@01D6B91B.67EEB100]

Da: Jeff Foley <notifications@github.com>
Inviato: giovedì 12 novembre 2020 17:42
A: OWASP/Amass <Amass@noreply.github.com>
Cc: Valeria Maria D'Onghia <vd@intuity.it>; Author <author@noreply.github.com>
Oggetto: Re: [OWASP/Amass] Amass not scanning alla domains (#514)


In your second example, are you comma separating the domain names? These troubleshooting questions should be brought to the Amass Discord Server<https://discord.gg/rtN8GMd>
