### ISSUE TITLE
Failed to Load Configuration File

### ISSUE THREAD

**Issue by nagarajcruze** [OWASP/Amass#516]
Failed to load the configuration file: Failed to load the configuration file: key-value delimiter not found: URLScan can be used without an API key, but the key allows new submissions to be made 
I just copied the config file from github and added all free API keys then if i use the config file with -config argument, it throws this error and also amass -enum list is not showing the API that i added.

Do you have any idea about this error? help me please.

**Comment by nagarajcruze** [comment]
Should i want to keep the data sources as #as prefix? 
like this? 
#https://otx.alienvault.com (Free)
#[data_sources.AlienVault]
#[data_sources.AlienVault.Credentials]
#apikey=xxxxxxxxxxxxxx

or 
without # ?
https://otx.alienvault.com (Free)
[data_sources.AlienVault]
[data_sources.AlienVault.Credentials]
apikey=xxxxxxxxxxxxxxx

i did both, when i have the # then i'm not getting that previous error, but still -list is not showing the updated available resources.

**Comment by nagarajcruze** [comment]
[data_sources]
# When set, this time-to-live is the minimum value applied to all data source caching.
minimum_ttl = 1440 ; One day

# Are there any data sources that should be disabled?
#[data_sources.disabled]
#data_source = Ask
#data_source = Exalead
#data_source = IPv4Info

# Provide data source configuration information.
# See the following format:
#[data_sources.SOURCENAME] ; The SOURCENAME must match the name in the data source implementation.
#ttl = 4320 ; Time-to-live value sets the number of minutes that the responses are cached.
# Unique identifier for this set of SOURCENAME credentials.
# Multiple sets of credentials can be provided and will be randomly selected.
#[data_sources.SOURCENAME.CredentialSetID]
#apikey = ; Each data source uses potentially different keys for authentication.
#secret = ; See the examples below for each data source.
#username =
#password =

#https://otx.alienvault.com (Free)
#[data_sources.AlienVault]
#[data_sources.AlienVault.Credentials]
#apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://app.binaryedge.com (Free)
#[data_sources.BinaryEdge]
#ttl = 10080
#[data_sources.BinaryEdge.Credentials]
#apikey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://c99.nl (Paid)
#[data_sources.C99]
#ttl = 4320
#[data_sources.C99.account1]
#apikey =
#[data_sources.C99.account2]
#apikey =

#https://censys.io (Free)
#[data_sources.Censys]
#ttl = 10080
#[data_sources.Censys.Credentials]
#apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://chaos.projectdiscovery.io (Free-InviteOnly)
#[data_sources.Chaos]
#ttl = 4320
#[data_sources.Chaos.Credentials]
#apikey =

#https://cloudflare.com (Free)
#[data_sources.Cloudflare]
#[data_sources.Cloudflare.Credentials]
#apikey =

#Closed Source Invite Only
#[data_sources.CIRCL]
#[data_sources.CIRCL.Credentials]
#username =
#password =

#https://dnsdb.info (Paid)
#[data_sources.DNSDB]
#ttl = 4320
#[data_sources.DNSDB.Credentials]
#apikey =

#https://developer.facebook.com (Free)
# Look here for how to obtain the Facebook credentials:
# https://goldplugins.com/documentation/wp-social-pro-documentation/how-to-get-an-app-id-and-secret-key-from-facebook/
#[data_sources.FacebookCT]
#ttl = 4320
#[data_sources.FacebookCT.app1]
#apikey =
#secret =
#[data_sources.FacebookCT.app2]
#apikey =
#secret =

#https://github.com (Free)
#[data_sources.GitHub]
#ttl = 4320
#[data_sources.GitHub.accountname]
#apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://networksdb.io (Free)
#[data_sources.NetworksDB]
#[data_sources.NetworksDB.Credentials]
#apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://passivetotal.com (Free)
#[data_sources.PassiveTotal]
#ttl = 10080
#[data_sources.PassiveTotal.Credentials]
#username =
#apikey =

#https://recon.dev (Free)
#[data_sources.ReconDev]
#[data_sources.ReconDev.free]
#apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#[data_sources.ReconDev.paid]
#apikey =

#https://securitytrails.com (Free)
#[data_sources.SecurityTrails]
#ttl = 1440
#[data_sources.SecurityTrails.Credentials]
#apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://shodan.io (Free)
#[data_sources.Shodan]
#ttl = 10080
#[data_sources.Shodan.Credentials]
#apikey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://spyse.com (Paid/Free-trial)
#[data_sources.Spyse]
#ttl = 4320
#[data_sources.Spyse.Credentials]
#apikey =

#https://developer.twitter.com (Free)
# Provide your Twitter App Consumer API key and Consumer API secrety key
#[data_sources.Twitter]
#[data_sources.Twitter.account1]
#apikey =
#secret =
#[data_sources.Twitter.account2]
#apikey =
#secret =

#https://umbrella.cisco.com (Paid-Enterprise)
# The apikey must be an API access token created through the Investigate management UI
#[data_sources.Umbrella]
#[data_sources.Umbrella.Credentials]
#apikey =

#https://urlscan.io (Free)
#URLScan can be used without an API key, but the key allows new submissions to be made
#[data_sources.URLScan]
#[data_sources.URLScan.Credentials]
#apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://virustotal.com (Free)
#[data_sources.VirusTotal]
#ttl = 10080
#[data_sources.VirusTotal.Credentials]
#apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://whoisxmlapi.com (Free)
#[data_sources.WhoisXML]
#[data_sources.WhoisXML.Credentials]
#apikey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#https://zetalytics.com (Paid)
#[data_sources.ZETAlytics]
#ttl = 1440
#[data_sources.ZETAlytics.Credentials]
#apikey =

#[data_sources.ZoomEye]
#ttl = 1440
#[data_sources.ZoomEye.Credentials]
#username =
#password =
This is my config.inin file.

**Comment by nagarajcruze** [comment]
[demo-config.txt](https://github.com/OWASP/Amass/files/5579898/demo-config.txt)

This is how my config looks like. i have changed .ini to txt coz i cannot updload .ini file to github.

**Comment by asolab** [comment]
same issue am presently facing, any solution yet?

**Comment by nagarajcruze** [comment]
create a folder in home directory (~/.config/amass) and create a config.ini file over there and that's it, it will work.

**Comment by asolab** [comment]
pls can I get like a video of your explanation ? sorry for disturbing, Thanks!

**Comment by nagarajcruze** [comment]
You can follow this method
https://github.com/OWASP/Amass/blob/master/doc/user_guide.md#the-configuration-file
Uncomment the data sources that you have api key, 
example:-
if you have shodan api key then paste in the apikey={yourAPIKeY} then uncomment it. like this below.
From:-
#https://shodan.io (Free)
#[data_sources.Shodan]
#ttl = 10080
#[data_sources.Shodan.Credentials]
#apikey =

To

#https://shodan.io (Free)
[data_sources.Shodan]
ttl = 10080
[data_sources.Shodan.Credentials]
apikey =

**Comment by asolab** [comment]
I just did, unless I use the -dir its still not workiing,  even with the dir flag the list is not reflecting in my result, pls follow me back on twitter so I can dm you, just followed you @asolab

**Comment by nagarajcruze** [comment]
Done

**Comment by asolab** [comment]
Your DM is closed Boss

**Comment by caffix** [comment]
Please bring future requests for assistance with the configuration file to the Discord server
