### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by michenriksen** [OWASP/Amass#519]
**Amass Version:** `v3.10.5`
**System:** `Linux <redacted> 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

I regularly experience that `amass enum` panics when running it on my DigitalOcean VPS (don't know if that has anything to say). I tried to decrease the max DNS queries but the panic unfortunately still happens. This is roughly the command I run:

```bash
$ amass enum -ip -df domains.lst -nocolor -oA amass -max-dns-queries 200
```

### Error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xdb40f6]

goroutine 383937 [running]:
github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).tcpExchange(0xc000199860, 0x3dbebf, 0xc0064de500)
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:517 +0x56
created by github.com/OWASP/Amass/v3/resolvers.(*BaseResolver).processMessage
        /home/caffix/go/src/github.com/OWASP/Amass/resolvers/resolver.go:482 +0x519
```

Let me know if you need any more information!

**Comment by phackt** [comment]
Exactly the same error !

**Comment by phackt** [comment]
@michenriksen did you succeed in finding a work around with this issue ?

**Comment by michenriksen** [comment]
@phackt yes, I made a hotfix in my fork of the project. You can get the fixed version with the following commands:

```bash
go get github.com/michenriksen/Amass
cd ~/go/src/github.com/michenriksen/Amass
go build -o amass cmd/amass/*
```

**Comment by phackt** [comment]
Thanks @michenriksen ! i just saw your hotfix i will apply it waiting for amass team to merge it ! 

Regards,

**Comment by yusufmalikul** [comment]
> @phackt yes, I made a hotfix in my fork of the project. You can get the fixed version with the following commands:
> 
> ```shell
> go get github.com/michenriksen/Amass
> cd ~/go/src/github.com/michenriksen/Amass
> go build -o amass cmd/amass/*
> ```

Many thanks! this worked.

**Comment by michenriksen** [comment]
@yusufmalikul Thanks for letting me know! I updated my comment with the fix.

**Comment by JoshuaMart** [comment]
Hi,
Sometimes I have the same mistake

**System :** Ubuntu 20.04.1 LTS
**Amass version :** 3.11.10

Command :
```
amass enum -passive -d domain.tld
```

Error :
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xdc419e]

goroutine 5434 [running]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0x18e3458, 0xc000157970, 0xc00d459a28, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2012 +0x11e
panic(0xf397e0, 0x20c3fe0)
	/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/panic.go:965 +0x1b9
github.com/yuin/gopher-lua.callGFunction(0xc000157970, 0x0, 0xc001198080)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:262 +0x1f7
github.com/yuin/gopher-lua.init.3.func26(0xc000157970, 0xc07c100603, 0xc00306b000, 0x0)
	/home/runner/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:817 +0x39d
[...]
```

**Comment by caffix** [comment]
Thank you @JoshuaMart. I'm working on a fix for the upcoming release

**Comment by contaminatedesert** [comment]
Just here to say that this is also occurring in version 3.11.11. Ubuntu 20.04 via snap on GCP.

**Comment by caffix** [comment]
@contaminatedesert The most recent version is v3.11.12

**Comment by contaminatedesert** [comment]
Maybe this is a separate issue, but snap says I've got 3.11.12 as can be seen in the screenshot below, but the amass version number when I run it is 3.11.11.

![image](https://user-images.githubusercontent.com/16392834/113021207-33e87300-9138-11eb-9879-297e64f083dd.png)

![image](https://user-images.githubusercontent.com/16392834/113020922-ed931400-9137-11eb-8d7f-044f3533417c.png)

 Additionally, I am still encountering this issue. 

![image](https://user-images.githubusercontent.com/16392834/113021668-ab1e0700-9138-11eb-9342-bc891f4a1414.png)

**Comment by caffix** [comment]
@contaminatedesert The battle with the Lua scripting engine will continue

**Comment by caffix** [comment]
This issue appears to be under control now
