### ISSUE TITLE
'dns' subcommand does not write output to file even when specified

### ISSUE THREAD

**Issue by TheWebranger** [OWASP/Amass#523]
Following command does not write output to specified file:
```
amass dns -df domains.txt -nf subdomains.txt -oA amass
```
Even specifying directory does not work:
```

amass dns -df domains.txt -nf subdomains.txt -oA amass -dir output
```
Am I missing something?

**Comment by caffix** [comment]
It should give you `amass.txt` and `amass.json` in your present working directory. We can answer these types of questions for you in the Amass Discord server
