### ISSUE TITLE
Failed to Load Configuration File

### ISSUE THREAD

**Issue by asolab** [OWASP/Amass#527]
my amass has been unable to load my config.ini after I input all the necessary API keys and also keenly followed the location placement of the file .
![Screenshot (28)](https://user-images.githubusercontent.com/56577893/103956578-216a2900-5149-11eb-95f0-1e311a761f0a.png)

**Comment by moshebe** [comment]
It seems to be working on my machine.
Can you please attach the output of `ls -la` in the directory the command has been running?
It looks to me like the file name/path is incorrect or maybe missing read permission.

**Comment by caffix** [comment]
Users have incorrectly setup their configuration files before and then raised issues. It's easier to help users with their config files via the Discord server
