### ISSUE TITLE
More sources

### ISSUE THREAD

**Issue by shelld3v** [OWASP/Amass#530]
The API request to fetch subdomains: `https://jonlu.ca/anubis/subdomains/{domain}`

**Comment by shelld3v** [comment]
Hi, saw you pushed the source, appreciate it!! And here is another source that you need to add too:

`ThreatBook`: `https://api.threatbook.cn/v3/domain/sub_domains?apikey={API-KEY}&resource={DOMAIN}` (API key required)

Response:
```json
{
    "data": {
        "domain": "yahoo.com",
        "sub_domains": {
            "total": "10000",
            "data": [
                "news.yahoo.com",
                "research.yahoo.com",
                "my.yahoo.com",
                ...
            ]
        }
    },
    "response_code": 0,
    "verbose_msg": "OK"
}
```

**Comment by shelld3v** [comment]
Others:

`IPv4Info`: Steps:
- GET `http://ipv4info.com/search/NF/yahoo.com`
- Grep `/dns/(.*?)/yahoo.com` in the response for the token
- GET `http://ipv4info.com/subdomains/{TOKEN}/yahoo.com` for first subdomains.
- Now make a loop:
  -  In `http://ipv4info.com/subdomains/{TOKEN}/yahoo.com`, there is the URL for the next page. It's something like this: `/subdomains/{ANOTHER_TOKEN}/page{NUMBER}/yahoo.com`
  - And on that page, there is the URL for another next page (this is the loop) with a different token and a different page number (Note: the page number is from 1->2->3->...)
  - Break the loop if you can't find any token anymore, because that means out of subdomain

Reference: https://github.com/projectdiscovery/subfinder/blob/master/v2/pkg/subscraping/sources/ipv4info/ipv4info.go

**Comment by shelld3v** [comment]
Okay, so here are top 10 sources from subfinder:

```
1. ipv4info
2. cebaidu
3. certspotter
4. sitedossier
5. archiveis
6. bufferover
7. sublist3r
8. dnsdumpster
9. riddler
10. commoncrawl
```

**Note: About `certspotter`, subfinder looks for both old API and new API (Old: `https://certspotter.com/api/v0/certs?domain=`, New: `https://api.certspotter.com/v1/issuances?...`). Amass only fetchs the new one!!**

**Comment by shelld3v** [comment]
Also, IP138 is a really interesting scrape source I found from another tool: [OneForAll](https://github.com/shmilylty/OneForAll). The subdomains can be dumped with this URL: `https://site.ip138.com/{DOMAIN}/domain.htm`

**Comment by shelld3v** [comment]
New source: `archive.today`. You can't get all subdomains from **Archive.Today** (only first 50) because of the captcha, but those are pretty valuable

**Comment by shelld3v** [comment]
Hey, don't add `NetCraft` yet since there are some problems in getting the next page! I will tell you soon about this

**Comment by hazcod** [comment]
@caffix I wonder if we simply can integrate subfinder as a source?

**Comment by shelld3v** [comment]
subfinder is a tool that fetches subdomains sources, the same as amass, but amass has more sources! So, I don't think that adding subfinder as a source makes sense

**Comment by shelld3v** [comment]
@hazcod you can try these ADS scripts: https://gist.github.com/sillydadddy/b1726c8e8ce281d55b82d4e2a1a610e8 (`amass enum -d example.com -scripts /path/to/those/scripts`)

**Comment by caffix** [comment]
Examples of incorporating other tools using Amass Data Source scripts has been demonstrated in various training videos. One such script is shown below.

lua```
name = "test"
type = "api"

function start()
    setratelimit(1)
end

function vertical(ctx, domain)
    local cmd = outputdir(ctx) .. "/bin/assetfinder --subs-only " .. domain

    local data = assert(io.popen(cmd))
    for line in data:lines() do
        newname(ctx, line)
    end
    data:close()
end
```

**Comment by shelld3v** [comment]
Waiting to see **Ipv4Info** become a source...

**Comment by shelld3v** [comment]
Hey @caffix, I saw that ArchiveToday has been deleted because *"it does not work outside a browser"*. But, I'm seeing that subfinder still can find subdomains from http://archive.is!!! (5 xoom.com subdomains)
