### ISSUE TITLE
Max time feature.

### ISSUE THREAD

**Issue by fourteentheme** [OWASP/Amass#551]
Active scan is very slow. Can you provide max time feature? So I can set the max time to 1 hour for each domain.

**Comment by caffix** [comment]
There is already a `-timeout` flag that allows you to identify a maximum number of minutes for the enumeration to execute

**Comment by fourteentheme** [comment]
I'm not sure this is working correctly. For example, the command below doesn't take 5 seconds.
amass enum -active -d github.com -timeout 5
