### ISSUE TITLE
windows install err p.RawFragment undefinded *url.URL has no field or method RawFragment

### ISSUE THREAD

**Issue by gptshubham595** [OWASP/Amass#554]
![image](https://user-images.githubusercontent.com/24877361/106494884-fc1ad180-64e0-11eb-935f-9d3de1576daa.png)

**Comment by jimen0** [comment]
Hi @gptshubham595,

This has nothing to do with Windows. It seems your Go version is outdated. Current version is 1.15.7 and soon it will be [1.16](). [`(net/url).URL.RawFragment`](https://golang.org/doc/go1.15) was added in Go 1.15. Updating your Go version to 1.15.7 at least should work.

> net/url
>
> The new URL field RawFragment and method EscapedFragment provide detail about and control over the exact encoding of a particular fragment. These are analogous to RawPath and EscapedPath.

**Comment by gptshubham595** [comment]
Solved Thank You, Updated golang and it is working now.
