### ISSUE TITLE
new version feel slowly

### ISSUE THREAD

**Issue by icezhaoL** [OWASP/Amass#555]
new version
![image](https://user-images.githubusercontent.com/14086616/106550736-b3016680-654e-11eb-8895-7ae5bc1d16d8.png)

The old version had 100+k of traffic   ，It's now 3K of traffic

new version has a lot of ptr dns request。

**Comment by shelld3v** [comment]
It decreased the traffic but still has the same accuracy as the old version, even more. Reducing DNS traffic means less eating CPU and A LOT faster, isn't it good?

**Comment by icezhaoL** [comment]
I can handle more traffic，brute faster。  i set maximum_dns_queries = 60000  ，It doesn't have a significant effect

**Comment by shelld3v** [comment]
Not everyone, man, not everyone!

**Comment by shelld3v** [comment]
You are having a pretty strong machine, but a lot of people don't!
