### ISSUE TITLE
-update flag to Update Amass

### ISSUE THREAD

**Issue by stfuanu** [OWASP/Amass#565]
It's very nice to see one of my most  favorite tool Amass getting improved everyday and new additions very frequently . So can we please have an -update flag to update it quickly , So we won't have to  change/add config.ini api-keys again & again after deleting it installing again .

thanks :)

**Comment by stfuanu** [comment]
Figured out ,

```
apt-get install amass 
```

works fine ,  but still need to update config.ini in ~/.config/amass/ manually .

**Comment by shelld3v** [comment]
```
apt-get install amass 
```
won't install the latest version

**Comment by stfuanu** [comment]
idk how , but it did .
it prompted for yes/no to upgrade , i did yes and done .

```
amass -version
```
output is v3.11.2 , earlier it was 3.10. something .

**Comment by caffix** [comment]
I have never had to rebuild my configuration file. Just keep the config file in a location outside the Amass Project files. You can point Amass to your `config.ini` file using the `-config` flag
