### ISSUE TITLE
Feature Request - Apache TinkerPop Support (Graph)

### ISSUE THREAD

**Issue by kerberosmansour** [OWASP/Amass#57]
As a security Engineer I want to pick and choose my Graph backend which out having to worry about Amass Specific support for that Graph. Apache TinkerPop http://tinkerpop.apache.org/ Apache TinkerPop™ is a graph computing framework for both graph databases (OLTP) and graph analytic systems (OLAP).

**Comment by caffix** [comment]
I like this idea, and it appears easy enough to send Amass results to an Apache TinkerPop database. Is this what you had in mind?

**Comment by kerberosmansour** [comment]
Yes, thanks Jeff!

**Comment by caffix** [comment]
This feature should be available in version 2.9.1

**Comment by caffix** [comment]
This feature was implemented in v3.6.0
