### ISSUE TITLE
Excluding multiple data sources not working

### ISSUE THREAD

**Issue by teavanist** [OWASP/Amass#571]
Hi, 
I am trying to run a scan and I wanted to exclude two sources Alterations and Reverse DNS. But regardless of how I try, amass continues to list Reverse DNS. As per the documentation we should separate the data sources by a comma 

amass enum -d company.com -src -ip -exclude Alterations, Reverse DNS

I also tried to add these two in the config file for exclusion. But even there Reverse DNS results continue to show up. 

Is there something wrong in my use of the command ?

Edit: Some of the other combinations I tried: 
-exclude 'Alterations, Reverse DNS'
-exclude 'Alterations' , 'Reverse DNS'

**Comment by caffix** [comment]
Currently, Reverse DNS is not a data source that can be excluded

**Comment by teavanist** [comment]
Thanks @caffix for the clarification

**Comment by GhostDog98** [comment]
Sorry to necro here, but is there a place that contains a list of all the data sources that cannot be excluded? This is kinda important to know when amass continues to print verbose messages for the excluded source, making it impossible to verify if you've disabled a source successfully... Couldn't find it anywhere in the docs...
