### ISSUE TITLE
Docker run error

### ISSUE THREAD

**Issue by unstppbl** [OWASP/Amass#58]
Built the docker image with `docker build -t amass https://github.com/OWASP/Amass.git`,
tried to run it, but got error. A possible fix would be to ignore SSL check in http.Transport options.

```bash
╰$ sudo docker run amass --passive -d example.com
Get https://raw.githubusercontent.com/OWASP/Amass/master/wordlists/namelist.txt: x509: certificate signed by unknown authority
```

**Comment by caffix** [comment]
@unstppbl Has Amass version 2.8.5 resolved this issue for you?

**Comment by unstppbl** [comment]
> @unstppbl Has Amass version 2.8.5 resolved this issue for you?

Yup, works like a charm

**Comment by caffix** [comment]
Great! I'll be closing the issue then

**Comment by euglpe** [comment]
I got same issue in version 2.9.0
