### ISSUE TITLE
Add subdomain enumeration  with whois Registrar Abuse Contact Email

### ISSUE THREAD

**Issue by tk-t0n0y** [OWASP/Amass#580]
I have a Registrar Abuse Contact Email of a company . How to use this company mail  to amass to discover more subdomain with this mail . In whois look up website there is a feature like paste email and find domain .. is it possible to use amass to get subdomain which is registered by company@hhd.com

**Comment by caffix** [comment]
You can use the domain name in the email as your parameter to the `-d` flag. Feel free to bring these usage questions to our Discord server
