### ISSUE TITLE
The system was unable to build the pool of resolvers

### ISSUE THREAD

**Issue by acvn** [OWASP/Amass#581]
my amass is not working on ubuntu 20.04, the result is "The system could not build the resolver set". can somebody help me? 
![2021-02-19_23-26](https://user-images.githubusercontent.com/52058660/108531962-e0e5f980-7309-11eb-91cb-344e8d5376bf.png)

**Comment by caffix** [comment]
The error means that your system/network is not allowing Amass to reach the DNS resolvers. Please feel free to join our Discord server for troubleshooting and questions regarding usage

**Comment by DamianKowalik78** [comment]
Same here. Any chance explain here instead of joining Discord ?
