### ISSUE TITLE
Script: Failed to load script

### ISSUE THREAD

**Issue by nancheal** [OWASP/Amass#582]
when Integrating amass with my work, and print all the log, there is a error when load script

Script: Failed to load script: <string> line:116(column:27) near '{':   syntax error

and i log the error file is

Amass/resources/scripts/api/bgpview.ads 

is there any bug? thanks

**Comment by caffix** [comment]
Is this still happening to you?

**Comment by tk-t0n0y** [comment]
Yes , not working now ,

**Comment by caffix** [comment]
You're using the latest version (3.12.3)?

**Comment by tk-t0n0y** [comment]
Yes

**Comment by tk-t0n0y** [comment]
Yes
