### ISSUE TITLE
why is it waiting after starting the program?

### ISSUE THREAD

**Issue by Phoenix1112** [OWASP/Amass#584]
hi. thanks for this project.. i am using amass on ubuntu vps server
every time I start the program it waits for about 20 minutes and then it runs. Why is it waiting so long? Won't you make a fix?

amass version: v3.11.5
os: ubuntu
ram: 32gb
cpu: 6
commands:

```amass enum -passive -d example.com -o outputtxt```
```amass enum -config config.ini -d example.com -o output.txt```

**Comment by caffix** [comment]
These troubleshooting requests should be brought to our Discord server. I would suggest removing the default output directory using the following command: `rm -rf ~/.config/amass`

Also, be sure you're not running both of the commands you listed above at the same time

**Comment by Phoenix1112** [comment]
@caffix thnaks for answer..  this command worked for me.. ```rm -rf ~/.config/amass```
I expect your success to continue. If I have a problem again, I'll ask a question on your discord channel.

**Comment by caffix** [comment]
Thank you. I'm glad to hear it worked for you and will close the issue now
