### ISSUE TITLE
ArchiveToday bug

### ISSUE THREAD

**Issue by chrisdlangton** [OWASP/Amass#586]
Saw this
```
ArchiveToday: vertical callback: <string>:12: bad argument #2 to scrape (table expected, got string)
stack traceback:
    [G]: in function 'scrape'
    <string>:12: in main chunk
    [G]: ?

OWASP Amass v3.11.3                               https://github.com/OWASP/Amass
--------------------------------------------------------------------------------
2 names discovered - scrape: 1, dns: 1
```
I expected 20+ subdomains and expect getting only 2 is related to this bug.

re-running a little later, and using various other domains did not make any difference

**Comment by shelld3v** [comment]
@chrisdlangton Can you try updating your Amass to the latest version?

**Comment by chrisdlangton** [comment]
I've done that and the error has gone away. strange. The patch notes didn't mention anything for ArchiveToday so i was sceptical
