### ISSUE TITLE
Still getting a build issue with the dockerfile

### ISSUE THREAD

**Issue by dsamuel323** [OWASP/Amass#588]
When building the dockerfile, I still get the following issue even with the fix: 

<img width="837" alt="Screen Shot 2021-03-02 at 7 52 51 AM" src="https://user-images.githubusercontent.com/8119153/109651346-69477400-7b2c-11eb-9d6c-bd79060bfeef.png">

**Comment by ZeroDot1** [comment]
https://github.com/OWASP/Amass/issues/585#issuecomment-785554784
