### ISSUE TITLE
[Test Case] Test passive sources (mainly crt.sh)

### ISSUE THREAD

**Issue by mikailtunc** [OWASP/Amass#59]
Write a test case to ensure Amass is successfully pulling down all subdomains that we know exists within a domain we control.

`letsencrypt.owasp-amass.com` is the domain to be tested and should return exactly 100 unique results:

```
1.letsencrypt.owasp-amass.com
2.letsencrypt.owas-amass.com
...
100.letsencrypt.owasp-amass.com
```

If domains {1...100}.letsencrypt.owasp-amass.com are returned in the -passive scan then we know crt.sh is working as intended.

**Comment by caffix** [comment]
@mikailtunc The test consistently returns 98 names, and I see the 20.letsencrypt.owasp-amass.com and the 40.letsencrypt.owasp-amass.com missing. Do you see this on your side?

**Comment by emtunc** [comment]
@caffix Is this test run using crt.sh? If so, the full list of subdomains can be seen here:

https://crt.sh/?q=%25.letsencrypt.owasp-amass.com

**Comment by caffix** [comment]
I found the problem, and the fix is in the upcoming PR.

**Comment by mikailtunc** [comment]
All good, thank you!
