### ISSUE TITLE
Installation on Apple Silicon

### ISSUE THREAD

**Issue by h4vi** [OWASP/Amass#590]
Had some issues with the traditional installation of amass on a mac equipped with an arm chip. Thought it was worth mentioning along with the workaround I used for anyone else having the same problem:

`arch -x86_64 bash`

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

`alias brew_86="arch -x86_64 /usr/local/homebrew/bin/brew"`

`brew_86 tap caffix/amass`

`brew_86 install amass`

`alias amass="/usr/local/homebrew/Cellar/amass/3.11.8/bin/amass"`

From there, you should be able to run amass in bash.

**Comment by h4vi** [comment]
Open to any more permanent suggestions out there!

**Comment by caffix** [comment]
The next release should have support for the Apple Silicon when installing via Homebrew

**Comment by hazcod** [comment]
@caffix FYI the home-brew repo will have to be updated as wel. 
https://github.com/caffix/homebrew-amass/blob/master/Formula/amass.rb

**Comment by caffix** [comment]
@hazcod The homebrew tap is updated automatically. It turns out that more GitHub actions needed to be updated to allow the additional build to be performed

**Comment by adwaithks-orca** [comment]
`amass enum -passive -d domain.com` on MacBook Air M1 is giving me `runtime: failed to create new OS thread`. Installed amass via homebrew caffix.

**Comment by adwaithks** [comment]
When I run amass on Macbook Air M1 (`amass enum -passive -d domain.com`), it gives an error `runtime: failed to create new OS thread`. Installed amass via homebrew.
