### ISSUE TITLE
Build error for Amass\datasrcs\cloudflare.go

### ISSUE THREAD

**Issue by pracsyssec** [OWASP/Amass#593]
I am trying to build amass from github on Windows. My go version is go1.16.2 windows/amd64 and I have a user environment variable for GO111MODULE=on. 

I tried installing with the following commands:
`go get -u -v github.com/OWASP/Amass/...`
`go get -u -v github.com/OWASP/Amass/v3/...`
`go get -u -v github.com/OWASP/Amass/cmd/amass`

Build fails on the following:

`github.com/OWASP/Amass/datasrcs
go\src\github.com\OWASP\Amass\datasrcs\cloudflare.go:84:33: cannot use req.Domain (type string) as type context.Context in argument to api.ListZones:
        string does not implement context.Context (missing Deadline method)
go\src\github.com\OWASP\Amass\datasrcs\cloudflare.go:90:33: not enough arguments in call to api.DNSRecords
        have (string, cloudflare.DNSRecord)
        want (context.Context, string, cloudflare.DNSRecord)`

Am I missing something?

**Comment by caffix** [comment]
People on the Discord server can share how to properly build Amass from source
