### ISSUE TITLE
Amass intel command not working for Amass > v3.10.5

### ISSUE THREAD

**Issue by shadow1587** [OWASP/Amass#594]
Hi,

The Amass intel command doesn't seem to be working for amass version 3.11.5. It works fine in v3.10.5 but when I use anything later than that version no output is returned after the command finishes running, no error messages are printed either. I've tried using the built binaries and also built from sources but the same issue persists.

I have tried on the below system:
kali 2021.1 and go1.15.6

Command used:
amass intel -src -whois -d <domain>

**Comment by caffix** [comment]
The ViewDNS data source has been removed. The reverse WHOIS feature is dependent on the data sources you have access to

**Comment by shadow1587** [comment]
Thanks for the update, I'll have a look at other data sources.

**Comment by jcalderonaxos** [comment]
@caffix , So... how do I have this working again? what whois other data sources can I integrate and how?
