### ISSUE TITLE
how to add more than 1 api keys in config.ini

### ISSUE THREAD

**Issue by parabss** [OWASP/Amass#595]
What's the syntax if i want to add more than 1 api key of a single source in config.ini file ?

1) ```apikey = xxx, xxx```

2)  ```apikey="xxx" , "xxx" ```  

3) ```apikey= 'xxx' ; 'xxx' ```

4)  
```
# https://whoisxmlapi.com (Free)
[data_sources.WhoisXML]
[data_sources.WhoisXML.Credentials]
apikey =   xxxx
apikey =   xxxxx
```

5)
```
apikey=xxx;
apikey=xxx;

```

**Comment by mzpqnxow** [comment]
@parabss check out https://github.com/OWASP/Amass/blob/master/examples/config.ini that should give you what you're looking for. For your case, I think you would want something like this- or something close to it:

```
[data_sources.WhoisXML]
# Applies to all WhoisXML accounts
ttl = 43200 

[data_sources.WhoisXML.account1]
apikey = xxxx

[data_sources.WhoisXML.account1]
apikey = yyyy
```

**Comment by caffix** [comment]
Just be sure that both accounts are not given the same name like the example above

**Comment by mzpqnxow** [comment]
> Just be sure that both accounts are not given the same name like the example above

Good eye, I fixed up the copy pasta. I think this can probably be closed now @parabss

**Comment by molitona** [comment]
@parabss  @caffix @mzpqnxow 

is like that fine ??

![Screenshot from 2022-09-08 23-00-07](https://user-images.githubusercontent.com/35532337/189233659-921ac799-cf7c-4fc0-84c5-eebb58cf316b.png)

**Comment by NITIN911** [comment]
https://github.com/owasp-amass/amass/blob/master/examples/config.ini

Not found

**Comment by mzpqnxow** [comment]
https://github.com/examples/config.yaml
