### ISSUE TITLE
issue with amass

### ISSUE THREAD

**Issue by knowthetech** [OWASP/Amass#596]
OWASP Amass v3.11.10                              https://github.com/OWASP/Amass
--------------------------------------------------------------------------------
45 names discovered - api: 2, cert: 9, archive: 32, alt: 1, dns: 1
--------------------------------------------------------------------------------
ASN: 20940 - AKAMAI-ASN1
	secret/23   	4    Subdomain Name(s)
ASN: 15169 - GOOGLE - Google LLC
	secret/14     	1    Subdomain Name(s)
	secret/14      	42   Subdomain Name(s)

The enumeration has finished
Discoveries are being migrated into the local database
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xe7445e]

goroutine 2553 [running]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0x19d0fb0, 0xc000225080, 0xc0056219b0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2012 +0x11e
panic(0x100b020, 0x221c090)
	/root/.go/src/runtime/panic.go:969 +0x1b9
github.com/yuin/gopher-lua.callGFunction(0xc000225080, 0x0, 0xc0010579c0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:262 +0x1f7
github.com/yuin/gopher-lua.init.3.func26(0xc000225080, 0xc07c1c0203, 0xc0097f8000, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:817 +0x39d
github.com/yuin/gopher-lua.mainLoopWithContext(0xc000225080, 0xc0097f8000)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/vm.go:60 +0x126
github.com/yuin/gopher-lua.(*LState).callR(0xc000225080, 0x2, 0x0, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1203 +0x256
github.com/yuin/gopher-lua.(*LState).Call(...)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:1959
github.com/yuin/gopher-lua.(*LState).PCall(0xc000225080, 0x2, 0x0, 0x0, 0x1ad5d00, 0xc02fb4ebc0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2022 +0x114
github.com/yuin/gopher-lua.(*LState).CallByParam(0xc000225080, 0x1aee960, 0xc001084400, 0x0, 0x1, 0x0, 0xc0035a6a68, 0x2, 0x2, 0x1aec360, ...)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20200816102855-ee81675732da/state.go:2040 +0xe9
github.com/OWASP/Amass/v3/datasrcs/scripting.(*Script).dnsRequest(0xc0001e9cc0, 0x1aec360, 0xc009fdd830, 0xc002d86060)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.11.10/datasrcs/scripting/script.go:301 +0x386
github.com/OWASP/Amass/v3/datasrcs/scripting.(*Script).OnRequest(0xc0001e9cc0, 0x1aec360, 0xc009fdd830, 0x10279e0, 0xc002d86060)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.11.10/datasrcs/scripting/script.go:267 +0x113
reflect.Value.call(0xfc9c20, 0xc0130bcd20, 0x13, 0x1168486, 0x4, 0xc00f1a2090, 0x2, 0x2, 0xc0014c9500, 0xc000852060, ...)
	/root/.go/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xfc9c20, 0xc0130bcd20, 0x13, 0xc00f1a2090, 0x2, 0x2, 0x0, 0x0, 0x1)
	/root/.go/src/reflect/value.go:337 +0xb9
github.com/caffix/service.(*BaseService).processRequests.func1(0xf84380, 0xc00f1a20c0)
	/root/go/pkg/mod/github.com/caffix/service@v0.0.0-20210202222504-bfa33e78ab27/base.go:171 +0x1e5
github.com/caffix/queue.(*queue).Process(0xc00becca50, 0xc012fba280)
	/root/go/pkg/mod/github.com/caffix/queue@v0.0.0-20210301212750-6e488abe1004/queue.go:170 +0x4f
github.com/caffix/service.(*BaseService).processRequests(0xc0001e9cc0)
	/root/go/pkg/mod/github.com/caffix/service@v0.0.0-20210202222504-bfa33e78ab27/base.go:180 +0xb8
created by github.com/caffix/service.(*BaseService).Start
	/root/go/pkg/mod/github.com/caffix/service@v0.0.0-20210202222504-bfa33e78ab27/base.go:50 +0x12c

**Comment by caffix** [comment]
Please try v3.11.11 of Amass
