### ISSUE TITLE
AMASS 3.11.11 crash on enum -passive

### ISSUE THREAD

**Issue by gprime31** [OWASP/Amass#599]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x129c0ee]

works fine on 3.11.10

**Comment by tarunkant** [comment]
It crashes on 3.11.10 too

**Comment by gprime31** [comment]
not for me.
running go 1.16.2 linux/arm64

**Comment by tarunkant** [comment]
I am running: `go version go1.12.9 linux/amd64`

**Comment by tarunkant** [comment]
Tried with `go version go1.16.2 linux/amd64` too.

the same error

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xdc419e]
```

comes with both amass version: 3.11.10 and 3.11.11

**Comment by jaisharmafps** [comment]
Not working go1.16.2 linux/amd64

**Comment by tarunkant** [comment]
It seems the issue has been fixed in the latest release.
