### ISSUE TITLE
Out of memory on a 16gb VPS.

### ISSUE THREAD

**Issue by Rz-Rz** [OWASP/Amass#603]
The whole error message is 17 miles long
![2021-04-05 22_02_43-root@findomain-amass-s-2vcpu-4gb-nyc1-01_ ~_amass_linux_amd64](https://user-images.githubusercontent.com/52322219/113620514-b0a8af00-965a-11eb-9745-23834192fd0f.png)

**Comment by Rz-Rz** [comment]
Broken pipe error message

![2021-04-08 21_06_39-root@findomain-amass-s-2vcpu-4gb-nyc1-01_ ~_amass_linux_amd64](https://user-images.githubusercontent.com/52322219/114082883-96ffa580-98ae-11eb-96df-d67974ba1c95.png)

**Comment by Phoenix1112** [comment]
@Rz-Rz As someone who has been using vps and amass for a long time, I will give you some suggestions.

Create 10 gb of swap space. ( https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04 )

RAM may be 16 GB, but ram can also inflate your computer as there can be many things stored. Restart your computer or vps server before doing heavy work after long time use.

When I look at the picture above, the swap space will solve your job.

**Comment by caffix** [comment]
Try version v3.12.1

**Comment by anasbousselham** [comment]
I have the same problem : `runtime: out of memory` on my do vps, i have the latest ver.

**Comment by Sab0tag3d** [comment]
Usually increasing swap helps in those situations. Almost all VPS have a lot of space at SSD, so we could easily enlarge our memory and avoid such errors. Look at https://linuxize.com/post/create-a-linux-swap-file/ 

> I have the same problem : `runtime: out of memory` on my do vps, i have the latest ver.

**Comment by caffix** [comment]
I'm seeing the lowest memory consumption ever. Do you have an example to share that's creating the out of memory error?

**Comment by anasbousselham** [comment]
I just solved the problem, I have increased the size of my swap.
Thank you for help/

**Comment by najum98** [comment]
> I just solved the problem, I have increased the size of my swap.
> Thank you for help/

What's your RAM size and swap size now?
Facing same issue on my droplet
