### ISSUE TITLE
pipeline stage 6: Failed to extract a domain name from the FQDN

### ISSUE THREAD

**Issue by rafarachey** [OWASP/Amass#604]
Hi, i am new to this and I've been trying to brute force subs and i keep getting this error. Would appreciate any help. Thank you.

1 error occurred:
        * pipeline stage 6: Failed to extract a domain name from the FQDN

**Comment by caffix** [comment]
What version of the tool are you running? It would be easier to discuss this on the Discord server

**Comment by rafarachey** [comment]
Im running v3.11.13. 

Alright i'll drop a message on Discord. Thank You.

**Comment by caffix** [comment]
This issue should now be fixed in v3.12.0
