### ISSUE TITLE
Brute forcing cannot be performed without DNS resolution

### ISSUE THREAD

**Issue by m3hrajbhat** [OWASP/Amass#606]
When trying to run amass enum -passive  -d mydomain.com, i am getting this error 
**Brute forcing cannot be performed without DNS resolution**, 
added my config file also ~/.config/amass/config.ini,but error remains same...
tried with some additional commands like _amass enum -passive -norecursive -noalts -config /myconfigfile.ini -d mydomain.com_,still getting same issue..

**Comment by shelld3v** [comment]
Hi, you need to use the `active` mode for this situation

**Comment by m3hrajbhat** [comment]
Same error with `active` mode also

**Comment by caffix** [comment]
@m3hrajbhat Does your configuration file enable brute forcing? These troubleshooting questions are easier to solve on our Discord server

**Comment by m3hrajbhat** [comment]
> @m3hrajbhat Does your configuration file enable brute forcing? These troubleshooting questions are easier to solve on our Discord server

Solved Thanks buddy! Brute forcing was enbled in config file.

**Comment by mastercho** [comment]
> > @m3hrajbhat Does your configuration file enable brute forcing? These troubleshooting questions are easier to solve on our Discord server
> 
> Solved Thanks buddy! Brute forcing was enbled in config file.

please describe how you fix the issue
