### ISSUE TITLE
UPDATE: panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by muhammad-luay** [OWASP/Amass#613]
UPDATE: I also get the same error as previous reports.

I've also just installed amass and I get the error whenever I run any command

```panic: runtime error: integer divide by zero

goroutine 44 [running]:
github.com/caffix/resolve.(*baseResolver).calcNewRate(0xc000322000, 0xc008322180, 0xc, 0x10)
        /home/runner/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210420232254-1ad231ab11f3/base.go:368 +0x1aa
github.com/caffix/resolve.(*baseResolver).rateAdjustments(0xc000322000)
        /home/runner/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210420232254-1ad231ab11f3/base.go:340 +0x1e5
created by github.com/caffix/resolve.NewBaseResolver
        /home/runner/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210420232254-1ad231ab11f3/base.go:93 +0x7c7
```

the command i ran was  ```amass enum -d dji.com```

I'm using cmd

**Comment by caffix** [comment]
@muhammad-luay Can you please check which version of Amass you're running and share which installation method you used?

**Comment by muhammad-luay** [comment]
https://github.com/OWASP/Amass/releases/download/v3.12.2/amass_windows_amd64.zip

version 3.12.2

**Comment by caffix** [comment]
I'm looking into it and will have a fix release coming soon
