### ISSUE TITLE
geziyor changes to JoinURL break net/http

### ISSUE THREAD

**Issue by gcmurphy** [OWASP/Amass#621]
When trying to install amass from source today I hit this problem: 

```sh
github.com/OWASP/Amass/net/http
# github.com/OWASP/Amass/net/http
/root/go/src/github.com/OWASP/Amass/net/http/http.go:235:16: too many arguments in call to processURL
        have (*url.URL, error)
        want (string)
/root/go/src/github.com/OWASP/Amass/net/http/http.go:241:16: too many arguments in call to processURL
        have (*url.URL, error)
        want (string)
```

geziyor changed the signature of JoinURL in this [commit](https://github.com/geziyor/geziyor/commit/6a23efd1752d9ba90dd6d4ce691e94a0cd407a05).

Not sure if it's my bad or not..

**Comment by caffix** [comment]
Fixed this and did not remember the open issue
