### ISSUE TITLE
How to disable Alterations ?

### ISSUE THREAD

**Issue by w4cky** [OWASP/Amass#624]
Hi, i disable alternations in config /etc/amass.ini 
```

[alterations]
enabled = false

```

but amass show alternations is available

```
┌──(root💀)-[~/certstream-auto-tool]
└─# amass enum -config /etc/amass.ini -list
Data Source               | Type                    | Available
--------------------------------------------------------------------------------
AlienVault                  api                         *
Alterations                 alt                         *
```

**Comment by w4cky** [comment]
```
amass enum -exclude Alterations -config /etc/amass.ini -d blogmakijaz.pl -ipv4 -json /tmp/123 -src
[Alterations]     wwwitst.blogmakijaz.pl 23.202.231.167,23.217.138.108
[Alterations]     wwwlax-europewestengima.blogmakijaz.pl 23.202.231.167,23.217.138.108
[DNS]             mail.blogmakijaz.pl 51.38.142.47

```

lol :) why Alternations is exclude and show results Alterations records?

**Comment by c3101** [comment]
Having the same problem

Also some DNS servers seems to respond with a IP for all alterations, is there some way amass can detect this behaviour and not add those to the DB?

**Comment by shelld3v** [comment]
You can use the flag `-noalts` to disable Alterations

**Comment by shelld3v** [comment]
Please close this if my answer has resolved your problem

**Comment by c3101** [comment]
No it doesn't, no matter if you specify "-noalts" on the command line,  or set

[alterations]
enabled = false

in the config file, or both, it still runs alterations!

**Comment by shelld3v** [comment]
@c3101 Can you join the Amass Discord server and so we can discuss there?

**Comment by caffix** [comment]
> No it doesn't, no matter if you specify "-noalts" on the command line, or set
> 
> [alterations]
> enabled = false
> 
> in the config file, or both, it still runs alterations!

How have you verified this claim?

**Comment by c3101** [comment]
Not sure how, but I failed to recreate the problem the weekend, I can't explain.
Please close this as a result of my stupidity.
