### ISSUE TITLE
panic race condition when starting an enumeration scan

### ISSUE THREAD

**Issue by steers** [OWASP/Amass#627]
Just ran into a panic in Amass v3.12.3 caused by a segmentation fault.

The `ctx` struct field on `Enumeration` is used in a select statement in `(*enumSource).checkForData`, however this field is not set in `(*Enumeration).Start` until the statement after the `enumSource` is created.

https://github.com/OWASP/Amass/blob/v3.12.3/enum/enum.go#L96

In most cases, it seems that the context field is non-nil before it's used in `checkForData`, but it's definitely a race between goroutines.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xe0afa7]

goroutine 29580 [running]:
github.com/OWASP/Amass/v3/enum.(*enumSource).checkForData(0xc018f28000)
	/go/src/github.com/OWASP/Amass/v3/enum/input.go:269 +0x107
created by github.com/OWASP/Amass/v3/enum.newEnumSource
	/go/src/github.com/OWASP/Amass/v3/enum/input.go:63 +0x52b
```

**Comment by steers** [comment]
The PR didn't get linked to this issue, but with https://github.com/OWASP/Amass/pull/630 merged, this should be resolved.

**Comment by shelld3v** [comment]
Can we close this now?
