### ISSUE TITLE
Feature Request: Max Depth for Recursive Brute-forcing

### ISSUE THREAD

**Issue by caffix** [OWASP/Amass#633]
There has been a request to allows configurations to identify a maximum depth for recursive brute-forcing. 

Please let us know if this feature is of interest to other users so the project can prioritize the effort.

**Comment by Regala** [comment]
Definitely very useful so that the enum doesn't take weeks 😊

**Comment by manuel-sommer** [comment]
Hi, to my understanding, this PR https://github.com/OWASP/Amass/pull/739 fixes this issue, right?

**Comment by caffix** [comment]
Yes @manuel-sommer. I'll now close the issue. Thank you!
