### ISSUE TITLE
Failed to move the data into the in-memory graph database: No quads provided

### ISSUE THREAD

**Issue by is121018** [OWASP/Amass#635]
Hello,

I just updated amass to version v3.13.0 and I get the following error, when trying to list entries in the amass database. Is this a configuration issue?

![image](https://user-images.githubusercontent.com/7896159/121316746-ed6a7e00-c909-11eb-93ee-46a8045e2964.png)

Kind regards

**Comment by caffix** [comment]
That error message is typically displayed when the graph database could not be found. Did you save the db in another directory?

**Comment by is121018** [comment]
Nope, at least not intendedly. I tried deleting the .config/amas directory
in the home dir and reinstalled amass, yet I still get the same error
message.

Jeff Foley ***@***.***> schrieb am Mi., 9. Juni 2021, 17:20:

**Comment by caffix** [comment]
Let's take the troubleshooting to the Amass Discord server and close this issue

**Comment by is121018** [comment]
-

**Comment by nonsleepr** [comment]
Was the issue resolved? What caused it?

**Comment by caffix** [comment]
@nonsleepr It was a usage error. The information was not saved into the database, which is why it indicated that no quads were provided
