### ISSUE TITLE
amass enum seems to hang no matter what domain(s) i feed it

### ISSUE THREAD

**Issue by mikedesu** [OWASP/Amass#642]
somehow, enum worked for a while, but all of asudden it has been just...literally giving me no output whatsoever even with the `-v` flag turned on.

v3.13.2, ubuntu linux, built with `go get -v github.com/OWASP/Amass/v3/...`

i've also tested against the pre-built amd64 linux binary, same issue. i have several config files, but no matter if i'm trying passive or active, brute or non-brute, etc., all combinations are yielding the same result. 

attempting to ctrl-c yields sometimes a "No names were discovered during enumeration", but it continues to hang and never quits. no idea what is going on

**Comment by shelld3v** [comment]
It's hard to say what have you experienced was, but you can try removing `~/.config/amass` because it does cause a similar hanging bug

**Comment by mikedesu** [comment]
> It's hard to say what have you experienced was, but you can try removing `~/.config/amass` because it does cause a similar hanging bug

Removing that folder seems to have stopped the hanging. Thanks!

**Comment by shelld3v** [comment]
Close the issue?
