### ISSUE TITLE
Snap shows wrong version number (3.11.11) instead of snap package 3.13.4

### ISSUE THREAD

**Issue by kosli** [OWASP/Amass#686]
I just installed amass via snap on my Ubuntu/Linux System:

```
$ snap list amass
Name   Version  Rev  Tracking       Publisher  Notes
amass  v3.13.4  877  latest/stable  caffix     -
```

but when I start amass, it shows an older version:
```
$ /snap/bin/amass -version
v3.11.11
```

Was the wrong snap package distributed?

**Comment by RaduNico** [comment]
I am encountering this issue as well. Attempting to update using snap results in a success message, but the update appears to have no effect, only the older version remains present.

**Comment by caffix** [comment]
I see what's happening and am investigating a solution. In the mean time, please select an alternative method of installation

**Comment by caffix** [comment]
@kosli @RaduNico What architecture are you systems? Is this issue still causing a problem for you?
