### ISSUE TITLE
[Feature Request] Spaced results

### ISSUE THREAD

**Issue by s7x** [OWASP/Amass#69]
Hello there!

A little request/feature/change that could potentially help for copy/pasting of results.
When you enable the -ip flag, in the results you have something like that:
```
example.com,127.0.0.1,::1
```
And when you try to double click the domain or IP in your terminal, it highlights the whole line.
It would be great to have a separator like tab or space after the ',' (or even remove the ',' and separate with spaces) so when you double click it selects only the domain or IP and not the whole line.

I don't know if my explanations are clear enough. I know it's not crucial but that would be a little cool addition for ease of copy/paste.

Cheers and thanks for your work.

**Comment by caffix** [comment]
I agree with your suggestion, but it could require waiting a little while to implement it, since the change to the output format will probably require going up a major version. Perhaps between now and then, we can discuss other formatting improvements on the chat server.

**Comment by caffix** [comment]
The comma between names and the list of IP addresses has been replaced with a space. I imagine this should be easier to work with, correct? If so, please close the feature request. Thank you!

**Comment by s7x** [comment]
@caffix This is perfect. You are awesome! It indeed fixes the issues ;)
Cheers & long live Amass!
