### ISSUE TITLE
amass intel doesnt work with "-d" flag anymore

### ISSUE THREAD

**Issue by wellencamass** [OWASP/Amass#696]
running docker run caffix/amass intel -d google.ru gives me help page after the last update.

The -d is in the tutorials and user guide
Cant upload the screenshot, sorry. Just run it by urself

**Comment by shelld3v** [comment]
`docker run caffix/amass intel -d google.ru -whois`

**Comment by shelld3v** [comment]
@wellencamass Join [Amass discord](https://discord.gg/rtN8GMd) for Amass tool help and support

**Comment by Serizao** [comment]
Hello, i have the same issue like Amass run witout do anythings. Have you got a solution ?
