### ISSUE TITLE
Issue on Scripting Engine

### ISSUE THREAD

**Issue by DhiyaneshGeek** [OWASP/Amass#697]
Hi there

i tried to use these amass-tool with the script engine

using the following command i was not able to get the intended output 

Command Used:

amass enum -scripts /root/monitor/amass-tools/ -passive -src -d hackerone.com -include assetfinder,github-subdomains,findomain,subfinder

![image](https://user-images.githubusercontent.com/24750220/130364466-76d9b6f5-1759-4478-bfbd-e31488b01d36.png)

**Comment by dogeyoyo** [comment]
Hi @DhiyaneshGeek thanks for raising this issue. After going through conversations on Amass' discord server, I found out that removing `outputdir(ctx) .. ` from the scripts resolves this issue as it instructs amass to look for scripts inside `output` directory instead of directory provided through config/flag. Hope this helps.

**Comment by DhiyaneshGeek** [comment]
@dogeyoyo can you describe in details , i'm not able to get you :(

**Comment by dogeyoyo** [comment]
@DhiyaneshGeek Sure. 

See for example, in https://github.com/PatrikFehrenbach/amass-tools/blob/master/assetfinder.ads at line 6:
``` ada
    local cmd = outputdir(ctx) .. "assetfinder --subs-only " .. domain
```
`outputdir(ctx) ..` appends output directory path to `assetfinder` command so it becomes `<output-dir>/assetfinder` which doesn't exists in our setup, resulting in failure. After removing `outputdir(ctx) ..` command becomes `assetfinder ...` and amass searches for it globally and executes successfully.

**Comment by DhiyaneshGeek** [comment]
@dogeyoyo Thanks a lot for explaining it . now i'm able to solve this issue 

Cool !
