### ISSUE TITLE
panic: reflect: slice index out of range

### ISSUE THREAD

**Issue by leebaird** [OWASP/Amass#701]
Kali Linux rolling, fully patched.

Usage: amass enum -d target.com -ipv4 -noalts -norecursive

Results: returned 798 results then crashed. See below.

panic: reflect: slice index out of range [recovered]
        panic: reflect: slice index out of range

goroutine 2852 [running]:
encoding/json.(*encodeState).marshal.func1(0xc0039a0e20)
        /usr/lib/go-1.15/src/encoding/json/encode.go:326 +0x85
panic(0x105c480, 0x1bbbdd0)
        /usr/lib/go-1.15/src/runtime/panic.go:969 +0x1b9
reflect.Value.Index(0x10456e0, 0xc01f170c80, 0x197, 0x3, 0x1190100, 0xc00f67fdd0, 0x199)
        /usr/lib/go-1.15/src/reflect/value.go:962 +0x1f2
encoding/json.arrayEncoder.encode(0xc013ddc7e0, 0xc0072d4080, 0x10456e0, 0xc01f170c80, 0x197, 0x1050100)
        /usr/lib/go-1.15/src/encoding/json/encode.go:886 +0x8d
encoding/json.sliceEncoder.encode(0xc00ce6dd10, 0xc0072d4080, 0x10456e0, 0xc01f170c80, 0x197, 0x100)
        /usr/lib/go-1.15/src/encoding/json/encode.go:860 +0x8f
encoding/json.structEncoder.encode(0xc012e1a900, 0x5, 0x8, 0xc013ddc810, 0xc0072d4080, 0x11968a0, 0xc01f170c60, 0x199, 0x10a0100)
        /usr/lib/go-1.15/src/encoding/json/encode.go:759 +0x2ab
encoding/json.ptrEncoder.encode(0xc013ddc840, 0xc0072d4080, 0x10b59c0, 0xc01f170c60, 0x16, 0x10b0100)
        /usr/lib/go-1.15/src/encoding/json/encode.go:915 +0x125
encoding/json.(*encodeState).reflectValue(0xc0072d4080, 0x10b59c0, 0xc01f170c60, 0x16, 0xc0039a0100)
        /usr/lib/go-1.15/src/encoding/json/encode.go:358 +0x82
encoding/json.(*encodeState).marshal(0xc0072d4080, 0x10b59c0, 0xc01f170c60, 0xc010200100, 0x0, 0x0)
        /usr/lib/go-1.15/src/encoding/json/encode.go:330 +0xf4
encoding/json.(*Encoder).Encode(0xc0039a0f40, 0x10b59c0, 0xc01f170c60, 0x0, 0x0)
        /usr/lib/go-1.15/src/encoding/json/stream.go:206 +0x8b
main.saveJSONOutput(0xc00036f380, 0xc000224200, 0xc01020ec00, 0xc00cea68c0)
        /build/amass-9ca4iE/amass-3.13.4/cmd/amass/enum.go:493 +0x2f6
created by main.runEnumCommand
        /build/amass-9ca4iE/amass-3.13.4/cmd/amass/enum.go:214 +0x99f

**Comment by shelld3v** [comment]
I'm not sure, but can you try `amass enum -d target.com -ipv4 -noalts -brute -norecursive`?

**Comment by leebaird** [comment]
This is no longer an issue.
