### ISSUE TITLE
(Maybe?) useful documentation for authoritative sources / APIs

### ISSUE THREAD

**Issue by mzpqnxow** [OWASP/Amass#704]
Hey there @caffix, I haven't been on the Discord in a long time but was working on something recently to interact with the CSC DomainManager API to query domains and resource records. I recall a ways back there was some discussion about adding things like CloudFlare, MarkMonitor, CSC, and other commercial APIs that enterprises might make use of to manage their traffic or DNS. I don't recall how many were actually added but I thought [this link](https://github.com/StackExchange/dnscontrol/tree/master/providers) might be helpful both in helping to enumerate various sources that may be worth enumerating as well as providing some brief examples of how to interact with each

I found it funny that the above linked project is the only thing I could find on all of GitHub (or the Internet, for that matter) that actually consumes the CSC DomainManager API... this is what made me think to send it over. It seems a bit obscure, but some enterprises probably have quite a bit of data in it

If I have some time I will try to join back up on Discord and see if I can add CSC to Amass once I've finished my current projects

You can close this issue once you read it, think of it as a very roundabout way of sending you a PM :)

**Comment by caffix** [comment]
Thank you very much, @mzpqnxow!
