### ISSUE TITLE
The GoogleCT source is not working properly

### ISSUE THREAD

**Issue by Isaac21e** [OWASP/Amass#707]
When running subdomain enumeration on slack.com (for example) many subdomains that have certificates are missing.
```console
foo@bar:~$ amass enum -passive -src -include GoogleCT -d slack.com
[GoogleCT]        dev9.slack.com
[GoogleCT]        q11.slack.com
[GoogleCT]        dev5.slack.com
[GoogleCT]        dev2.slack.com
[GoogleCT]        dev1.slack.com
[DNS]             slack.com
[GoogleCT]        qa11.slack.com
[GoogleCT]        dev.slack.com
[GoogleCT]        dev10.slack.com
[GoogleCT]        14-04-09.slack.com
[GoogleCT]        xmpp.slack.com
[GoogleCT]        15-03-02-dev3.slack.com
[GoogleCT]        dev4.slack.com
[GoogleCT]        dev6.slack.com
[GoogleCT]        assets.slack.com
[GoogleCT]        15-04-30-dev7.slack.com
[GoogleCT]        14-12-23-dev1.slack.com
[GoogleCT]        auth.slack.com
[GoogleCT]        15-02-04-dev2.slack.com
[GoogleCT]        dev11.slack.com
[GoogleCT]        staging.slack.com
[GoogleCT]        14-47.staging.slack.com
```
The above shows subdomains with certificates, but a simple query to crt.sh shows that there are much more:

![image](https://user-images.githubusercontent.com/35118577/135808247-4f2edf8c-a50b-4f8c-81bf-f8d6ce52d011.png)

**Comment by caffix** [comment]
Google CT does not always have the same information as crt.sh

**Comment by Isaac21e** [comment]
Maybe, but there are a lot missing.
For example, you can find 2015-06-25.dev1.slack.com in google certificates (url below) but amass won't return it.
I got to this because I saw that subdomains that GoogleCT (via amass) found in the past are missing, although using the exact same command.

You can find it here: 
https://transparencyreport.google.com/https/certificates?hl=en&cert_search_auth=&cert_search_cert=p:c2xhY2suY29tOnRydWU6ZmFsc2U6OkNBb1FBUT09&cert_search=include_subdomains:true;domain:slack.com&lu=cert_search_cert

**Comment by caffix** [comment]
@Isaac21e Are you still referring to the integration with Google Certificate Transparency, or potentially another aspect of Amass? Can you please bring this to the `troubleshooting` channel of our Discord server?
