### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by knowthetech** [OWASP/Amass#726]
panic: runtime error: integer divide by zero

goroutine 479708 [running]:
github.com/caffix/resolve.(*resolverPool).nextResolver(0xc004551290, 0x1bbb288, 0xc0000c8008, 0x0, 0x450cc5)
	/root/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:125 +0x439
github.com/caffix/resolve.(*resolverPool).Query(0xc004551290, 0x1bbb288, 0xc0000c8008, 0xc0045507e0, 0x3, 0x1a8c7d8, 0xc0001e63f0, 0x8, 0xc0001e63f0)
	/root/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:207 +0x165
github.com/OWASP/Amass/v3/datasrcs.(*RADb).OnStart(0xc0001e63f0, 0x1a8c701, 0xc0001e63f0)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/datasrcs/radb.go:59 +0xb1
github.com/caffix/service.(*BaseService).Start(0xc0001e63f0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/caffix/service@v0.0.0-20210920205156-38bde8eb0503/base.go:52 +0x156
github.com/OWASP/Amass/v3/systems.(*LocalSystem).AddAndStart(0xc00069b0e0, 0x1bc9db0, 0xc0001e63f0, 0x3241534c202c296e, 0x5428204e4952412d)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:108 +0x35
github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources.func1(0x1bc9db0, 0xc0001e63f0, 0xc0045dd020)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:126 +0x3e
created by github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:131 +0x105
panic: runtime error: integer divide by zero

goroutine 479699 [running]:
github.com/caffix/resolve.(*resolverPool).nextResolver(0xc001f843f0, 0x1bbb288, 0xc000130008, 0x0, 0x450cc5)
	/root/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:125 +0x439
github.com/caffix/resolve.(*resolverPool).Query(0xc001f843f0, 0x1bbb288, 0xc000130008, 0xc0004bc000, 0x3, 0x1a8c7d8, 0xc0001ce3f0, 0x8, 0xc0001ce3f0)
	/root/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:207 +0x165
github.com/OWASP/Amass/v3/datasrcs.(*RADb).OnStart(0xc0001ce3f0, 0x1a8c701, 0xc0001ce3f0)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/datasrcs/radb.go:59 +0xb1
github.com/caffix/service.(*BaseService).Start(0xc0001ce3f0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/caffix/service@v0.0.0-20210920205156-38bde8eb0503/base.go:52 +0x156
github.com/OWASP/Amass/v3/systems.(*LocalSystem).AddAndStart(0xc000633f20, 0x1bc9db0, 0xc0001ce3f0, 0x828e54a816324b9, 0x94ad06a02d26932b)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:108 +0x35
github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources.func1(0x1bc9db0, 0xc0001ce3f0, 0xc005613680)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:126 +0x3e
created by github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:131 +0x105
panic: runtime error: integer divide by zero

goroutine 479727 [running]:
github.com/caffix/resolve.(*resolverPool).nextResolver(0xc004812090, 0x1bbb288, 0xc000128008, 0x0, 0x450cc5)
	/root/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:125 +0x439
github.com/caffix/resolve.(*resolverPool).Query(0xc004812090, 0x1bbb288, 0xc000128008, 0xc004442000, 0x3, 0x1a8c7d8, 0xc0048123f0, 0x8, 0xc0048123f0)
	/root/go/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:207 +0x165
github.com/OWASP/Amass/v3/datasrcs.(*RADb).OnStart(0xc0048123f0, 0x1a8c701, 0xc0048123f0)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/datasrcs/radb.go:59 +0xb1
github.com/caffix/service.(*BaseService).Start(0xc0048123f0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/caffix/service@v0.0.0-20210920205156-38bde8eb0503/base.go:52 +0x156
github.com/OWASP/Amass/v3/systems.(*LocalSystem).AddAndStart(0xc0002a5b00, 0x1bc9db0, 0xc0048123f0, 0xc0132444b0, 0xc00bc19300)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:108 +0x35
github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources.func1(0x1bc9db0, 0xc0048123f0, 0xc00286a5a0)
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:126 +0x3e
created by github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources
	/root/go/pkg/mod/github.com/!o!w!a!s!p/!amass/v3@v3.14.0/systems/local.go:131 +0x105

**Comment by caffix** [comment]
I believe v3.14.2 and v3.14.3 fixed this issue
