### ISSUE TITLE
Help!!!Unable to run amass enum -list

### ISSUE THREAD

**Issue by AlienFukro** [OWASP/Amass#737]
amass version v3.14.1
OS Parrot
Go version go1.17.2

When I run amass enum -list, I get the following error

===========================================================
panic: runtime error: integer divide by zero

goroutine 482067 [running]:
github.com/caffix/resolve.(*resolverPool).nextResolver(0xc0048d9b00, {0x19ec728, 0xc0000400e0})
	/build/amass-pCL2NR/amass-3.14.1/build/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:125 +0x395
github.com/caffix/resolve.(*resolverPool).Query(0xc0048d9b00, {0x19ec728, 0xc0000400e0}, 0xc00195b6f8, 0x3, 0x18b9da8)
	/build/amass-pCL2NR/amass-3.14.1/build/pkg/mod/github.com/caffix/resolve@v0.0.0-20210920205119-7c35ff3e3771/pool.go:207 +0x1ff
github.com/OWASP/Amass/v3/datasrcs.(*RADb).OnStart(0xc0002fc360)
	/build/amass-pCL2NR/amass-3.14.1/datasrcs/radb.go:59 +0x76
github.com/caffix/service.(*BaseService).Start(0xc0002fc360)
	/build/amass-pCL2NR/amass-3.14.1/build/pkg/mod/github.com/caffix/service@v0.0.0-20210920205156-38bde8eb0503/base.go:52 +0x131
github.com/OWASP/Amass/v3/systems.(*LocalSystem).AddAndStart(0xc004c7a000, {0x1a02d48, 0xc0002fc360})
	/build/amass-pCL2NR/amass-3.14.1/systems/local.go:108 +0x2c
github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources.func1({0x1a02d48, 0xc0002fc360}, 0xc0139f0340)
	/build/amass-pCL2NR/amass-3.14.1/systems/local.go:126 +0x3b
created by github.com/OWASP/Amass/v3/systems.(*LocalSystem).SetDataSources
	/build/amass-pCL2NR/amass-3.14.1/systems/local.go:131 +0x25d

===========================================================

**Comment by caffix** [comment]
I recommend you update to version 3.14.2
