### ISSUE TITLE
How to disable all data sources during active mode?

### ISSUE THREAD

**Issue by dogeyoyo** [OWASP/Amass#745]
Hi there,
I am trying to disable all data sources during active mode by adding them to `[data_sources.disabled]` list and process only supplied (already found) subdomains, but amass still issues requests to these data sources.

* My `config.ini` looks something like this:

```
...
[data_sources]

# disable data sources
[data_sources.disabled]
data_source = 360PassiveDNS
data_source = AbuseIPDB
data_source = Ahrefs
data_source = AlienVault
data_source = AnubisDB
...
```

* Log file shows amass still contacting data sources:
```
* 23:05:29.755919 Robtex: ip_info request to service failed: 429: 429 Too Many Requests
23:05:34.756779 Robtex: ip_info request to service failed: 429: 429 Too Many Requests
23:05:39.757657 Mnemonic: vertical request to service failed: Get "https://api.mnemonic.no/pdns/v3/clover.network?limit=1000": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
23:05:44.758013 Robtex: ip_info request to service failed: 429: 429 Too Many Requests
23:05:49.759261 Robtex: ip_info request to service failed: 429: 429 Too Many Requests
23:05:59.760723 Robtex: ip_info request to service failed: 429: 429 Too Many Requests
23:06:04.761181 Searx: scrape: 429: 429 Too Many Requests
```

Thanks in advance.

**Comment by caffix** [comment]
`amass enum -include bgpview -active -d <domains> -nf <names file path>` will only use BGPView for infrastructure information and start with the file for names that are in scope identified by the domains provided. Please come to our Discord server for future usage questions like this one
