### ISSUE TITLE
[Question] Check working APIs credentials

### ISSUE THREAD

**Issue by Sim4n6** [OWASP/Amass#749]
Hi, I'm a newcomer. I was wondering if there is away to check the APIs that are working ? meaning a sub-command that verify working api credentials first, please ?

**Comment by caffix** [comment]
Currently, no sub-command or flag exists to test that API credentials are valid and/or have available credits. You can check the JSON output to see which data sources discovered subdomain names during the enumeration. In the future, please bring your questions to our Discord server
