### ISSUE TITLE
[add support] dnsrepo.noc.org

### ISSUE THREAD

**Issue by dogasantos** [OWASP/Amass#751]
Hey guys, would that be possible to add support for https://dnsrepo.noc.org ? 
They offer an api for dns queries with very good value
Thanks

**Comment by caffix** [comment]
We can certainly make use of this as a data source. If you want to leverage API access, Daniel and/or Tony will need to give Amass an account for testing

**Comment by caffix** [comment]
NOC was quite helpful with the integration and DNS repository database can be used as a data source with Amass
