### ISSUE TITLE
go get: installing executables with 'go get' in module mode is deprecated

### ISSUE THREAD

**Issue by GreenPoint-InfoSec** [OWASP/Amass#759]
One of the go get requests fails during installation:

> go: downloading github.com/spf13/pflag v1.0.5
> go: downloading github.com/inconshreveable/mousetrap v1.0.0
> go get: installing executables with 'go get' in module mode is deprecated.
> Use 'go install pkg@version' instead.
> For more information, see https://golang.org/doc/go-get-install-deprecation or run 'go help get' or 'go help install'.
> go: downloading github.com/projectdiscovery/subfinder/v2 v2.4.9

I am not sure where package it is trying to get at this stage. I have included the before and after requests to help identify it.

**Comment by Forchapeatl** [comment]
work around on Linux environments would be to run the following commands
`sudo apt update`
`sudo apt install snapd`
`sudo snap install amass`
These above commands worked for me.

**Comment by caffix** [comment]
@GreenPoint-InfoSec The output you shared came from building a different tool

**Comment by Forchapeatl** [comment]
> @GreenPoint-InfoSec The output you shared came from building a different tool

Please have a look at this file [go.sum](https://github.com/OWASP/Amass/blob/master/go.sum)
![image](https://user-images.githubusercontent.com/24577149/149282734-ce750472-d44c-4aab-a81b-2647c383fb07.png)
