### ISSUE TITLE
flag provided but not defined: -visjs

### ISSUE THREAD

**Issue by Obad94** [OWASP/Amass#761]
I'm running the following command `amass viz -visjs -d example.com` and it is providing me an error: 
**flag provided but not defined: -visjs**

Amass version: v3.15.2.

I also found that there is no visjs flag in viz.go file.
How to include the visjs flag in Amass.

**Comment by mariuskimmina** [comment]
There is indeed no `visjs` flag, I also found no mention of such a flag anywhere in the docs - why do you expect such a flag to exist and what should it do? what's the issue you are facing or what are you trying to achieve?

**Comment by caffix** [comment]
The project once supported exporting a `vis.js` visualization, but its performance is lower than D3 and the feature was removed quite a while ago
