### ISSUE TITLE
Enable active recon methods?

### ISSUE THREAD

**Issue by shadowzoom** [OWASP/Amass#77]
Does this option is checking if domain alive via port? If command will be amass -active -d example.com net -p 443, amass will check if example.com alive on 443 port, am i right?

**Comment by caffix** [comment]
The net sub-command functionalities have been moved to the amass.netdomains command in the tool suite. Also, so far, Amass has never performed port scanning as part of the enumerations

**Comment by caffix** [comment]
When you use '-active' and specify ports, those ports will be used to pull certificates from resolved DNS names in an attempt to discover additional names

**Comment by analyst666** [comment]
Thanks
