### ISSUE TITLE
 -min-for-recursive 1 not working.

### ISSUE THREAD

**Issue by panchocosil** [OWASP/Amass#78]
I create a subdomains with `g.f.e.d.c.b.a.cerobug.com` (my domain) where all the letters `g.f.e.d.c.b.a` have a record A.

Then I create a abc.txt wordlist with:
```
g
f
e
d
c
b
a
```

Command:
```
amass -d cerobug.com -w abc.txt -brute -src -min-for-recursive 1
```

Result:
```
[CertSpotter]     www.cerobug.com
[Brute Forcing]   a.cerobug.com
[VirusTotal]      e.d.c.b.a.cerobug.com
[VirusTotal]      mail.cerobug.com
[VirusTotal]      g.f.e.d.c.b.a.cerobug.com
[VirusTotal]      webmail.cerobug.com
[VirusTotal]      ftp.cerobug.com
[Alterations]     www1.cerobug.com
[VirusTotal]      c.b.a.cerobug.com
[VirusTotal]      f.e.d.c.b.a.cerobug.com
[Alterations]     www2.cerobug.com
[Alterations]     mail2.cerobug.com
[VirusTotal]      b.a.cerobug.com
[Alterations]     mail2-6.cerobug.com
```

Problem:
Not all subdomain are been found via brute forcing. For example `d.c.b.a.cerobug.com` is not found by Brute Forcing.

Version: `amass version 2.8.7`

**Comment by caffix** [comment]
From your example, and from discussing this with you via chat, the project needs to allow -min-for-recursive 0 to be specified. This would cause brute forcing to be performed on every name discovered.

**Comment by caffix** [comment]
Thank you for the excellent feedback!
