### ISSUE TITLE
Do not query public-dns.info by default without user-interaction

### ISSUE THREAD

**Issue by xerxoria** [OWASP/Amass#781]
At the moment amass downloads https://public-dns.info/nameservers-all.csv every time it is run - that is even if called without arguments (called in init of [resolvers.go](https://github.com/OWASP/Amass/blob/24a7a76861a7b79e69b8c431903b0890831d9707/config/resolvers.go#L54)).

While I would even argue for removing `DefaultBaselineResolvers` altogether and rely solely on `config.ini`, I definitely would at least appreciate some kind of control over this behaviour and most certainly did not expect amass to initiate any connection unless explicitly asked for.

**Comment by caffix** [comment]
Most users prefer that the default configuration yield the best performance and result set. How would you propose we satisfy everyone and are you interested in contributing the changes?
