### ISSUE TITLE
[feature suggestion] Please print more info about the status/progress/stats of the DNS search

### ISSUE THREAD

**Issue by yurivict** [OWASP/Amass#79]
For one large organization's network it consumes a significant amount of time and memory:
```
  PID USERNAME       THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
36184 yuri            25  42    0  2420M  2318M uwait   1 116.9H 674.43% amass
 ```
It runs for almost a day now, without any indication when it might be done, but it still prints some new names once in a while.

Please consider printing some more info about how many items ```amass``` went through, how many are in its todo list, etc. What takes so much time in memory? Also please print how many bytes were sent/received over the lifetime of the process.

Otherwise, the user has no idea how much longer there is to wait: a week, a month? (I hope not.)

amass-2.8.6

**Comment by caffix** [comment]
Version 2.9.2 has been released, and it prints additional information for users that will help them estimate how much time is left until completion of the enumeration. Thank you!

**Comment by yurivict** [comment]
Thanks!
