### ISSUE TITLE
Amass enum passive has no output in 46 minutes for a domain with 20k subdomains when db is not empty for that domain

### ISSUE THREAD

**Issue by rew1nter** [OWASP/Amass#807]
A fresh installation of amass latest from snap or src run with `amass enum -d corp.com -v -passive` finishes finding 20k subdomains within 5 minutes. But while the   same command is run again, it gets stuck forever with no subdomain output at all. 
P.S I'm using amass in a VPS.

**Comment by nikhen** [comment]
Can you *ping google.com* in a separate tab? It could be blocking on part of the ISP.
