### ISSUE TITLE
DB issue!

### ISSUE THREAD

**Issue by blackcodersec** [OWASP/Amass#811]
Hello,

My command was
`amass enum -passive -d domain.com -nolocaldb -norecursive -timeout 5 -nocolor -o amass.txt`

but output here. result save amass db. that means `-nolocaldb` not working?
![image](https://user-images.githubusercontent.com/72689232/164944703-5b379a19-d965-47db-9ab4-3ae2d90e206f.png)

**Comment by caffix** [comment]
The help information shows that the feature has been discontinued
