### ISSUE TITLE
AMASS Intel Does not Work

### ISSUE THREAD

**Issue by Sword-Saint-0** [OWASP/Amass#843]
I cannot get the AMASS intel command to work and there is no error output at all, it acts as if I've never typed anything:

root@kali:/usr/share/amass# amass intel -d facebook.com -whois
root@kali:/usr/share/amass# 

Any idea how to fix this?

**Comment by mzpqnxow** [comment]
> I cannot get the AMASS intel command to work and there is no error output at all, it acts as if I've never typed anything:
> 
> 
> 
> root@kali:/usr/share/amass# amass intel -d facebook.com -whois
> 
> root@kali:/usr/share/amass# 
> 
> 
> 
> 
> 
> Any idea how to fix this?

General tip, if you're using amass from the Kali package, I would recommend using the latest master first to make sure you see the same behavior

**Comment by caffix** [comment]
The reverse whois functionality often does not provide results if you do not have access to a paid data source
