### ISSUE TITLE
AMASS intel --asn is not working

### ISSUE THREAD

**Issue by Th3BlackHol3** [OWASP/Amass#844]
Amass is not responding with "$ **amass intel --asn** (Numbers)", when I start scanning it takes 3 to 5 minutes but does not give any error or results.

Version: AMASS v3.14.1
OS: Parrot OS 5.0 (Electro Ara)

**Comment by mo7amed-yasser** [comment]
Amass is not responding with "$ amass intel -d domin ", when I start scanning it takes 3 to 5 minutes but does not give any error or results

**Comment by t00fi** [comment]
same issue
