### ISSUE TITLE
-timeout option: exit after finishing the task

### ISSUE THREAD

**Issue by knassar702** [OWASP/Amass#849]
Hello Team, I'm trying to use the timeout option to set a time limit for my amass brute-forcing process so in this case, Amass doesn't exit after finding the domains it keeps running until the timeout value in minutes ends like this example here

```bash
$ amass enum -d vulnweb.com -timeout 15 -brute 
```

**Comment by caffix** [comment]
This usage question would be best handled in the Amass Discord server: https://discord.gg/TMMyYtBMTR

**Comment by knassar702** [comment]
hey @caffix, thanks for your response but I'm not asking about "How can I do X in Amass" 
I've opened this issue to make some changes in this option instead of waiting 15 min we can make it exit if the task is finished without waiting all this time in every scan

I hope I made my point clear

best regards 
@knassar702

**Comment by caffix** [comment]
Amass does not wait for the timeout to expire. It simply uses the the timeout value to create a Go context that will expire, but the enumeration never waits for this to happen. Your instance of the tool is simply making use of the time available
