### ISSUE TITLE
Unable to find config.ini file on Mac!

### ISSUE THREAD

**Issue by d0nest** [OWASP/Amass#856]
Apples-MacBook-Air:~ macbookair$ $HOME/Library/Application\ Support/amass/config.ini
-bash: /Users/macbookair/Library/Application Support/amass/config.ini: No such file or directory

it says no such file or directory!

**Comment by caffix** [comment]
https://github.com/OWASP/Amass/blob/master/examples/config.ini

Please bring these usage questions to our Discord server: https://discord.gg/rtN8GMd
