### ISSUE TITLE
Internet disconnected while using amass in kali

### ISSUE THREAD

**Issue by shivam-singh-official** [OWASP/Amass#859]
Every time i tried to run amass command in kali linux it got disconnected from the internet is there any solution for this problem ??

**Comment by shivam-singh-official** [comment]
Now I know why got disconnected. If we try to run virtual box in NAT network then amass got disconnected from the internet So use virtual box in bridge network mode.

**Comment by duraki** [comment]
It's a usual issue. Many issues reported but still not resolved
