### ISSUE TITLE
Windows update

### ISSUE THREAD

**Issue by shadowzoom** [OWASP/Amass#87]
Hi there! Can you please  upload fresh windows release? Last windows version was 2.7.5
Thanks

**Comment by caffix** [comment]
Windows 64-bit binaries for version 2.8.8 of the tool suite has now been added to the latest release. Also, we are working on updating the CI/CD process to automatically produce updated binaries with every tag

**Comment by shadowzoom** [comment]
Huge thanks mate! :)
