### ISSUE TITLE
Docker image for amass:v3.20.0 is missing

### ISSUE THREAD

**Issue by Ilyesbdlala** [OWASP/Amass#880]
It seems [caffix/amass:v3.20.0](https://hub.docker.com/r/caffix/amass/tags) docker image is missing. Probably due to the [publish pipeline failing](https://github.com/OWASP/Amass/actions/runs/3110473059). 
I see you already made a fix to resolve the issue [here](https://github.com/OWASP/Amass/commit/0b865ebb8ef57b953d0782c6855eaba1b8692663).
Are there any plans to publish the docker image in the current amass version, or are you waiting for the next version bump to do so?

Thanks for your contributions :)

**Comment by rseedorff** [comment]
@caffix Have you noticed this? Do you need a helping hand on this?

**Comment by caffix** [comment]
@rseedorff we can always use more contributors. It would be great to get the Dockerfile in tip-top shape for the next release

**Comment by rseedorff** [comment]
Fixed within the latest release: https://github.com/OWASP/Amass/commit/857520ee808b7d5473cf8360d959b7f87b7ce8dd
