### ISSUE TITLE
Very long 'enum' when start on raspberry pi 4 (arm64, 8gb memory)

### ISSUE THREAD

**Issue by foozzi** [OWASP/Amass#882]
OS: Raspbian stable
amass: latest
go: 1.19.2

`amass enum -passive -d hackerone.com`

Execution time on my fedora 36 (main PC):
```
real    0m40,594s
user    0m45,939s
sys     0m1,617s
```

Execution time on my raspberry pi 4 (arm64, 8gb memory, ssd):

```
real    3m29.641s
user    6m46.717s
sys     0m27.121s
```
Why is this happening? And how to improve efficiency?

**Comment by caffix** [comment]
I have never tested it on a Raspberry Pi before. Feel free to share your findings on our Discord server
