### ISSUE TITLE
Missing data sources in config.ini

### ISSUE THREAD

**Issue by ghost** [OWASP/Amass#892]
The following data sources are listed in the README but aren't present in the default configuration file, and some of them are configurable APIs:

AnubisDB
Greynoise
Maltiverse
Mnemonic
Pulsedive
Searchcode
SonarSearch [DOWN]
Spyse [DOWN]
ThreatCrowd [DOWN]
ThreatMiner
Crtsh
Digitorus
GoogleCT
BGPTools
BGPView
RADb
Robtex
ShadowServer
AbuseIPDB
Ask
Baidu
Bing
DNSDumpster
DNSHistory
DNSSpy
DuckDuckGo
Gists
Google
HackerOne
HyperStat
PKey
RapidDNS
Riddler
Searx
Yahoo
ArchiveIt
Arquivo
CommonCrawl
HAW
UKWebArchive
Wayback
AskDNS
SpyOnWeb

**Comment by fuzzyami** [comment]
Hello! 
is this a bug? a feature? are these sources expected back? were they removed intentionally?

**Comment by caffix** [comment]
@fuzzyami most of these data sources have not been removed.

@ghost not data source integrations have support for APIs requiring credentials
