### ISSUE TITLE
Question about min-for-recursive

### ISSUE THREAD

**Issue by shadowzoom** [OWASP/Amass#90]
English is not my main language so i lil bit understand what this options do. I've ofcourse read "Number of subdomain names required for recursive brute forcing to begin" but damn, i can't understand that :(
Just correct me please:
If amass -brute -min-for-recursive 3 -d example.com
Amass will start find subdomains bigger that 3 characters, right? Like aaa.example.com bbb.example.com
Or it will find only subdomain only with 3 subdomains like 1.2.3.example.com 4.5.6.example.com

**Comment by caffix** [comment]
Brute forcing will begin on example.com right away. Recursive brute forcing takes place on additional labels, such as the cs.example.com or careers.example.com subdomain names. What if you do not want to start recursive brute forcing on every new subdomain name you discover? What if you would like some evidence that careers.example.com is worth brute forcing?

If you specify the '-min-for-recursive 2' flag, two labals need to show up on careers.example.com before recursive brute forcing will begin, such as the www.careers.example.com and support.careers.example.com subdomain names. The flag allows you to control when recursive brute forcing will be triggered.

**Comment by ertygiq** [comment]
@caffix Thank you for the explanation. To clarify, when you say "labels need to show up on careers.example.com before recursive brute forcing will begin", do you mean that the labels need to show up by other data sources (e.g., Bing)?
