### ISSUE TITLE
I have installed amass with go but I dont know how can I configure the api keys on config.ini

### ISSUE THREAD

**Issue by codefaztaz** [OWASP/Amass#900]
I have installed amass with go but I dont know how can I configure the api keys

**Comment by caffix** [comment]
Build your config file from the [example](https://github.com/OWASP/Amass/blob/master/examples/config.ini) and provide it to the tool using the `-config` flag. The link above is also provided in the tool help information

**Comment by VineetSadawari** [comment]
The Path here says 404 ; https://github.com/OWASP/Amass/blob/master/examples/config.ini
