### ISSUE TITLE
No names were discovered on every host

### ISSUE THREAD

**Issue by c0rvax** [OWASP/Amass#92]
Hi!

### Description

I am launching the program like this `amass -d uber.com`. I get `No names were discovered`. However, launching `amass -oA /tmp/uber -d uber.com` writes a file with [events](https://pastebin.com/GC2w8CyV). Although other files are all empty. I am pretty sure there is no internet issue on my side, as the events generated do contain some of the resolved hostnames along with respective ip addresses

### Probable problem (not sure if this is the key, but might be of interest)

I have traced some of the source code and found that the code which is responsible for putting data to the output it is here https://github.com/OWASP/Amass/blob/master/amass/graph.go#L547. The loop here https://github.com/OWASP/Amass/blob/master/amass/graph.go#L559 seems to be not appending any data from the Graph, which might be actually the key issue.

### Environment

I have version 2.9.0
`Linux vault 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux`
The tools is installed on the system using `go install` as shown in the manual

**Comment by c0rvax** [comment]
Update: https://github.com/OWASP/Amass/blob/master/amass/graph.go#L644 this code seems to be always returning 0 and exiting the function

**Comment by c0rvax** [comment]
I believe this issue is connected to https://github.com/caffix/amass/issues/34, and the fix there was just to wait for the site to come online, but is there any chance to not rely on that website in case it goes down?

May be it would be possive to return dummy_ASN when there is no response from the server?

**Comment by fraabye** [comment]
I am experiencing the same error with 2.9.0 on a fully patched Kali rolling.  It appears to be working and runtimes are as expected with known domains but no results are returned.

**Comment by fraabye** [comment]
> I have figured out that there are very slow requests on https://github.com/OWASP/Amass/blob/master/amass/network.go#L251
> 
> Well, looks that asn.shadowserver.org is not resolved or 43 port on that host is kicking me out

It looks as if there is no current dns records for this host at all.

**Comment by c0rvax** [comment]
Correct, the resolving of `asn.shadowserver.org` stopped for me

Meanwhile you can launch the tool with `-do` options and parse the data manually

**Comment by caffix** [comment]
As you determined, a network service (asn.shadowserver.org) that Amass relies on went down temporarily. It appears to be back online now. We will be exploring ways to prevent this problem in the future

**Comment by caffix** [comment]
An additional data source has been integrated into the network infrastructure lookups to address this problem. This is only a start though, and I intend on improving this portion of the architecture over time. Since the situation has been solved for now, I'll be closing this issue. Thank you for the useful feedback!
