### ISSUE TITLE
Dockerfile fails to build due to WORKDIR name

### ISSUE THREAD

**Issue by attackercan** [OWASP/Amass#95]
Docker fails to build an image from local Dockerfile.

Steps to reproduce:

1. Download a single file `Dockerfile` from the Github project root to an empty folder on your system.
2. Run `docker build .`
3. Observe an error from docker:

`package github.com/OWASP/Amass/...: /go/src/github.com/OWASP/Amass exists but /go/src/github.com/OWASP/Amass/.git does not - stale checkout?`
`The command '/bin/sh -c apk --no-cache add git   && go get -u github.com/OWASP/Amass/...' returned a non-zero code: 1`

As I can see it, this happens because `go get -u github.com/OWASP/Amass/...` is trying to first "sync" local and remote repositories, instead of simply downloading it. This happens since the name of local folder in golang docker is the same as the name of target remote repo. It is trying to sync using git, and hence fails while searching for ".git" folder in the remote repo.

See, Dockerfile contains:

`WORKDIR /go/src/github.com/OWASP/Amass` <- local folder is treated by go as an empty repo with the name Amass
`go get -f -u github.com/OWASP/Amass/...` <- remote repo name is also Amass

Changing `WORKDIR` final folder name to any other name, such as `WORKDIR /go/src/github.com/OWASP/Amass123`, will allow docker to build both using local Dockerfile, and the way [described on your How-to page](https://github.com/attackercan/Amass#using-docker)).

I can't see a reason of naming a WORKDIR folder **inside a docker** like that, since that intermediate docker is only used for compiling go sources. Hence I suggest to change WORKDIR folder name to anything that looks good for you.

You can play with the commit I made in my fork: https://github.com/attackercan/Amass/commit/4a6febcd7f6c0bd7517cf6e9750bc32a5c0dbf31

**Comment by attackercan** [comment]
As additional note, I also dont see any need for `COPY . .` command. 

Nothing should be really COPY'ed inside the *build* container, since the sources will be anyway downloaded from github repo by `go get`. 

I understand that `/go/src/github.com/OWASP/Amass` is a path to your development source code branch, and you left it here because it was convenient to develop Dockerfile, but it seems that it is not necessary and may be deleted.

**Comment by fork-while-fork** [comment]
The `Dockerfile` is written assuming one of two conditions:

1. You clone the repo and run the build within the repo directory:
```
git clone https://github.com/OWASP/Amass
cd Amass
sudo docker build -t amass .
```
2. You give docker the github path:
```
sudo docker build -t amass https://github.com/OWASP/Amass.git
```

The former being preferable for developers and the latter for users.

**Comment by attackercan** [comment]
Gotcha, thx for clarification!

My task was to have a Dockerfile which produces a container with a fresh copy of amass from Github repo **without** copying sources to the host machine. For this task, I should definately construct my own Dockerfile with all necessary workflow, instead of grabbing your Dockerfile and asking you to modify it.

I'm closing the issue, just leave it is a reference in case someone faces the same problem in future.
